### ISSUE TITLE
Pygame doesn't run on NixOS if installed via pip (1857)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1024]
#  **Issue &numero;1857 opened by *[robertpfeiffer](https://github.com/robertpfeiffer)* at 2020-05-25 09:05:15**

Looks like the prebuilt wheels don't find Xlib on NixOS if SDL2 was not installed via nix package manager.<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2020-05-30 10:54:16*

The solution might be not to use the prebuilt binaries on NixOS, but to tell pip to always compile from source

**Comment by Starbuck5** [comment]
Closing in favor of #2967, a more recent NixOS issue.
