### ISSUE TITLE
Generate pygame.QUIT events in full-screen environments like RPi (2066)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1095]
#  **Issue &numero;2066 opened by *[robertpfeiffer](https://github.com/robertpfeiffer)* at 2020-09-02 15:25:56**

On a raspberry Pi with SDL_VIDEODRIVER="rpi", there is no window manager that sends us SDL_QUIT events when Alt+F4 is pressed.<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2022-02-27 10:23:29*

It's probably more appropriate to wait for a fix from the SDL side

**Comment by MyreMylar** [comment]
The standard fullscreen raspberry pi driver for raspberry pi OS is now wayland.

I just checked and setting the wayland driver on the Pi generates pygame.QUIT events when alt+F4 is pressed in full screen mode.
