### ISSUE TITLE
Create example for multi-player joystick handling in examples/ (2078)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1099]
#  **Issue &numero;2078 opened by *[robertpfeiffer](https://github.com/robertpfeiffer)* at 2020-09-05 11:53:14**

There should be an example program that reacts to hotplugging events based on the new API implemented by @lordmauve.
It should correctly handle pushed buttons on newly plugged-in controllers, and demonstrate un-plugging and re-plugging of controllers, as well as selecting the right controller from multiple connected ones.

I think it could be a simple thing, like a character selector in a couch multiplayer game, with character selection features like:

- press A to join
- press B to leave
- hold A when ready
- use left stick to select character (Like a letter A, B, or C, I don't think we should polish the graphics here)

and possibly a "main game" mode that prints the input events of every "player" and pauses the game when a gamepad is "disconnected".
<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2020-09-05 12:38:24*

Probably the examples/eventlist.py should be modified to handle it too(or instead?).

Related to the new joystick PR merged in which adds support for hotplugging/etc. https://github.com/pygame/pygame/pull/2027
<hr>

# # #  **[yudonglin](https://github.com/yudonglin)* commented at 2020-09-06 04:14:55*

I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.

Here is part of the codes, please do not copy:
```
class SingleJoystick:
    def __init__(self):
        if pygame.joystick.get_init() == False:
            pygame.joystick.init()
        self.inputController = None
        self.update_device()
    def update_device(self):
        if pygame.joystick.get_count()>0:
            self.inputController = pygame.joystick.Joystick(0)
            self.inputController.init()
        else:
            self.inputController = None
    def get_init(self):
        if self.inputController != None:
            return self.inputController.get_init()
        else:
            return False
    def get_button(self,buttonId):
        if self.inputController != None and self.inputController.get_init() == True:
            return self.inputController.get_button(buttonId)
        else:
            return None
    def get_axis(self,buttonId):
        if self.inputController != None and self.inputController.get_init() == True:
            return self.inputController.get_axis(buttonId)
        else:
            return 0
```
<hr>

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2020-09-06 08:15:46*

@yudonglin 
> I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.

There's already a new API implemented in C, generating events when controllers are plugged in, merged in with # 2027. The example should use that.
<hr>

# # #  **[yudonglin](https://github.com/yudonglin)* commented at 2020-09-10 04:35:05*

> @yudonglin
> 
> > I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.
> 
> There's already a new API implemented in C, generating events when controllers are plugged in, merged in with # 2027. The example should use that.

That codes in joystick_calls.py are already good enough. Besides, I only have one controller, so we probably need someone with 2 controllers to help us continue this project. In the best scenario, it should be both Xbox and the ps4 controller. Also, I hope that the event.key can be designed to return the button get press or the axes of the joystick when event.type is pygame.JOYBUTTONDOWN.

For hot-plugging, the only thing we can do (and what joystick_calls.py does) is to look for the device every time the screen gets updated if the (default or certain) joystick is not initialized. Maybe this can be done using multi-threaded for better performance.

**Comment by zoldalma999** [comment]
I think this would be nice. It should use the `pygame.JOYDEVICEADDED` and `pygame.JOYDEVICEREMOVED` events to detect if a joystick has been connected or disconnected.
