### ISSUE TITLE
SDL2 display.set_palette (2099)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1108]
#  **Issue &numero;2099 opened by *[illume](https://github.com/illume)* at 2020-09-14 04:50:59**

set_palette is not supported in SDL2

See display.set_palette PR and issue:
- https://github.com/pygame/pygame/issues/1754
- https://github.com/pygame/pygame/pull/1972

# # #  SDL Palette documentation

https://wiki.libsdl.org/SDL_Palette
https://wiki.libsdl.org/SDL_SetPaletteColors
https://wiki.libsdl.org/SDL_AllocPalette
https://wiki.libsdl.org/SDL_FreePalette

# # #  pygame.display.set_palette documentation
https://www.pygame.org/docs/ref/display.html# pygame.display.set_palette
```
 pygame.display.set_palette()
    Set the display color palette for indexed displays
    set_palette(palette=None) -> None
```
>    This will change the video display color palette for 8-bit displays. This does not change the palette for the actual display Surface, only the palette that is used to display the Surface. If no palette argument is passed, the system default palette will be restored. The palette is a sequence of RGB triplets.
<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2020-09-14 09:31:52*

It's easy to emulate this with OpenGL, or to have a layer of indirection to perform the palette swap every time on pygame.display.update. I'm not sure if it's worth implementing the ugly but reliable solution here.

(The ugly but reliable solution would be to do the palette-swap in software. OpenGL is out of the question for reasons of portability. Even doing the swap with Renderer would mean adding fuctionality to upsteam SDL2)
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2020-10-25 11:18:39*

From what I can tell, there is no easy solution for this. There are some [users of this function](https://github.com/search?q=%22pygame.display.set_palette%22&type=code), so it's important. However, there's no way to address it before the release of pygame 2 on the 28th of Oct. For these reasons I'll remove the critical label, and this can be added to a list of things that are not compatible (along with cdrom, and scrap) in the release.

**Comment by zoldalma999** [comment]
I think we can close this issue, as there has not been any issues requesting this for a while now (as far as I can tell), and it is not that easy to implement this either
