### ISSUE TITLE
Trouble playing mp3 files tagged with mutagen (2134)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1123]
#  **Issue &numero;2134 opened by *[cheofusi](https://github.com/cheofusi)* at 2020-10-02 10:25:13**

After tagging an audio file with mutagen pygame no longer seems to be able to play the file. It however loads the file successfully and the call to pygame.mixer.music.play() throws no error. I actually use the music-tag library which is just a wrapper around mutagen for tagging the files.

On removal of the tags pygame plays the file but the audio is very different from the actual audio on the file. Other media players play the both the tagged and untagged file just fine<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-10-02 12:24:44*

What version of pygame are you using?
<hr>

# # #  **[cheofusi](https://github.com/cheofusi)* commented at 2020-10-02 16:19:38*

version 1.9.6

<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-10-02 16:33:28*

Then the first thing to try is using pygame 2.0.0.dev12, mainly because 1.9.6 uses SDL1 which had lots of issues with mp3 files.

You can install it from pip at the command line in the usual way:

`python3 -m pip install pygame==2.0.0.dev12`

Or via your IDE of choice.
<hr>

# # #  **[cheofusi](https://github.com/cheofusi)* commented at 2020-10-02 17:33:14*

pygame 2.0.0.dev12 doesn't fix the problem

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2020-10-02 18:44:50*

pygame uses libmpg123 through sdl_mixer for mp3s. Which is supposed to be a pretty good mp3 library.

- What OS version are you using I wonder?
- The windows SDL_mixer has a mpg123-1.25.13... which is from 2019-10-26. Which is pretty new. Linux and Mac are even newer.
- can you try playing it with mpg123? This way we could see if it's an SDL_mixer+mpg123 issue. If it plays fine with mpg123, then it's an SDL_mixer issue.
- playback might be to do with sample rate miss-match between the mp3 sample rate, and the sound card. What 44khz or 48khz? SDL_mixer sample rate conversion is not the nicest. You could try changing sample rates with pygame.mixer.pre_init or pygame.mixer.init.

<hr>

# # #  **[cheofusi](https://github.com/cheofusi)* commented at 2020-10-02 21:48:15*

The tagged song plays fine with mpg123. For songs which have been tagged and then had their tags removed, the sample rate mis-match was the cause of shitty audio coming out these files. Manually setting the frequency of pygame.mixer.init to the sample rate of file fixes the audio. So problem is

1.  mpg123 plays tagged files while pygame doesn't
2. removing the tags from tagged files causes a sample rate miss-match
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-10-03 12:22:43*

What OS are you using?
<hr>

# # #  **[cheofusi](https://github.com/cheofusi)* commented at 2020-10-03 17:09:17*

debian buster

<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-11-21 03:59:18*

Does the issue still happen on the latest pygame version (2.1 at the time of writing of this comment)? Also can you post the tagged audio file here so that it can be easier to debug and test this issue on different platforms? :)

**Comment by MyreMylar** [comment]
This could be tested again. SDL_mixer has undergone a few changes since this was posted.

The library being used to edit mp3 file metadata was this one: https://pypi.org/project/music-tag/

Should be able to pip install it and edit some tags like this:

```python
import music_tag

file = music_tag.load_file("test.mp3")
file['title'] = 'Testy McTestTitle'
file['artist'] = 'Testy McTesterson'
file.save()
```

Then try loading and playing the tagged file in pygame with `pygame.mixer.music.play()`

**Comment by MyreMylar** [comment]
Test program:

```
import pygame

import music_tag


file = music_tag.load_file("mp3s/Danny Bale - On the Throne.mp3")
file["title"] = "Test Adding a Tag"
file["artist"] = "Test another tag"
file.save()

pygame.init()

pygame.mixer.music.load("mp3s/Danny Bale - On the Throne.mp3")
pygame.mixer.music.play()
 # does the audio play?
screen = pygame.display.set_mode((800, 600))

running = True

while running:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    if not pygame.mixer.music.get_busy():
        print("Song finished!")

    pygame.display.flip()

```

**Comment by MyreMylar** [comment]
I was able to successfully tag mp3s with mutagen via the music-tag python package on linux (Raspberry Pi 5) and on Windows and have the tags successfully applied to the files and the mp3s still play perfectly fine before and afterwards in pygame-ce 2.4.0/2.5.0.

See the code snipped pasted above for a test program.
