### ISSUE TITLE
Mouse input incorrect after multiple calls to set_mode() (2186)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1143]
#  **Issue &numero;2186 opened by *[lordmauve](https://github.com/lordmauve)* at 2020-10-13 22:46:53**

A user [reported an issue in Pygame Zero](https://github.com/lordmauve/pgzero/issues/230#issuecomment-708039034) where mouse coordinates are clamped to [0, 99].

Pygame Zero creates an initial 100x100 window in order to be able to call Surface.convert_rgba(), and immediately (same frame) resizes it to the real dimensions. So this bug appears to be that input events are being produced based on the original size of the window, not the new size.

Perhaps this is a race condition: triggering a resize a couple of frames later resolves the issue.

Versions:
Pygame 1.9.6
SDL 1.2.15
Archlinux
Reproducible in PyPI package (manylinux wheels?)<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-10-18 10:33:27*

There are a few odd issues with multiple calls to `display.set_mode()`. See: # 212, # 993 & # 2100 . So clearly calls to it are not completely independent of one another.

A window/display resize function, if we had one, might be a better way to approach this use case. Then we could probably steer subsequent call to `set_mode()` to that function most of the time (assuming flags and depth are the same) and avoid the issue.

None of this will help pygame 1.9.6 of course.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-10-18 10:35:10*

Would be good to get this tested on more platforms and more recent version too to assess severity.

**Comment by MyreMylar** [comment]
Test program:
```python
import pygame

pygame.init()

screen = pygame.display.set_mode((100, 100))
screen = pygame.display.set_mode((800, 600))

running = True

while running:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    print(pygame.mouse.get_pos())

    pygame.display.flip()
```

**Comment by MyreMylar** [comment]
OK, the original issue is now closed for pygame zero and much time has passed. 

I've tried reproducing it with the test program above that mimics the original conditions (a set mode call at a small size, followed by a same frame resize to a larger window) and I can't reproduce this issue on recent pygame-ce (2.4.0/2.5.0) on linux (raspberry PI OS/raspberry pi 5) or on a Windows PC.
