### ISSUE TITLE
Enhancement: Add display server/windowing system to support prompt (2540)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1304]
#  **Issue &numero;2540 opened by *[robertpfeiffer](https://github.com/robertpfeiffer)* at 2021-03-29 08:45:35**

If pygame is running under X11, wayland, or XWayland, if we have any way to detect this, maybe we should consider printing this in the support prompt. There are many display bugs that are impossible to diagnose without this info.

We should probably *also* print the processor architecture if it's anything other than x86_64.<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2021-04-21 12:35:47*

This is impossible to google. I have no idea if there is any way to query the X Server for information about concrete implementation details. It might be possible by bypassing SDL, but X or X server is just too short. I get information about Apple XServe hardware.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-04-07 10:28:28*

Is this what we need:
https://wiki.libsdl.org/SDL_GetCurrentVideoDriver

**Comment by MyreMylar** [comment]
display driver and architecture details are now included in pygame.print_debug_info(). I think this is the correct place from this level of detail, we can probably also start asking people to supply the print out of print_debug_info() in bug report templates....

In fact I'll add that in a PR now.
