### ISSUE TITLE
Multiline support missing (2574)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1326]
#  **Issue &numero;2574 opened by *[Loremoth](https://github.com/Loremoth)* at 2021-04-30 23:28:48**

It seems very strange to me that a famous videogame library like this misses simple support for writing multiline text on screen. I hope it will be fixed soon...<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-05-02 01:04:13*

It's not like pygame has just forgotten to do this, it's more that "GUI" stuff has been seen as "out of scope" for pygame itself.

However, this could probably be doable. There could be a `wrap_pixel` keyword argument on font.render and freetypefont.render. Probably would need a spacing factor kwarg too. But would it also have to handle `\n` and `\t` characters?

I wonder what people who have written GUI libraries for pygame think. Could this simplify / optimize your workflow? Should pygame add this? What sort of interface should it use? @ppizarror @MyreMylar
<hr>

# # #  **[ppizarror](https://github.com/ppizarror)* commented at 2021-05-02 01:16:59*

I think there's plenty of libraries that wrap text, for example ``textwrap`` (used by pygame-menu); having a simple core API is better because this kind of feature would not be used for many people, as in general a GUI library is preferred.

For example, if that ``wrap_pixel``is implemented, what is the distance between lines? (so, line height should also be provided). And about new lines (\n, \t), or language support (for word-breaking). And what about RTL-languages, and the text remaining these lines, they must be centered, justified, left, right? There's a lot of things to wonder. Generally this high-level features introduce lots of problems.

In the case of pygame-menu (https://github.com/ppizarror/pygame-menu) ``textwrap`` is used (and \n, \t support too), and it returns a list of widgets that can be manually fine-tuned by the user (generally they do).
<hr>

# # #  **[Farbfetzen](https://github.com/Farbfetzen)* commented at 2021-05-02 17:17:17*

For anyone who wants to implement this for themselves there is a helpful example in the docs: https://www.pygame.org/docs/ref/freetype.html# pygame.freetype.Font.render_to
<hr>

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2021-05-09 15:22:42*

In the past this would have been closed as wontfix, because it can easily be done in pure Python, and typesetting whole paragraphs is definitely out of scope.
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-12-28 04:04:30*

I agree, this kind of feature is probably best implemented in user code, or a 3rd party pygame library. pygame has always been a lower level tool which you can use to build your engine and game on, and this feature would need a higher level API, with the existing pygame API it would not be elegant to integrate this feature. There are many good libs that use pygame and provide this feature.
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-12-28 06:08:14*

I disagree, I think this functionality can and should be added into base pygame.

It's a big edge for users to go from rendering single lines of text to full GUI libraries. And it seems awfully inconvenient for users to have to reimplement the same functionality over and over, if they aren't aware of GUI libraries or don't wish to use them.

The fact that we have reference code on how to do this supports that it is a common operation that we can abstract.

I suggest a single additional optional argument to Font.render and freetype.Font.render (and variations, but hopefully they are centralized under the hood). It could be named something like `typesetting`, and would be a dictionary containing certain keys, settings.
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-12-28 06:25:42*

I see this is a pretty useful thing indeed, but I also believe that incase we add this to pygame, it would need a nicer, higher level API to make it more pleasant to work with, rather than adding more hacks to existing API. [pygame-text](https://github.com/cosmologicon/pygame-text) is a really nice module, solely dedicated to multiline font rendering. If pygame did add multiline support on its own, perhaps we could talk with the owners of this lib to have some integration with pygame, rather than having to re-invent the wheel again on our end. OFC, another solution is to just let things be as is, users who need this feature can easily use this library, or any other thing

**Comment by Starbuck5** [comment]
Fixed in #1898
