### ISSUE TITLE
pygame resizing display grabs background (2578)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1329]
#  **Issue &numero;2578 opened by *[gresm](https://github.com/gresm)* at 2021-05-04 18:15:00**

**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** : Linux
- **Python version** : 3.9.4
- **SDL version** : 2.0.14
- **PyGame version** : 2.0.1
- **Relevant hardware** : ??? (what)

**Current behavior:**

When you resize the window using pygame.display.set_mode new area is the background

**Expected behavior:**

New area should be black

**Screenshots**

![image](https://user-images.githubusercontent.com/78505251/117049807-ece03580-ad14-11eb-9ba7-a46bcfa5dc7b.png)

![image](https://user-images.githubusercontent.com/78505251/117049893-08e3d700-ad15-11eb-8614-943a8c289c66.png)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. see
2. the
3. test code

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.display.set_mode((100, 100))
pygame.display.set_mode((500, 500))
```

**Stack trace/error output/other error logs**

```
No errors raised.
```
<hr>

#  Comments

# # #  **[gresm](https://github.com/gresm)* commented at 2021-05-04 18:20:21*

It works like screen grabbing:
![image](https://user-images.githubusercontent.com/78505251/117050539-bf47bc00-ad15-11eb-9e40-dfb59616a7a6.png)
But at reality pixels are completly transparent:
![image](https://user-images.githubusercontent.com/78505251/117050852-24031680-ad16-11eb-8ab4-5a2086e6d463.png)

<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-05-04 18:38:14*

Can you be more specific than "Linux"? That looks like the Ubuntu desktop. What version of what distro are you using?

If you're on the newest Ubuntu, are you using Wayland (which is the default now)?

If you fill the display, and then `flip` or `update` the display, does this go away? Basically, would this hobble a complete pygame app or not?
<hr>

# # #  **[gresm](https://github.com/gresm)* commented at 2021-05-05 06:43:16*

cat /etc/os-release returns:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

<hr>

# # #  **[mljli](https://github.com/mljli)* commented at 2021-06-03 16:21:14*

Looks like it's by design. You can call display.flip() manually to update the window.

@Starbuck5 Or shall we change the default haviour?

```
if (!win) {                                                                        
    /*open window*/                                                                
    win = SDL_CreateWindow(title, x, y, w_1, h_1, sdl_flags);                      
    if (!win)
        return RAISE(pgExc_SDLError, SDL_GetError());                              
    init_flip = 1;
}

/* ... */

/* ensure window is initially black */
if (init_flip)
    pg_flip_internal(state);
```
<hr>

# # #  **[gresm](https://github.com/gresm)* commented at 2022-04-05 16:44:03*

Still an issue for pygame 2.1.2
![image](https://user-images.githubusercontent.com/78505251/161804491-98ac392d-4b0e-4f32-944c-68c0972a3851.png)

<hr>

# # #  **[hl037](https://github.com/hl037)* commented at 2022-04-07 08:03:55*

+1 on Archlinux.

This bug is labled "minor", but this one will make me have to use another engine...
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-04-07 10:35:37*

Does this happen with a more complete pygame program?

```
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480))

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

small_size = True

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN and event.key == pygame.K_RETURN:
            if small_size:
                screen = pygame.display.set_mode((800, 600))
                white_background = pygame.Surface(screen.get_rect().size)
                white_background.fill((255, 255, 255))
                small_size = False
            else:
                screen = pygame.display.set_mode((640, 480))
                white_background = pygame.Surface(screen.get_rect().size)
                white_background.fill((255, 255, 255))
                small_size = True

    screen.blit(white_background, (0, 0))
    pygame.display.flip()


pygame.quit()

``` 
<hr>

# # #  **[hl037](https://github.com/hl037)* commented at 2022-04-07 12:56:41*

Oh, I realize that my bug is not actually the same than the one described here...
(your code works and does not produce any flickering on my system)

Mine happens with *resizeable* window... maybe should I open a distinct issue ?

Another thing that you do that I didn't is to blit a surface to the screen while I just called fill on the screen surface.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-04-07 14:05:44*

> Oh, I realize that my bug is not actually the same than the one described here... (your code works and does not produce any flickering on my system)
> 
> Mine happens with _resizeable_ window... maybe should I open a distinct issue ?
> 
> Another thing that you do that I didn't is to blit a surface to the screen while I just called fill on the screen surface.

Here is my version of a basic resizable window application:

```
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480), pygame.RESIZABLE)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

small_size = True

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.WINDOWRESIZED:
            white_background = pygame.Surface(screen.get_rect().size)
            white_background.fill((255, 255, 255))
         
    screen.blit(white_background, (0, 0))
    pygame.display.flip()


pygame.quit()

```
<hr>

# # #  **[gresm](https://github.com/gresm)* commented at 2022-04-07 20:19:34*

I can confirm that code above (by @MyreMylar ) makes window to flicker, but it seems like it is caused by the fact that every time the window is resized, pygame has to make new surface, so the data from earlier version is erased...
But this needs separate issue...
<hr>

# # #  **[bydariogamer](https://github.com/bydariogamer)* commented at 2022-04-22 06:56:06*

I was unable to reproduce this code in python 3.10.4 compiled with GCC 11.2.0 on an Arch Linux with GNOME 42.0 desktop using pygame 2.1.2 and SDL 2.0.16:

![image](https://user-images.githubusercontent.com/62303655/164620135-59e78016-9c0b-4d6a-a50f-399ac0c6538b.png)

<hr>

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-11-02 00:55:21*

I was able to reproduce this on pygame 2.1.3dev8 compiled with SDL 2.0.22 and python 3.10.7 compiled with GCC 12.2.0. OS is Manjaro linux with the KDE Plasma desktop environment (X11). I do not believe this to be a bug in pygame or SDL because I get the same effect using the SFML library with my own C++ code if I haven't written anything to the screen yet.

**Comment by bilhox** [comment]
Environment:

Operating system : Ubuntu 22.04
Python version : 3.10.12
SDL version : 2.26.5
PyGame version : 2.3.2

I was unable to reproduce the problem.

**The code :**

```py
import pygame

pygame.display.set_mode([200, 200])
pygame.display.set_mode([400, 300])
```

State one :
![image](https://github.com/pygame-community/pygame-ce/assets/69472620/effcccf3-185a-44cf-b05a-8c6c95ec54da)
State two :
![image](https://github.com/pygame-community/pygame-ce/assets/69472620/0e493eb3-67c0-45cb-a2b5-2d35c24b7ded)

**Comment by ankith26** [comment]
Cannot reproduce the original issue anymore (Ubuntu 23.10)
`pygame-ce 2.4.0.dev3 (SDL 2.28.3, Python 3.11.6)`

The crux of the original issue was that subsequent calls to `set_mode` don't clear the window, but post pygame(-ce) 2.1.3 the screen is forced to black on every `set_mode` call. 

With resizing, it is important to redraw and update/flip after resizing to not see the garbage surface data on the window.
