### ISSUE TITLE
Change mixer.music.load/queue to emit FileNotFoundErrors (2792)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1431]
# **Issue &numero;2792 opened by *[Starbuck5](https://github.com/Starbuck5)* at 2021-10-24 03:08:27**

Right now they emit pygame.errors when they can't find a file. It should be a FileNotFoundError, like any other resource loader.

This issue is just to remember to change this on a release we can break compat slightly.<hr>

# Comments

**Comment by MyreMylar** [comment]
This has already been changed to FileNotFoundErrors:

```
Traceback (most recent call last):
  File "C:\Users\dan\Programming\scrap\music_mutagen_tagging.py", line 13, in <module>
    pygame.mixer.music.queue("mp3s/Danny Bole - On the Throne.mp3")
FileNotFoundError: No file 'mp3s/Danny Bole - On the Throne.mp3' found in working directory 'C:\Users\dan\Programming\scrap'.
```
