### ISSUE TITLE
Find issues in new SDL releases earlier (2941)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1493]
#  **Issue &numero;2941 opened by *[illume](https://github.com/illume)* at 2021-12-22 01:36:32**

With each SDL release there's usually at least one test suite failure. There's also often a bug that we find some time after release on a users machine.

There is usually an SDL pre-release, but even when we report issues they are not fixed in time. Or the issues take more than 1-3 days we have to find them or make a bug report. Or no one notices the pre-release, or no one has time to try things out.

How to try and prevent issues appearing in SDL?

Some possibilities:
- get SDL default/main branch on our machines so we can test it as it is developed and catch errors earlier.
- test SDL main branch on our CI for each platform (or at least one)
- get some SDL_VIDEODRIVER != "dummy" tests on CI, since some issues are not found using the dummy driver
- get pygame tests being run on SDL CI?
<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-12-22 01:55:44*

Those are good ideas.

I like the idea of getting SDL-main on some of our CI, and getting contributors developing stuff with it.

I can't find any build artifacts from the SDL github for Windows, so it might be difficult on that platform.

**Comment by Starbuck5** [comment]
I still think this is a good idea overall, but the occurrence of new failures has gone down and there are no active plans to do this. It would also be challenging to do, probably wouldn't make sense on PRs, like background job every week to test SDL2-main. But then how would people see the failures?

Anyways, there are no active plans to work on this as far as I know, so lets close as not planned.
