### ISSUE TITLE
Mouse click event appear twice in touchscreen  (2992)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1514]
#  **Issue &numero;2992 opened by *[huanyun0](https://github.com/huanyun0)* at 2022-01-19 08:20:04**

Environment:

- Operating system (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 7
- Python version (e.g. 3.7.9, 3.8.5) :  3.8.0
- SDL version (e.g. SDL 2.0.12):  2.0.18
- PyGame version (e.g. 2.0.0.dev10, 1.9.6):  2.1.2
- Pyinstaller version:  4.5.1

Current behavior:
   I create an exe file and run it on touchscreen in windows7. Sometimes when I touch the screen it appears two click events(MOUSEBUTTONDOWN and MOUSEBUTTONUP appear twice, but FINGERUP and FINGERDOWN appear once).The most important thing is that the touch property of the second MOUSEBUTTONDOWN is False(MOUSEBUTTONUP also), but I don't press the mouse.

Expected behavior:

   Pygame can only capture one mouse event when I touch the screen once.

Steps to reproduce:
  
1. Open the program and touch the screen.

Test code:

```
import pygame

if __name__ == '__main__':
    pygame.init()
    window = pygame.display.set_mode((500,300))
    pygame.display.set_caption("Test")
    pygame.event.set_blocked(None)
    pygame.event.set_allowed([pygame.MOUSEBUTTONUP, pygame.MOUSEBUTTONDOWN, pygame.QUIT,
                              pygame.FINGERUP, pygame.FINGERDOWN, pygame.KEYDOWN, pygame.KEYUP])
    is_work = True
    while is_work:
        for e in pygame.event.get():
            print("event = ", pygame.event.event_name(e.type)," ", e.dict)
            if e.type == pygame.QUIT:
                is_work = False
                break
        pygame.display.update()
    pygame.quit()
```
<hr>

#  Comments

# # #  **[huanyun0](https://github.com/huanyun0)* commented at 2022-01-19 10:00:49*

![bug](https://user-images.githubusercontent.com/50545596/150108063-c32f85f4-fe5b-4f71-a9e3-13eebb009164.PNG)

<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-01-19 11:53:54*

Hi, thanks for the bug report! My hypothesis is that there's two things going on here.
1) The OS is virtualising the touch screen as a secondary mouse, generating mouse events that look like real mouse events to SDL and therefore to pygame as well.
2) SDL generates the mouse events that have `touch=True` when the OS recognises a touch screen update. This is also documented in SDL docs, and is perfectly intentional behavior (from my little search, it does not seem that there is a way to disable it, but maybe there should be). The [SDL_MouseButtonEvent docs](https://wiki.libsdl.org/SDL_MouseButtonEvent) docs also says
> You might want to ignore such events, if your application already handles SDL_TouchFingerEvent.

A workaround for you is to ignore mouse events that have `touch=True` in your code, and handle finger events separately.
<hr>

# # #  **[huanyun0](https://github.com/huanyun0)* commented at 2022-01-19 12:10:12*

You can see the screenshot above. The two MOUSEBUTTONUPs (one touch is True, one is False) are generated when I touch the screen once.The first MOUSEBUTTONUP I can ignore, but the touch property of the second MOUSEBUTTONUP is False. How can I differentiate it from an event triggered with a real mouse? (The second MOUSEBUTTONUP does not always appear)
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-01-21 17:26:53*

Hmmm, I don't think you can differentiate those, unless you (probably?) change some OS settings and not have it emulate a mouse with a touchscreen device?

**Comment by byTrident** [comment]
I just came across this problem and even though my touchscreen laptop is broken right now, i thought of the idea that maybe after getting the MOUSEBUTTONDOWN event, the programm starts a short timer and if after that timer screen is touched, a screen touched variable gets set true and if not the variable gets set false, same with the mouse. And of course in the while loop you can check if the variables are true and write your code in the if statement but you have to set it back to false in the end so it doesnt repeat infinitely.

Here is the code:
```
import pygame

if __name__ == '__main__':
    pygame.init()
    window = pygame.display.set_mode((500,300))
    pygame.display.set_caption("Test")
    pygame.event.set_blocked(None)
    pygame.event.set_allowed([pygame.MOUSEBUTTONUP, pygame.MOUSEBUTTONDOWN, pygame.QUIT,
                              pygame.FINGERUP, pygame.FINGERDOWN, pygame.KEYDOWN, pygame.KEYUP])
    is_work = True
    clock = pygame.time.Clock()

    finger_pressed = False
    mouse_down = False
    finger_down = False
    mouse_timer = 0.01
    mouse_timer_started = False

    while is_work:
        for e in pygame.event.get():
            print("event = ", pygame.event.event_name(e.type)," ", e.dict)
            if e.type == pygame.QUIT:
                is_work = False
                break
            if e.type == pygame.MOUSEBUTTONDOWN:
                mouse_timer = 0.01
            if e.type == pygame.FINGERDOWN:
                finger_pressed = True

        mouse_timer -= 0.005

        if mouse_timer <= 0 and finger_pressed == True:
            finger_down = True
            mouse_down = False
            finger_pressed == False
        else:
            finger_down = False
            mouse_down = True
            finger_pressed == False

        if finger_down:
            # do stuff if screen touched
            finger_down = False
        
        if mouse_down:
            # do stuff if mouse pressed
            finger_down = False

        clock.tick(60)
        pygame.display.update()
    pygame.quit()
```

I hope this helps with a problem you had half a year ago 😄

**Comment by MyreMylar** [comment]
I can't reproduce this generically on a touchscreen after many attempts to produce duplicate mous button up events after touching a touch screen. I think we'll have to assume that this was fixed at some point along with the many changes to pygame-ce and SDL, or it was specific to the original poster's hardware combination.

If anyone else manages a reproduction - please let us know here and we can re-open.
