### ISSUE TITLE
font.SysFont() always silently fallback to the default font; but font.Font() works (3025)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1535]
#  **Issue &numero;3025 opened by *[xuancong84](https://github.com/xuancong84)* at 2022-02-11 12:05:06**

On my Ubuntu/Linux x86_64, the font `simhei.ttf` is installed as a system font, and `pygame.font.get_fonts()` shows "simhei" in the list.

If I create a font using `pygame.font.SysFont("simhei", 60)`, all Chinese characters are displayed as a square. But no error is reported, so I assume the system must have silently fallback to the default font.

If I create a font using `pygame.font.Font("/usr/local/share/fonts/simhei.ttf", 60)`, all Chinese characters are displayed correctly.

So apparently, the SysFont function is not working properly. And I also checked, the same bug applies to `pygame.freetype.SysFont()` as well.<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-02-12 09:00:06*

I'm really not sure how that would happen.

Is this dependent on pygame version? What pygame version are you using?

If you print out `pygame.sysfont.Sysfonts` after putting into a Sysfont request to initialize it, it will show you the state that the Sysfont module is working with. It should show "simhei" and its filepath as a key value pair.

The sysfont code is in python so if you end up debugging it yourself, it'll be easier than working in one of the modules written in C. Some relevant code: https://github.com/pygame/pygame/blob/main/src_py/sysfont.py# L432-L474

And if you want to debug this, you might need the relevant compilation guide for your system: https://www.pygame.org/wiki/CompileUbuntu

**Comment by MyreMylar** [comment]
This works fine in my testing. 

- Simhei installed as system font.
- Run test program:

```python
import pygame

pygame.init()

pygame.init()
clock = pygame.time.Clock()
clock_FPS = 60


screen = pygame.display.set_mode([800, 800])

font = pygame.font.SysFont("simhei", 60)
drawn_text = font.render("GUI事件传入 退出", True, pygame.Color("white"))

while True:
    clock.tick(clock_FPS) / 1000

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()

    screen.fill((0, 0, 0))

    screen.blit(drawn_text, (0, 0))
    pygame.display.update()
```

See Chinese characters on the screen.
