### ISSUE TITLE
Why can't I sign in with my Gmail email? (3030)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1536]
#  **Issue &numero;3030 opened by *[RixInGithub](https://github.com/RixInGithub)* at 2022-02-14 18:55:48**

Well, I can't signup or login with my email:

Well, since you are not thiefs or something, I revealed my email

But, I want to know here, why can't I sign up with it. I will wait for a confirmation email from whatever.

[**HAVE TO REMOVE THIS**]<hr>

#  Comments

# # #  **[gresm](https://github.com/gresm)* commented at 2022-02-14 19:10:52*

Where you can't signup / login with your email?
<hr>

# # #  **[MightyJosip](https://github.com/MightyJosip)* commented at 2022-02-15 09:07:14*

Hello!

Thank you for your bug report in the Issues section of Pygame GitHub organization. After a long investigation where top experts for Pygame have gathered and discussed this problem we can confirm this has been fixed in the most recent Pygame version 🎉 

You need to install Pygame with`python3 -m pip install pygame==2.1.2`
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-02-15 09:29:17*

Be nice MightyJosip.

@RixInGithub Presumably you're referring to pygame.org. Registration has been disabled for a while because of spam getting posted, we're aware of the problem. Hopefully it can be enabled again in the future.
<hr>

# # #  **[RixInGithub](https://github.com/RixInGithub)* commented at 2022-02-15 20:01:01*

> Be nice MightyJosip.
> 
> @RixInGithub Presumably you're referring to pygame.org. Registration has been disabled for a while because of spam getting posted, we're aware of the problem. Hopefully it can be enabled again in the future.

Oh dang 👎🏻

**Comment by RixInGithub** [comment]
uhh can you please edit out my email pls

**Comment by MightyJosip** [comment]
> uhh can you please edit out my email pls

Done

**Comment by RixInGithub** [comment]
> > uhh can you please edit out my email pls
> 
> Done

thank you very muchie :)

**Comment by oddbookworm** [comment]
Unfortunately, none of us have the ability to do that. You’re gonna have to ask on that issue for that. We’re all banned from that repository

**Comment by oddbookworm** [comment]
Or since it’s your issue, you might be able to edit it out yourself?

**Comment by RixInGithub** [comment]
> Or since it’s your issue, you might be able to edit it out yourself?

i thought this was the original my issue. thanks guys for letting me edit out my original original issue too!
