### ISSUE TITLE
The `buildconfig` of MSYS2 may need to be updated (3149)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1590]
#  **Issue &numero;3149 opened by *[wszqkzqk](https://github.com/wszqkzqk)* at 2022-04-23 05:31:24**

**Description**

There're more environments in MSYS2 now besides `x86_64` and `i686`, like `ucrt64`, `clang64` and `clang32`.

Also, the build process with MSYS2 fails due to compile errors now.<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-05-02 05:27:34*

Thanks for the bug report. I don't believe any pygame contributors actually use it on MSYS2, so I wouldn't put stock on it being fixed anytime soon.

If you want to fix it up we'll be happy to check out a pull request.

**Comment by ankith26** [comment]
With the upcoming meson port, supporting msys2 fully should be much easier. The only think left to do is to add a basic CI that can test this stuff, which I plan to tackle in that PR
