### ISSUE TITLE
More global key information (3175)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1600]
#  **Issue &numero;3175 opened by *[Starbuck5](https://github.com/Starbuck5)* at 2022-05-11 09:58:52**

**Description**

I'd like to add the functions `pygame.key.get_just_pressed()` and `pygame.key.get_just_released()` to make it possible for entities to get more information about keyboard state without being tied to the event loop.

When I say entities, I'm assuming there's a list of entities that make up the sprites and "things" of the game. This is a very common pattern.

Imagine you're making an Asteroids game. You want "press held" information for turning and for firing the thruster. However, you want "discrete keypress" for the shooting behavior. You can get the "press held" info "globally" using `pygame.key.get_pressed()`. For "discrete keypress" you can of course turn to KEYDOWN events. 

But how do you pipe your KEYDOWNs to your ship entity? Do you pipe every event to every entity in the event loop, even though the asteroids will never need any events? Do you special case the ship and lose a bit of elegance? This is by no means unsolvable, you could even do falling edge detection on the data from get_pressed. This API just aims to simplify it, give a convenient way to work with key input while in a situation where it's fine / preferable to be decoupled from the event loop.

**Implementation**
Ankith was grilling me about this on discord.

Every time the event system is pumped, it can clear out some global state "dict". And then when it sees KEYUPs or KEYDOWNs it adds them to the relevant "dict." When the user calls `get_just_pressed()` or `get_just_released()` it shows them the data gathered in the last "sample" taken, during the last call to pygame.event.get().

*not a dict, but whatever<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-05-21 06:14:49*

Tiny example to show how I imagine the API looking.

```py
if pygame.key.get_just_pressed()[pygame.K_a]:
  print("A key was just pressed")
```
<hr>

# # #  **[python-ast-person](https://github.com/python-ast-person)* commented at 2022-10-05 22:44:47*

My  proposal(# 3479) would allow you to handle this by defining `Sprite.handle_event()`:
```
class PlayerShip(pygame.sprite.Sprite):
    ...
    listening_events = {pygame.locals.KEYDOWN,}
    def handle_event(self,event):
        if event.type == pygame.locals.KEYDOWN:
            # insert what ever you want to do
        else:
            super().handle_event(event)
    ...
```

**Comment by zoldalma999** [comment]
#1912 has been merged, so this is completed.
