### ISSUE TITLE
New scrap functions (3402)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1674]
#  **Issue &numero;3402 opened by *[Starbuck5](https://github.com/Starbuck5)* at 2022-08-19 06:19:18**

The current scrap API is in place for historical reasons. Copying and pasting images and other media besides text uses bespoke C code that has not been maintained in over a decade, and is no longer even built with pygame, mostly.

We should consolidate functionality with what SDL provides, and is what most people want to do: copy and paste text.

And we should have an API that doesn't require encoding or decoding bytes, text in and out as strings.

These new APIs should live alongside the current scrap functions, which should be deprecated.
ALTERNATIVELY
We could put new copy/paste APIs into the new `pygame.context` module, and deprecate the entire scrap module.

See: https://wiki.libsdl.org/CategoryClipboard<hr>

#  Comments

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-10-22 20:18:23*

I can take a crack at this

**Comment by novialriptide** [comment]
Fixed by https://github.com/pygame-community/pygame-ce/pull/1984
