### ISSUE TITLE
pygame.transform.grayscale() (3478)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1722]
#  **Issue &numero;3478 opened by *[novialriptide](https://github.com/novialriptide)* at 2022-10-05 07:38:32**

Pretty self-explanatory; it's a new function that supports grayscaling a `pygame.Surface`.

The design I'm thinking of is pretty simple as well, just this:
```python
pygame.transform.grayscale(surface: pygame.Surface) -> pygame.Surface
```

# #  Image Example
![image](https://user-images.githubusercontent.com/35881688/194006308-0125d823-35f1-4c29-9d2f-ac72a80fdebc.png)
<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-10-07 04:21:27*

See https://docs.opencv.org/4.x/de/d25/imgproc_color_conversions.html# color_convert_rgb_gray for the RGB -> luminance formula.
<hr>

# # #  **[Jam-Burger](https://github.com/Jam-Burger)* commented at 2022-10-14 09:31:18*

I would like to work on this issue

**Comment by zoldalma999** [comment]
Fixed by #1907
