### ISSUE TITLE
Add a sprite.Sprite.handle_event() hook  (3479)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1723]
#  **Issue &numero;3479 opened by *[python-ast-person](https://github.com/python-ast-person)* at 2022-10-05 21:05:19**

**Description**

I propose to add a hook to `sprite.Sprite` and `sprite.AbstractGroup` to allow sprites to handle their own events instead of the event handling code be in the main loop.

**Proposed API**
This enhancement would add two methods and one attribute to `sprite.Sprite`:

- `Sprite.listening_events` would be a set of events types that the sprite wants to listen for. If it is changed, `self.update_listening_events()` should be called.
- `Sprite.handle_event()` ,like `Sprite.update`, is a by default empty method designed to be overridden in a subclass. Its purpose is that it would be automatically called when a containing group's `handle_event` method is called if the events type is in the sprite's `listening_events`. Multiple sprites can handle the same event if they listen from it.

In addition, a convenience method `AbstractGroup.handle_events()` could be added, which would take a list of events and call `self.handle_event()` on each.<hr>

#  Comments

# # #  **[Matiiss](https://github.com/Matiiss)* commented at 2022-10-26 19:56:29*

I fail to see the purpose of this, you can already do something like
```py
class MySprite(pygame.sprite.Sprite):
    def update(self, events):
        for event in events:
            #  handle event


some_group = pygame.sprite.Group()
some_group.add(MySprite())

#  mainloop
    events = pygame.event.get()
    for event in events:
        #  handle event
    
    some_group.update(events)
```
also I don't think you should be actually changing the already existing classes, create a new one specifically for this purpose but again, I don't see a purpose here.

**Comment by ankith26** [comment]
I agree with Matt. Most big projects already have event handling mechanisms/templates so I don't think as a library we should make the API that high-level/specialized. For those who need such functionality this should not hard to implement in custom subclasses.
