### ISSUE TITLE
Freeze on Exit with Pygame 2.1.2 Examples (3491)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1726]
#  **Issue &numero;3491 opened by *[Robin-Andrews](https://github.com/Robin-Andrews)* at 2022-10-10 13:14:55**

I'm on Windows 10 using pygame 2.1.2 (SDL 2.0.18, Python 3.10.1).

I've tried pygame.examples.liquid and pygame.examples.stars, and both freeze when I click the exit icon, rather than exiting cleanly. This is not great for people wanting to use the examples to get a sense of good practice with writing Pygame code.

Any chance this could be addressed please?<hr>

#  Comments

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-10-10 17:37:43*

Hello! I'm on windows, and I can't reproduce the bug you describe.

I think it could actually be a bug of the IDE you are using (for instance, there is a weird known bug where pygame games run with IDLE have windows sticking around even after actually being closed. This is probably something having to do with the python process not exactly shutting down, and this is not pygames fault)

Could you test running the example directly from the windows commandline (like `py -m pygame.examples.liquid`) and see whether the issue persists?
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-10-16 03:48:37*

I can't reproduce the issue even in IDLE on 2.1.2.

And all the examples should be compliant with exiting on IDLE now (at least in the latest dev release).
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-10-16 06:42:21*

Yes, `pygame.quit()` was added to the old examples in this commit:
https://github.com/pygame/pygame/commit/8583d58221dd7b58d07a176b3a7214a28c814d95

My guess is that OP might have multiple versions of python & pygame installed, as this bug very was likely present in IDLE before 2.1.2. Either that or they have a more obscure IDE/python setup that is interacting badly.

@Robin-Andrews check the code you are running to see if it has a line like `pg.quit()` at the end. If it hasn't you are on a version before this was fixed, if it has you'll need to explain more about your dev setup.

**Comment by MyreMylar** [comment]
Closing due to no response and unable to reproduce.
