### ISSUE TITLE
On Linux, the window seems to be open twice (3533)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1745]
#  **Issue &numero;3533 opened by *[francis-clairicia](https://github.com/francis-clairicia)* at 2022-11-02 14:05:11**

**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Linux(Manjaro Gnome, kernel 5.15.74-3-MANJARO)
- **Python version**: 3.10.7
- **SDL version**: 2.0.22
- **PyGame version**: 2.1.3.dev8
- **Relevant hardware**: 

**Current behavior:**

When opening a window via `pygame.display.set_mode()`:
- on X11: the window blinks one time before showing up.
- on Wayland: the window blinks one time with a "black flash" taking all the screen before showing up.

**Expected behavior:**

Just open a window.

Works fine in pygame 2.1.2 (SDL 2.0.16).

EDIT: Works fine in pygame 2.1.3.dev6 (SDL 2.0.20) too.

**Screenshots**

EDIT: A screencast describing the problem : https://drive.google.com/file/d/1MtcZYtJv7aKrw8donikvdLLYFLLhbEUE/view?usp=sharing

**Steps to reproduce:**

1. Open a window with `pygame.display.set_mode()`.
2. See what is happening.

**Test code**

```py
import pygame

pygame.init()

pygame.display.set_mode((800, 600))

while True:
    for event in pygame.event.get():
        print(event)
        if event.type == pygame.QUIT:
            pygame.quit()
            exit(0)
```

**Stack trace/error output/other error logs**
The logs that I have from the above test code :

```
pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
<Event(4352-AudioDeviceAdded {'which': 0, 'iscapture': 0})>
<Event(4352-AudioDeviceAdded {'which': 0, 'iscapture': 1})>
<Event(32774-WindowShown {'window': None})>
<Event(32775-WindowHidden {'window': None})>
<Event(32774-WindowShown {'window': None})>
<Event(32777-WindowMoved {'x': 560, 'y': 1357, 'window': None})>
<Event(32770-VideoExpose {})>
<Event(32776-WindowExposed {'window': None})>
<Event(32768-ActiveEvent {'gain': 1, 'state': 2})>
<Event(32785-WindowFocusGained {'window': None})>
<Event(32788-WindowTakeFocus {'window': None})>
<Event(32787-WindowClose {'window': None})>
<Event(256-Quit {})>
```

As you can see, there is two `WindowShown` events before the `VideoExpose` one.
<hr>

#  Comments

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-11-02 14:33:04*

I cannot reproduce this issue on Manjaro with the KDE Plasma desktop (kernel 5.15.76-1-MANJARO) with either pygame 2.1.2 or pygame 2.1.3dev8
<hr>

# # #  **[francis-clairicia](https://github.com/francis-clairicia)* commented at 2022-11-02 17:41:05*

Okay so it can be a GNOME issue.
Even after updating my system and restarting the computer, clearing my virtual env and reinstalling it, I always have this problem.
<hr>

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-11-02 17:42:22*

Can you record a video demonstrating the problem?
<hr>

# # #  **[francis-clairicia](https://github.com/francis-clairicia)* commented at 2022-11-02 17:48:23*

Yes I'll do that.

I didn't think to test with the other 2.1.3 pre-releases and there is no issue with 2.1.3.dev6 (SDL 2.0.20).
<hr>

# # #  **[francis-clairicia](https://github.com/francis-clairicia)* commented at 2022-11-02 18:21:27*

Here is a screencast of the behaviour : https://drive.google.com/file/d/1MtcZYtJv7aKrw8donikvdLLYFLLhbEUE/view?usp=sharing
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-11-05 17:32:21*

The only change I can see that might affect this is a change in the version of SDL in the linux wheels between dev6 and dev8.

What is the console output for you with dev6? This thing:

```
pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.10.7)
```

<hr>

# # #  **[francis-clairicia](https://github.com/francis-clairicia)* commented at 2022-11-05 18:51:06*

pygame 2.1.3.dev6 (SDL 2.0.20, Python 3.10.7)
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-11-06 11:01:14*

I can reproduce this under Ubuntu 22.04 (also gnome). It most likely is due to the SDL 2.0.20 -> 2.0.22 bump

**Comment by MyreMylar** [comment]
Probably should retest this to see if it is still happening.

**Comment by ankith26** [comment]
At some point I could reproduce this issue, and now I cannot. I'm now on Ubuntu 23.10 (still with GNOME)
`pygame-ce 2.3.2 (SDL 2.26.5, Python 3.11.6)`

I'm closing this issue, though feel free to re-open if this issue persists

**Comment by Hato1** [comment]
I'm experiencing this issue on Linux Mint 22.2 Cinnamon (Ubuntu 24.04).
`pygame-ce 2.5.5 (SDL 2.32.6, Python 3.12.9)`.

**Comment by oddbookworm** [comment]
> I'm experiencing this issue on Linux Mint 22.2 Cinnamon (Ubuntu 24.04).
> `pygame-ce 2.5.5 (SDL 2.32.6, Python 3.12.9)`.

Can you share the output from `pygame.print_debug_info()` (after calling `pygame.init()`

**Comment by Hato1** [comment]
Sure, here you go
```
Platform:		Linux-6.14.0-33-generic-x86_64-with-glibc2.39
System:			Linux
System Version:		#33~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 19 17:02:30 UTC 2
Processor:		x86_64	SSE2: Yes	AVX2: Yes	NEON: No
Architecture:		Bits: 64bit	Linkage: ELF

Python:			CPython 3.12.9 (main, Mar 17 2025, 21:01:58) [Clang 20.1.0 ]
GIL Enabled:		True
pygame version:		2.5.5
SDL versions:		Linked: 2.32.6	Compiled: 2.32.6
SDL Mixer versions:	Linked: 2.8.1	Compiled: 2.8.1
SDL Font versions:	Linked: 2.24.0	Compiled: 2.24.0
SDL Image versions:	Linked: 2.8.8	Compiled: 2.8.8
Freetype versions:	Linked: 2.13.3	Compiled: 2.13.3

Display Driver:		x11 ( xwayland == False )
Mixer Driver:		pulseaudio
```

**Comment by Hato1** [comment]
A workaround in the meantime, starting the display with pygame.HIDDEN and then making a visible display prevents the flicker (or at least makes it much more subtle).

```python
pg.display.set_mode(SCREEN_SIZE, pg.HIDDEN)
pg.display.set_mode(SCREEN_SIZE)
```

**Comment by oddbookworm** [comment]
@Hato1 can you try on the brand-new 2.5.6 release?

**Comment by Hato1** [comment]
> [@Hato1](https://github.com/Hato1) can you try on the brand-new 2.5.6 release?

No change I'm afraid.
