### ISSUE TITLE
pygame.transform.invert() (3578)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1763]
#  **Issue &numero;3578 opened by *[novialriptide](https://github.com/novialriptide)* at 2022-11-20 07:51:18**

It just inverts the colors

# #  Example
<img src="https://user-images.githubusercontent.com/35881688/202891564-68bcd538-a690-4c85-a302-cf6a3f395922.jpg" width="400"><img src="https://user-images.githubusercontent.com/35881688/202891565-574965c4-84d0-4bf6-9c21-7ecc02efec58.png" width="400">

# #  Design
```python
def pygame.transform.invert(surface: pygame.Surface) -> pygame.Surface: ...
```<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-11-20 08:05:41*

I haven't really thought this through yet but couldn't you use the subtract blend mode with your image against a white surface?
<hr>

# # #  **[novialriptide](https://github.com/novialriptide)* commented at 2022-11-20 08:38:21*

> I haven't really thought this through yet but couldn't you use the subtract blend mode with your image against a white surface?

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/35881688/202893023-e69b4d24-63cf-4113-8849-715b7aa589f2.png">
Yup, you're correct. Here's the tested code.

```python
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 800))
img = pygame.image.load("touhou.jpg")

while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
    
    screen.fill((255, 255, 255))
    screen.blit(img, (0, 0), special_flags=pygame.BLEND_RGBA_SUB)
    pygame.display.update()
```
<hr>

# # #  **[novialriptide](https://github.com/novialriptide)* commented at 2022-11-21 02:29:12*

Shall we move this further as a PR?
<hr>

# # #  **[Matiiss](https://github.com/Matiiss)* commented at 2022-11-21 21:36:39*

Would it be faster to transform a surface with this and then blit it to destination or to create a white surface the same size of image, then blit image with this flag on the white surface and then blit the resulting (initially white) surface to destination, or perhaps, it would be fastest to use some numpy array magic. I suppose this new feature would be more performant than the second option (special flag), but would it be faster than using arrays? If so and using this new feature would be most performant then +1 from my side. +1 either way because this seems far more convenient and not that it would harm anything (unless it's really the slowest way which I doubt).
<hr>

# # #  **[gresm](https://github.com/gresm)* commented at 2022-11-22 21:22:15*

``invert`` is kind of ambiguous: can be also understood as flipping an image. Maybe the better name would be: ``invert_colo``~~u~~``rs``?
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-11-24 06:36:07*

Should this be moved forward at all if it's already accessible as a blend flag thing?
<hr>

# # #  **[MightyJosip](https://github.com/MightyJosip)* commented at 2022-11-24 09:27:22*

I would assume it could be added for performance reasons. But I don't see that function being used much
<hr>

# # #  **[novialriptide](https://github.com/novialriptide)* commented at 2022-11-24 16:20:17*

> I would assume it could be added for performance reasons. But I don't see that function being used much

I think people would use it for some glitchy effects or jumpscares in horror games. ¯\_(ツ)_/¯
<hr>

# # #  **[ExtraMobs](https://github.com/ExtraMobs)* commented at 2022-11-25 19:31:12*

I see a problem with RGBA images, but I solved it with surface masking and using RGB_SUB to avoid inverted alpha:

```python
import pygame


def invert_color(surface):
    s = surface.copy()
    mask = pygame.mask.from_surface(surface)
    s.blit(mask.to_surface(unsetcolor=(0, 0, 0, 0)), (0, 0))
    s.blit(surface, (0, 0), special_flags=pygame.BLEND_RGB_SUB)
    return s


screen = pygame.display.set_mode((600, 600))
img = pygame.image.load("test.png")

img = invert_color(img)


while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            raise SystemExit(0)

    screen.fill((255, 0, 0))
    screen.blit(img, (0, 0))
    pygame.display.update()

```

Original image:
![test](https://user-images.githubusercontent.com/50765958/204045189-ca9a0b3c-dbe2-4ae6-a295-ad1d888a1618.png)

result (red background):
![image](https://user-images.githubusercontent.com/50765958/204045155-d15ac0a4-44b0-4abe-a017-6946b4e355db.png)

~But, it works with images with alpha 0 or 255, don't enter these values.~

I found a way to resolve the alpha pixels:

```python
import pygame


def invert_color(surface):
    s = surface.convert_alpha()
    
    pixel = pygame.surfarray.pixels2d(s)
    pixel ^= 2 ** 24 - 1
    del pixel
    return s

clock = pygame.time.Clock()

screen = pygame.display.set_mode((600, 600))
img = pygame.image.load("test.png")

img = invert_color(img)


screen.blit(img, (0, 0))

while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            raise SystemExit(0)

    clock.tick(30)

    pygame.display.update()
```

Image:
![test](https://user-images.githubusercontent.com/50765958/204163557-9f11fcd5-be46-4a2b-a1cf-646ca85f78e5.png)

result:
![image](https://user-images.githubusercontent.com/50765958/204163566-65ac2713-6637-43c2-8752-e5d5476c535c.png)

**Comment by Starbuck5** [comment]
Fixed in #1911
