### ISSUE TITLE
Fix docs build (3646)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1791]
# **Issue &numero;3646 opened by *[Starbuck5](https://github.com/Starbuck5)* at 2022-12-30 05:30:36**

The CI is now failing on every commit, because it tries to build the docs with the latest Sphinx release. Sphinx just released 6.0.

Firstly

- [ ] Updated CI to pip install something Sphinx 4.x explicitly

- [ ] Update docs/README to say we're on Sphinx 4

I believe we are on Sphinx 4, see https://github.com/pygame/pygame/pull/2666

Eventually

- [ ] Update to Sphinx 5 and verify everything still looks okay

- [x] Removed this deprecated thing that's failing in 6

- [ ] Update to Sphinx 6 and verify everything still looks okay

<hr>

# Comments

**Comment by Starbuck5** [comment]
This has been resolved in the past.
