### ISSUE TITLE
Port SDL_mixer metadata functionality (3650)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1792]
#  **Issue &numero;3650 opened by *[Starbuck5](https://github.com/Starbuck5)* at 2023-01-01 07:59:33**

SDL_mixer 2.6 introduces some new metadata getter features for music.

See:
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicAlbumTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicArtistTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicCopyrightTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicTitle || https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicTitleTag

I believe we're on SDL_mixer 2.6 on our platforms, so this functionality could be cool to see. Imagine writing a music player and getting this sort of metadata from the actual files, rather than having to store them someplace else.

These could be ported as individual functions, or maybe they be one ~`get_metadata`  function.<hr>

#  Comments

# # #  **[Matiiss](https://github.com/Matiiss)* commented at 2023-01-01 08:04:00*

I'll do this

**Comment by Starbuck5** [comment]
Fixed in #8
