### ISSUE TITLE
Replace `SDL_GetTicks` with `SDL_GetTicks64` in `time.c` (3658)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1795]
#  **Issue &numero;3658 opened by *[Matiiss](https://github.com/Matiiss)* at 2023-01-06 04:50:36**

This is to solve the issue of 32-bit overflow every ~49 days (surely an edge case but still) as described here: https://wiki.libsdl.org/SDL2/SDL_GetTicks
It is also recommended there that `SDL_GetTicks64` should be used due to this reason.

I suppose this wouldn't break backwards compatibility since the public API wouldn't change, I don't know what are the current supported SDL versions though since `SDL_GetTicks64` was introduced in SDL version `2.0.18.`<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2023-01-06 06:05:39*

> I don't know what are the current supported SDL versions

It’s in the README, 2.0.8 and above as of a few days ago.
<hr>

# # #  **[Matiiss](https://github.com/Matiiss)* commented at 2023-01-06 06:15:41*

I guess this can be added to 3.0.0 milestone then... Should it be kept open? By the time supported versions get up to 2.0.18., this may be buried underneath a ton of other issues.

What about adding this alongside compile time conditionals with macros that check if SDL version is at least 2.0.18.?
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2023-01-06 06:55:19*

> What about adding this alongside compile time conditionals with macros that check if SDL version is at least 2.0.18.?

Sure.

**Comment by Starbuck5** [comment]
Fixed in #1873
