### ISSUE TITLE
pygame.transform.blur (3659)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1796]
# **Issue &numero;3659 opened by *[ScriptLineStudios](https://github.com/ScriptLineStudios)* at 2023-01-07 13:22:11**

```python

pygame.transform.blur(surface: pygame.Surface, kernel_size: int) -> pygame.Surface

```

pretty self explanatory allows you to blur an image, passing in an (optional?) kernel size for the blur<hr>

# Comments

**Comment by Starbuck5** [comment]
Fixed in #1836
