### ISSUE TITLE
pygame.mixer (corrupted size vs. prev_size while consolidating) (3692)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1818]
#  **Issue &numero;3692 opened by *[Red-exe-Engineer](https://github.com/Red-exe-Engineer)* at 2023-02-01 05:33:50**

I don't know, but Google says C stuff so...

Happens at random when using this is a class, I don't know if it's because I'm using threading or not, needs more testing.
```py3
def _play(self, file: str):
    while mixer.music.get_busy():
        time.sleep(0.2)

    mixer.music.load(file)
    mixer.music.play()

    while mixer.music.get_busy():
        time.sleep(0.2)

def play(self, file: str):
    Thread(target=self._play, args=(file,)).start()
```

My system has weird audio bugs too, if I play more than one video at once media stops player, also audio just sometimes glitches.

Ask if you have a question, I'll try to check this every once in awhile<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2023-02-01 06:05:52*

Hello.
This post doesn't have much info in it. Our [bug report template](https://github.com/pygame/pygame/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) shows the kind of info we want.

`corrupted size vs. prev_size while consolidating` ? is that an error message?

When does this happen? Presumably you need to call the play function multiple times to get this error message?

You can't have multiple mixer.music tracks playing at once, threads will not get around that.

<hr>

# # #  **[Red-exe-Engineer](https://github.com/Red-exe-Engineer)* commented at 2023-02-01 22:54:08*

> You can't have multiple mixer.music tracks playing at once, threads will not get around that.

Thanks, but I'm not trying to play multiple files at once (hence the `while mixer.music.get_busy()`).

As for when it occurs I don't know, playing multiple media (audio/video at once) seems to cause problems for me so maybe that's the reasoning?.

**Comment by zoldalma999** [comment]
Closing as there is not enough info to do anything here, and we will probably not be able to reach OP.
