### ISSUE TITLE
pygame.font (3693)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1819]
#  **Issue &numero;3693 opened by *[AAKk89](https://github.com/AAKk89)* at 2023-02-01 19:46:35**

Dear friends...
after searching the web, I have found tens of issues of people trying to import the pygame.font module on a mac device.
may I ask you if there is another pygame tool to render the text into the screen? or even if we can use a 3rd party to render the text into pygame screen... 
I struggled to find a way to do that... but i didn't find any.<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2023-02-01 20:05:00*

`pygame.freetype.font` ?

The mac issue is being investigated in development, and there is at least one potential fix PR - from what I understand it only occurred on some macs so it has been difficult to pin down.

**Comment by Starbuck5** [comment]
Fixed in #1922
