### ISSUE TITLE
Issue with running pygame2.0 in Sugar desktop (3696)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1820]
#  **Issue &numero;3696 opened by *[chimosky](https://github.com/chimosky)* at 2023-02-02 17:15:40**

Hi!

My name is Ibiam and I'm a maintainer at Sugar Labs, maintaining the [sugar desktop](https://www.sugarlabs.org/) and it's activities, we have a lot of activities that use pygame and we have a [sugargame module](https://github.com/sugarlabs/sugargame) that helps activities that use pygame run in sugar.

I'm trying to get it to support pygame2.0 so activities that use pygame can run properly in sugar but I've run into some issues, basically the sugargame module uses a `Gtk.Socket` and embeds the pygame display into the socket, `SDL_WINDOWID` is set before any pygame modules are initialized but when the test activity starts, there's just a black screen.

I'm having a hard time figuring out what the problem is as the test game works fine outside sugar and the `SDL_WINDOWID` is set to the id of the Gtk Socket and this worked fine in pygame 1.9.

I need help with figuring out what's wrong.<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2023-02-02 19:52:33*

Hello!

We have actually been discussing this again recently in a pull request. 

SDL, the library pygame wraps, dropped support for `SDL_WINDOWID` when they switched from SDL 1 to SDL 2. Once we upgraded pygame to use SDL2, the support for this environment variable also when away in pygame.

However, there is a new - probably more intuitive way - to embed pygame displays in other windows in SDL 2 and there is currently an open [pull request here](https://github.com/pygame/pygame/pull/3685) for pygame that implements this feature.

Essentially instead of doing:

```
import os
os.environ['SDL_WINDOWID'] = window_id
display_surf = pygame.display.set_mode((800, 600))
```

You would do:
```
display_surf = pygame.display.set_mode((800, 600), hwnd=window_id)
```

I believe. Though I haven't tested the whole process extensively myself yet. 

If you are experienced with building libraries from scratch you could perhaps try this pull request and the new methodology and see if it works in your use case?

<hr>

# # #  **[chimosky](https://github.com/chimosky)* commented at 2023-02-03 23:06:44*

> If you are experienced with building libraries from scratch you could perhaps try this pull request and the new methodology and see if it works in your use case?

I'll do that, thanks!
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2023-02-07 04:25:15*

The SDL_WINDOWID API being broken is considered a bug, and will be fixed.

I'm not sure the new API referenced that PR will be included in a release of pygame. It isn't merged yet either.

**Comment by Starbuck5** [comment]
SDL_WINDOWID has been readded since this issue was open, even though it doesn't fully work (problems with events outside of our control).

So I think we can consider this completed.
