### ISSUE TITLE
A way to detect whether Pygame-CE is being used.

### ISSUE THREAD

**Issue by Sjmarf** [pygame-community/pygame-ce#1845]
This would be useful in cases where a CE-exclusive feature is used, but you want to fallback to an alternative if the user doesn't have Pygame CE installed. Or, it could be used to warn the user upon program startup that they aren't using the correct version of Pygame.

**Comment by MyreMylar** [comment]
Good point.

We will likely have to add a testable flag/method in the pygame module if the fork and the upstream continue with parallel development (i.e. there is a 2.1.4 of pygame and a 2.1.4 of pygame-ce with different featuresets). 

For now there is no real difference between the last development release of upstream pygame and the full 2.1.3 release of pygame-ce.

**Comment by Starbuck5** [comment]
I propose a `pygame.IS_CE` attribute.

One would test it with `getattr(pygame, "IS_CE", False)`

This could be implemented on `__init__.py` in src_py.
