### ISSUE TITLE
pygame.transform.solid_overlay()

### ISSUE THREAD

**Issue by novialriptide** [pygame-community/pygame-ce#1847]
The purpose of this function is to replace every single non transparent pixel with the inputted color.

![dasd](https://user-images.githubusercontent.com/35881688/218426641-5091f4a4-95cc-48e5-a9be-839c8cdee475.png)

**Comment by MyreMylar** [comment]
Here is how I would do this at the minute with blend modes:

```
import pygame


display_surf = pygame.display.set_mode((800, 600))
display_surf.fill((255, 255, 255))
test_overlay_surface = pygame.Surface((50, 50), pygame.SRCALPHA)
test_overlay_surface.fill((255, 0, 0, 0))

sprite = pygame.image.load("images/walt.png").convert_alpha()
test_overlay_surface = pygame.Surface(sprite.get_size(), pygame.SRCALPHA)
test_overlay_surface.fill((255, 255, 255, 0))
test_colour_surface = pygame.Surface(sprite.get_size(), pygame.SRCALPHA)
test_colour_surface.fill((0, 0, 0, 255))
sprite.blit(test_overlay_surface, (0, 0), special_flags=pygame.BLEND_RGBA_MAX)
sprite.blit(test_colour_surface, (0, 0), special_flags=pygame.BLEND_RGBA_MULT)

pygame.init()

clock = pygame.time.Clock()

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    display_surf.fill((255, 255, 255))
    display_surf.blit(sprite, (100, 100))

    pygame.display.flip()

    clock.tick(60)

```

It could be simpler to do for sure. Is overlay the name of the photoshop filter that creates this effect?

**Comment by Starbuck5** [comment]
Haven't thought through this much, but `silhouette` could be a good name?

Descriptive, maybe a bit hard to spell.

**Comment by novialriptide** [comment]
@MyreMylar I dunno if it's viable for the user to do it themselves as this function alone would be useful for creating shadows for people who aren't that versed with these blend modes.

> Is overlay the name of the photoshop filter that creates this effect?

Yup, I'd prefer using overlay since that's what photoshop uses.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/35881688/218652859-fddc6ba1-edf3-40e7-b98f-180f6f5fe5e1.png">

> `silhouette`

@Starbuck5 

naruto? :)

**Comment by itzpr3d4t0r** [comment]
I think this would be a nice addition, compacting many blits/blend modes into a single function call is super beginner friendly and that's the direction we should follow with pygame. Not to mention potential optimizations coming from C alone or SIMD stuff if applicable.

**Comment by gresm** [comment]
Maybe it would be better to add this functionality with ``Surface.fill()`` using ``mask=...`` argument?

**Comment by yunline** [comment]
> I dunno if it's viable for the user to do it themselves as this function alone would be useful for creating shadows for people who aren't that versed with these blend modes.

Maybe we can add `transform.shadow(surface, x, y, distance, color, blur_radius)` to create a shadow surface.

**Comment by Python-ZZY** [comment]
I think it's not very useful.But u can use mask to do this.It's easy.
For example:
```py
image_input = pg.image.load("example.png")
overlay_rgb = (0, 0, 0)
image_output = pg.mask.from_surface(image_input).to_surface(setcolor=overlay_rgb, unsetcolor=(0, 0, 0, 0))
```

**Comment by novialriptide** [comment]
> Maybe we can add `transform.shadow(surface, x, y, distance, color, blur_radius)` to create a shadow surface.

@yunline "Shadow" usually means black, I personally think `overlay` would be a better naming choice.
