### ISSUE TITLE
Drop CPython 3.6 support

### ISSUE THREAD

**Issue by itzpr3d4t0r** [pygame-community/pygame-ce#1850]
Python 3.6 is officially dead:
![image](https://user-images.githubusercontent.com/103119829/218437104-a8978162-ea42-44f7-8313-344cd0369f6a.png)
 
I propose we drop compatibility for 3.6. This would allow us to lower CI runtime and let us use stuff that 3.7+ only supports, such as FASTCALL (speaking of C API).

**Comment by MightyJosip** [comment]
Looking at some of the most used python libraries on PyPi (or documentation page if PyPi doesn't have Requires section)
| library | version supported |
|---------|-------------------|
| pandas  | 3.8               |
| numpy   | 3.8               | 
| keras   | 3.7               |
| tensorflow   | 3.7               |
| scipy  | 3.8              |
| pytorch  | 3.7             |
| flask  | 3.7             |
| opencv  | 3.6             |

**Comment by pmp-p** [comment]
i think opencv is abi3 3.7+
