### ISSUE TITLE
cpychecker python C extension static analyzer (171)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#186]
#  **Issue &numero;171 opened by *[illume](https://github.com/illume)* at 2013-08-09 07:51:45**

A tool which can detect memory leaks and ref count bugs in python C extensions.

- reference count bugs
- Error-handling checking
- errors in exception handling
- Format string checking
- Verification of PyMethodDef tables
- ... some other types of bugs.

# #  Docs, videos, and blog posts.

- cpychecker documentation https://gcc-python-plugin.readthedocs.io/en/latest/cpychecker.html
- gcc-python-plugin github https://github.com/davidmalcolm/gcc-python-plugin
- http://emptysqua.re/blog/analyzing-python-c-extensions-with-cpychecker/
- https://www.youtube.com/watch?v=bblvGKzZfFI
- https://pyvideo.org/pycon-us-2012/static-analysis-of-python-extension-modules-using.html

----------------------------------------
- old Bitbucket issue https://bitbucket.org/pygame/pygame/issue/171
<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2013-10-02 02:44:14*

*Original comment by* **Lenard Lindstrom (Bitbucket: [llindstrom](https://bitbucket.org/llindstrom), GitHub: [llindstrom](https://github.com/llindstrom))**:

----------------------------------------

Well, I built GCC Python Plugin for Python 2.7 and the CPyChecker demo works. I will try it on a Pygame build, but the output is likely to be large.

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2013-10-02 03:42:14*

*Original comment by* **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**:

----------------------------------------

I noticed this talk about CPyChecker too... http://www.youtube.com/watch?v=bblvGKzZfFI

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2013-10-02 03:52:12*

*Original comment by* **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**:

----------------------------------------

The text of that talk has some useful hints in there... https://github.com/davidmalcolm/PyCon-US-2013-Talk/blob/master/PyCon-US-2013-dmalcolm-StaticAnalysis.txt

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2013-10-02 19:16:51*

*Original comment by* **Lenard Lindstrom (Bitbucket: [llindstrom](https://bitbucket.org/llindstrom), GitHub: [llindstrom](https://github.com/llindstrom))**:

----------------------------------------

Well, I tried CPyChecker on a Pygame build, and commited changeset 6edd09029351 to correct the problems it found. But it stalled out on font.c, so only two modules were checked. Likely I will have to go through modules individually. Also, this was a Python 2.7 check. Python 3 should be done as well.

I would attach an example CPyChecker report, but they were clobbered when I performed full unit testing on the changeset. But there will be plenty of opportunities to come.

I found the youtube video informative. I subscribed to the mailing list.

<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-10-17 05:03:28*

From what I know, Static analyzer runs already on our appveyor windows builds, so this issue can probably be closed.

(if someone wants to add onto something here feel free to re-open the PR)

EDIT: Oh wait the appveyor ones probably run another static analyser and not this one. My bad, re-opening this issue
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-12-28 04:14:32*

I was playing around with this issue, and it seems like `cpychecker` is a rather dated tool, and is not super-well maintained. I used latest Ubuntu 21.10 which runs python 3.9, and ran into issues getting `cpychecker` setup. Maybe we should consider more modern alternatives?

**Comment by Starbuck5** [comment]
As Ankith said in 2021, the tool is quite dated, and that has not changed since. I found this email chain discussing its status: https://gcc.gnu.org/pipermail/gcc/2023-March/240996.html

I did a quick search to see if there were other static analyzers for Python C extensions and only found links to this.

With that in mind, let's lay this 10 year old issue to rest.
