### ISSUE TITLE
Shall .c files generated by cython be included in the .gitignore?

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#1862]
Shall .c files generated by cython be included in the .gitignore?
Auto-merged .c files may be unuseable and needs to be regenerated.

**Comment by Starbuck5** [comment]
Generating the cython at build time is not a simple thing to do well.

I tried to do this, https://github.com/pygame/pygame/pull/2916, but I gave up after encountering lots of errors.

We're hoping to migrate away from the cython code, so maybe that makes it easier to live with this less than ideal set up for now.

But yes, for now we need to be careful to merge cython PRs serially.

**Comment by zoldalma999** [comment]
Done by #2831
