### ISSUE TITLE
`Renderer.present()` works abnormally when using direct3d11

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#1868]
**Environment:**

- **Operating system** : Windows10 21H2
- **Python version** : 3.10.6
- **SDL version** : 2.0.22
- **PyGame version** : 2.1.4dev1
- **Relevant hardware** : Null

**Test code**

```python
import pygame
from pygame._sdl2 import video

print("Available renderer drivers:")
for n,i in enumerate(video.get_drivers()):
    print(n,'|',i)

# Output:
#
# Available renderer drivers:
# 0 | <RendererDriverInfo(name: direct3d, flags: 0x0e, num_texture_formats: 1, max_texture_width: 0, max_texture_height: 0)>  
# 1 | <RendererDriverInfo(name: direct3d11, flags: 0x0e, num_texture_formats: 6, max_texture_width: 0, max_texture_height: 0)>
# 2 | <RendererDriverInfo(name: opengl, flags: 0x0e, num_texture_formats: 4, max_texture_width: 0, max_texture_height: 0)>
# 3 | <RendererDriverInfo(name: opengles2, flags: 0x0e, num_texture_formats: 4, max_texture_width: 0, max_texture_height: 0)>
# 4 | <RendererDriverInfo(name: software, flags: 0x0d, num_texture_formats: 8, max_texture_width: 0, max_texture_height: 0)>

win=video.Window("sb")
r=video.Renderer(win,index=1) # Select the direct3d11 driver

r.draw_color=(255,255,255,255)
r.fill_rect((10,10,100,100))

while 1:
    r.present() # Only when Renderer.present() is called repeatedly, the bug will appear.
    pygame.event.get()
```

**Current behavior:**
![image](https://user-images.githubusercontent.com/31395137/218971430-f8a82415-00fa-4e6e-af10-6482efd75da7.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/31395137/218971249-0fd7cab0-8078-4923-8447-bd99202c89ff.png)

**Comment by PurityLake** [comment]
This isn't just a DirectX11 issue.

This is a direct quote from [SDL website](https://wiki.libsdl.org/SDL2/SDL_RenderPresent)

> The backbuffer should be considered invalidated after each present; do not assume that previous contents will exist between frames. You are strongly encouraged to call [SDL_RenderClear](https://wiki.libsdl.org/SDL2/SDL_RenderClear)() to initialize the backbuffer before starting each new frame's drawing, even if you plan to overwrite every pixel.

So to me this isn't an issue with our implementation and more a underlying library issue.
