### ISSUE TITLE
Remove draw_py module?

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#1883]
**Description**

In src_py, we have draw_py.py, a reimplementation of the draw module in python. This also comes up a lot in draw_test.py.

This file claims to be a work in progress, and incomplete. It hasn't received a real update (non linting) since 2020, and no in depth work since early 2019.

It seems like at this point we should just remove this bit of code. Is this helping us improve draw at all?

@MightyJosip opinions?

**Comment by MightyJosip** [comment]
I would agree it should be removed. It is not used in pygame.draw code. It should basically be in the examples folder (it was made for educational purposes) if we have it at all. Also like you have mentioned it hasn't been updated in a long time, meanwhile draw itself has been changed a lot in last 4 years, so draw_py code is outdated (not correctly displaying how does pygame.draw actually do stuff).

Having python implementation is good, I have them for the most things I have done, it is quick (in terms of development time, not performance ;) ), but in general this file is redundant

**Comment by MyreMylar** [comment]
Seems like a sensible idea to me.
