### ISSUE TITLE
Implementing swizzling RGBA values for `pygame.Color`

### ISSUE THREAD

**Issue by avaxar** [pygame-community/pygame-ce#1919]
Taking pygame/pygame#3705 here...

# Description

 There should be a way to construct a new `pygame.Color` from joining multiple color channels of a `pygame.Color` together in respect to RGB(A), simply per a single property access, otherwise known as swizzling. This is alike to GLSL's [swizzling](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling), where one could construct a vector from another by joining the values of multiple axes in a single identifier (i.e `my_vec.xyz` instead of `vec3(my_vec.x, my_vec.y, my_vec.z)`).

# Example Concept

```py
>>> color = pygame.Color(1, 2, 3, 4)
>>> color.rgb  # Alpha would still be specified optionally; `255` by default.
(1, 2, 3, 255)
>>> color.bgr
(3, 2, 1, 255)
>>> color.rrr
(1, 1, 1, 255)
>>> color.arar
(4, 1, 4, 1)
>>> color.brag
(3, 1, 4, 2)
>>> color.grab
(2, 1, 4, 3)
```

# Notes

 Though, yes, I am aware how many attributes would need to be implemented in C for every single case. Assuming that we'd be supporting combining 3 and 4 axes, that means 4^3 + 4^4 = 320 cases that would need to be implemented. It could be shrunk down to 4^4 = 256 cases if we use default args for the alpha channel for the other 4^3 cases. And we could shrink it even more into one packed function if we hijack `__getattr__`.

**Comment by Starbuck5** [comment]
Remember that pygame Vectors have this functionality, and it would be good to have an implementation to look at and good to be consistent with the implementations.

**Comment by avaxar** [comment]
Ah right, I didn't know `pygame.Vector(2/3)` allowed swizzling.

**Comment by ScriptLineStudios** [comment]
I think ill try working on this

**Comment by oddbookworm** [comment]
@ScriptLineStudios I know @avaxar was trying to work on this, so you might want to get with them so that you don't step on each others' toes
