### ISSUE TITLE
Documentation rework

### ISSUE THREAD

**Issue by novialriptide** [pygame-community/pygame-ce#1924]
There are a couple of things that need to be addressed...
 - [ ] We should probably use a service like [weblate](https://weblate.org/en/) to host our translations for Korean and Spanish
 - [ ] There is currently no possible way to access the tutorial "Red or Black" in English other than using a direct URL
 - [x] `docs/tut` needs to be renamed to `docs/tutorial`
 - [ ] Utilize [Google's naming conventions](https://developers.google.com/style/filenames) for our `.rst` files (previously mentioned in #1918)
 - [x] There are duplicate asset files for the English and Korean variants for the tutorial "Red or Black" / 「빨간블록 검은블록」
 - [ ] Bring up a discussion on deleting the tutorials entirely? I don't think anyone actually uses them...
 - [x] Separate the English, Spanish, and Korean files

**Comment by bilhox** [comment]
Closing this issue, referenced in #3132
