### ISSUE TITLE
Sometimes Actions fail because of timeout when installing dependiences.

### ISSUE THREAD

**Issue by gresm** [pygame-community/pygame-ce#1931]
Sometimes Actions fail when installing dependencies with ``apt`` because of timeout. This happens for ``cppcheck Static Analysis`` workflow as seen [here](https://github.com/pygame-community/pygame-ce/actions/workflows/cppcheck.yml). This usualy happens when downloading one of the gcc dependencies. Examples:

[Example 1](https://github.com/pygame-community/pygame-ce/actions/runs/4250934566/jobs/7392650205#step:3:47)
>  Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 libstdc++6 amd64 11.1.0-1ubuntu1~20.04
  Connection timed out [IP: 185.125.190.52 80]

[Example 2](https://github.com/pygame-community/pygame-ce/actions/runs/4250194784/jobs/7391065703#step:3:54)
> Err:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 liblsan0 amd64 11.1.0-1ubuntu1~20.04
  Connection timed out [IP: 185.125.190.52 80]

[Example 3](https://github.com/pygame-community/pygame-ce/actions/runs/4250122769/jobs/7390918695#step:3:47)
> Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 libstdc++6 amd64 11.1.0-1ubuntu1~20.04
  Connection timed out [IP: 185.125.190.52 80]

[Example 4](https://github.com/pygame-community/pygame-ce/actions/runs/4249570583/jobs/7389846826#step:3:55)
> Err:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 liblsan0 amd64 11.1.0-1ubuntu1~20.04
  Connection timed out [IP: 185.125.190.52 80]

[Example 5](https://github.com/pygame-community/pygame-ce/actions/runs/4249564251/jobs/7389834708#step:3:57)
> Err:19 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 libtsan0 amd64 11.1.0-1ubuntu1~20.04
  Connection timed out [IP: 185.125.190.52 80]

Maybe, when downloading timed out, try running it again?

**Comment by zoldalma999** [comment]
I think I'll close this.

While this still happens sometimes, I don't think it is that often, plus we can rerun it easily if it does.
