### ISSUE TITLE
Add a version indicator to the front page of docs.

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#1937]
Example:
![image](https://user-images.githubusercontent.com/31395137/221239188-1e92ce27-08ce-408a-a175-f7e0c476d00d.png)

**Comment by oddbookworm** [comment]
There actually is one if you scroll all the way to the bottom and look at the bottom left corner

**Comment by yunline** [comment]
> There actually is one if you scroll all the way to the bottom and look at the bottom left corner

It's too small and not easy to be found, especially for people who have just started reading this document
