### ISSUE TITLE
Support SDL_WINDOWID

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#1943]
Original issue: https://github.com/pygame/pygame/issues/1574

**Comment by yunline** [comment]
Relevant PR: #1837

**Comment by Starbuck5** [comment]
That is relevant, but just to be clear, I don't see that PR closing this issue.

Since upstream pygame merged a back compat fix for the old SDL_WINDOWID environment variable, we should as well, to minimize our compatibility differences.
