### ISSUE TITLE
Operations between pygame.Vector2 and pygame.Rect

### ISSUE THREAD

**Issue by ScriptLineStudios** [pygame-community/pygame-ce#1949]
The ability to perform operations between a Rect and Vector2 together as follows:
```python
>>> pygame.Rect(10, 10, 5, 5) + pygame.Vector2(2, 2)
<rect(12, 12, 5, 5)>
```

**Comment by Matiiss** [comment]
Couldn't this just be simplified to support a sequence?

**Comment by novialriptide** [comment]
Not sure about this since it's a bit vague whether or not you're modifying the size instead of the position.

**Comment by robertpfeiffer** [comment]
The "easy" way to do this is to have properties like `rect.center_vec` and `rect.topleft_vec`, so you can say `rect.center_vec += Vector2(2, 2)`

**Comment by Matiiss** [comment]
@robertpfeiffer you can already do that with current 2-tuple getters/setters apparently
Some test code to play with:
```py
import pygame


WIDTH, HEIGHT = 640, 360
FPS = 60

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
clock = pygame.time.Clock()

rect = pygame.Rect(0, 0, 10, 10)
rect.center = pygame.Vector2(WIDTH, HEIGHT) / 2

running = True
while running:
    clock.tick(FPS)
    screen.fill("black")

    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            running = False

    keys = pygame.key.get_pressed()
    if keys[pygame.K_d]:
        rect.center += pygame.Vector2(5, 0)
    if keys[pygame.K_a]:
        rect.center += pygame.Vector2(-5, 0)
    if keys[pygame.K_s]:
        rect.center += pygame.Vector2(0, 5)
    if keys[pygame.K_w]:
        rect.center += pygame.Vector2(0, -5)

    pygame.draw.rect(screen, "red", rect)

    pygame.display.flip()
```
I don't know, this might as well invalidate the issue altogether combined with how the exact suggestion might be ambiguous as stated by @oddbookworm

**Comment by novialriptide** [comment]
I think this doesn't need to be implemented as the user can do this instead.
```python
a = pygame.Rect(3, 3, 3, 3)
a.topleft += pygame.Vector2(6, 6)
```

I'll be closing this issue now.
