### ISSUE TITLE
Support setting text direction

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#1952]
Port https://wiki.libsdl.org/SDL2_ttf/TTF_SetFontDirection

Languages like Arabic (right to left) need this to render properly. (Along with a call to Font.set_script as well)

Would be cool to have in the 2.1.4 update as part of a "text enhancements" story: multiline text, Font.set_script for internationalization... Font.set_direction for internalization as well.

See https://github.com/pygame/pygame/pull/3330 for inspiration.

**Comment by pmp-p** [comment]
What about adding free fonts with major scripts support ?
