### ISSUE TITLE
Add get_name() method to the different Font classes 

### ISSUE THREAD

**Issue by Martinus2004** [pygame-community/pygame-ce#1969]
**Description**

ReaMart proposed this in the discord: 

>  I made a little program that lets you browse the list of sysfonts. I have a list of the Font objects, which I loop trough and blit to the screen with some text.I figured it would be a nice feature if the text that was rendered would include the name of the font, so I tried doing something like font.get_name, but there was no such thing so yeah.

Not only for sysfont this would be handy in my opinion. Let's say a user wanted to get the name of a certain font in some other file or deep down in the code. It would be handy to get that name using the method rather than having to look it up yourself. Also if you have a list of Font objects, this would come in handy (like ReaMart had).

**Comment by MyreMylar** [comment]
I agree that this would be nice. The `freetype` submodule implements something similar with the `.name` attribute for it's `Font` class. However, that is a read only attribute which I know @Starbuck5 doesn't like.
