### ISSUE TITLE
Print a warning if the font is not found.

### ISSUE THREAD

**Issue by AndreyVarvar** [pygame-community/pygame-ce#1970]
Currently, if you type a non-existing font on your machine into the `pygame.font.SysFont()` function, the pygame automatically swaps it to a default font with no warning, and the user has to orient on the font itself to find that he misspelled it. My suggestion is to print a warning, if the font typed in is non-existing. Something like `Warning: your font was not found, so it got replaced with a default font.` should be fine.

**Comment by Sjmarf** [comment]
I think I'll try to implement this. I assume `logging.warning` is the proper way to give warnings to the user?

**Comment by Sjmarf** [comment]
And what should the error message say? `The system font '{name}' couldn't be found. Using the default font instead.` could work?

**Comment by AndreyVarvar** [comment]
Yes, I think this is good.

**Comment by Sjmarf** [comment]
#1973
