### ISSUE TITLE
Incorrect version check in font.c

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#1987]
In `font_set_direction`

```c
/*  There is a bug in SDL2 up to 2.26.3 (the current release version as of
   writing this) This bug flips the top-to-bottom and bottom-to-top rendering.
   So, this is a compat patch for that behavior
 */
#if SDL_VERSIONNUM(SDL_TTF_MAJOR_VERSION, SDL_TTF_MINOR_VERSION, \
                   SDL_TTF_PATCHLEVEL) <= SDL_VERSIONNUM(2, 26, 3)
```

This is not a bug in SDL, it's a bug in SDL_ttf, and therefore the check should be based on SDL_ttf versions. Probably just check if it's below 2.22.0 (the next minor SDL_ttf version).

This is an oversight I didn't spot in https://github.com/pygame-community/pygame-ce/pull/1956, a recent PR.

**Comment by oddbookworm** [comment]
I think [simplyrohan](https://github.com/simplyrohan) wants to handle this one
