### ISSUE TITLE
Outdated copyright info

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2029]
https://github.com/pygame-community/pygame-ce/blob/545b99a22009eecc453efb75125a212d43a4efa4/src_c/font.c#L1-L4

**Comment by Starbuck5** [comment]
It's not outdated, it's historical. The fact that it is 2023 doesn't minimize the fact that Pete Shinners had copyright in 2000 and 2001.

Personally I don't see any need to add a more current copyright notice.
