### ISSUE TITLE
Examples: use `import pygame` instead of `import pygame as pg`

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2033]
This is one of the largest questions of our time.

What is the "preferred" way of importing pygame, what should we use in our example files?

Status quo: `import pygame as pg`
My preferred: `import pygame`

React with rocket for `import pygame as pg`, react with eyes for `import pygame`.

**Comment by dr0id** [comment]
I think readability is higher using `pygame` but is longer to type. If the examples are aimed for beginners then `import pygame as pg` may not be as clear.

**Comment by Starbuck5** [comment]
I'm closing the poll, `import pygame` it is.

If someone would like to tackle this, change the programs in examples/ to use `import pygame` instead of `import pygame as pg`

**Comment by Starbuck5** [comment]
Before closing this issue, the cursors_module_example referenced by the docs still needs to be updated. Also, the chimp tutorial (English and Spanish) need to be updated with the new chimp example code.

**Comment by that1guy232** [comment]
#2191
