### ISSUE TITLE
Rectf() -- A rect calculated using float numbers

### ISSUE THREAD

**Issue by Python-ZZY** [pygame-community/pygame-ce#2035]
Sometimes counting pixels with integers is not accurate enough.  The speed of a game character can only be set to an integer like 1 or 2, not a floating-point number like 0.1.  A pixel is a int, but it is necessary to calculate a floating point number in order for a character to move one pixel after 10 refreshes.
This may affect the size of the Pygame library.  But if not design a class like Rectf, sometimes you need to add a vector which supported float to represent the position of the game character, which is very troublesome.

**Comment by Starbuck5** [comment]
https://github.com/pygame-community/pygame-ce/pull/1944 :)

**Comment by Python-ZZY** [comment]
> #1944 :)

errr.... I dont know how to remove my issue
