### ISSUE TITLE
Error while installing pygame using pip on Raspbian

### ISSUE THREAD

**Issue by KentoNanami** [pygame-community/pygame-ce#2052]
- **Operating system** Raspbian
- **Python version** 3.9.2
- **PyGame version** 2.1.3
- **Pip version** 20.3.4
- **Relevant hardware** Raspberry Pi

**Current behavior:**
I'm getting an error while installing pygame-ce using pip

**Error Output**
$ pip install pygame-ce
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pygame-ce
  Using cached pygame-ce-2.1.4.tar.gz (12.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dy5den8j
         cwd: /tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/setup.py", line 397, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/buildconfig/config.py", line 231, in main
        deps = CFG.main(**kwds, auto_config=auto)
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/buildconfig/config_unix.py", line 218, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_412e9b2607054043aff6e2851dddc185/buildconfig/config_unix.py", line 43, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    Hunting dependencies...
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://github.com/pygame-community/pygame-ce
    ---
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/22/93/9e7640f46c46702641bfecd9ce0cbfb7d7366d7b638b77630006d273a45a/pygame-ce-2.1.4.tar.gz#sha256=17244d4ef049e053bbd14e801f1a4c2ec0a65c069a3cf6793b66c622e15077bc (from https://pypi.org/simple/pygame-ce/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-ce-2.1.3.tar.gz (12.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sdvb66oj
         cwd: /tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/setup.py", line 398, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/buildconfig/config.py", line 231, in main
        deps = CFG.main(**kwds, auto_config=auto)
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/buildconfig/config_unix.py", line 218, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "/tmp/pip-install-kzzvsfn3/pygame-ce_3be925e737574b77b3e265ce58241abd/buildconfig/config_unix.py", line 43, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    Hunting dependencies...
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://github.com/pygame-community/pygame-ce
    ---
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1f/ba/8a95430f3b70ed9cb35a9702e3bac5f93c797c62c0f616f233462c13ef47/pygame-ce-2.1.3.tar.gz#sha256=67e03005b5c1c0dc3f1c18ea390a8ab3ed1871b79503ac4a04ad952b9e0d94fd (from https://pypi.org/simple/pygame-ce/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pygame-ce
ERROR: No matching distribution found for pygame-ce

**Comment by Starbuck5** [comment]
Looks like we don't have a prebuilt version of pygame-ce for your hardware. What model of raspberry pi do you have?

I'm confident your issue will be resolved if you can build from source-- our build from source guide for your system: https://github.com/pygame-community/pygame-ce/wiki/Compiling-on-Linux#debian-based-distros-like-ubuntu-and-raspberry-pi-os

**Comment by KentoNanami** [comment]
It's a raspberry pi 4 but I've just installed pygame-ce from source and the missing dependencies manually, now it works perfectly.
Thanks for your fast answer !

**Comment by KentoNanami** [comment]
Problem solved !

**Comment by Starbuck5** [comment]
Might as well update to the latest version now-- 2.2.0 just released (after you opened your issue) 😄

Glad that worked!
