### ISSUE TITLE
add get_frect as a method to surfaces

### ISSUE THREAD

**Issue by clear-code-projects** [pygame-community/pygame-ce#2066]
Since Pygame now has Rects as well as FRects it seems like a good idea to add a get_frect method. This would also create more consistency.

**Comment by Starbuck5** [comment]
This could be a good first C PR for someone, or good practice for a contributor who's learning their way around the C code.

- See the compiling guides in our wiki: https://github.com/pygame-community/pygame-ce/wiki
- Get pygame compiling on your system
- Copy all the `surf_get_rect` stuff but have it make an FRect instead (`pgFRect_New4`)
- Add docs in docs/reST/ref/surface.rst
- Add types in buildconfig/stubs/surface.pyi
- Add tests in test/surface.py (see whatever get_rect has)
