### ISSUE TITLE
Memory leak? (_sdl2.video.Window)

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2068]
**SDL: 2.0.22**
**pygame 2.3.0 dev1**
**python3.10.6**
**Windows10**
**Test Code:**
```python
from pygame._sdl2 import video
while 1:
    video.Window().destroy()
```
**Start**
![image](https://user-images.githubusercontent.com/31395137/228237765-92ff90e8-2f7b-49e2-9704-241d1be12f94.png)
**2 minutes later**
![image](https://user-images.githubusercontent.com/31395137/228238410-ba90aea5-bb52-4412-b761-0b9c3ce6c781.png)

It seems that memory usage is increasing, is that a memory leak?

**Comment by Starbuck5** [comment]
That would be a very slow memory leak. When I found a memory leak in one of the object repr PRs it went up to 600mb in like 30 seconds.

So perhaps not a memory leak and just some variation.
