### ISSUE TITLE
Deprecate `image.tostring`, `image.fromstring`

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2085]
It's been a while since we introduced `tobytes` and `frombytes` as the better named equivalents of these functions, and I've noticed people in the wild actually using the new names, so it's probably time to deprecate the old ones:

- [ ] Make functions generate a deprecation warning when called
- [ ] Mark functions deprecated in the docs

**Comment by SSS-Says-Snek** [comment]
I'll be working on this issue
