### ISSUE TITLE
Creating `pygame.Color` object from HSLA.

### ISSUE THREAD

**Issue by Sjmarf** [pygame-community/pygame-ce#2121]
Currently, to create a `pygame.Color` for a HSLA value, you have to do this:

```py
import pygame
col = pygame.Color("black")
col.hsla = (60, 100, 50, 100)
```

It would be nice if there was a cleaner way to do this. Maybe `from_hsva` / `from_hsla` class methods?

Edit: `cmy` and `i1i2i3` could also have this functionality, as Matt pointed out

**Comment by Starbuck5** [comment]
Another option is adding setters for chaining purposes. (So the setters also return the object they're modifying)

`color = pygame.Color(0.).set_hsva(1, 1, 1, 1)`
