### ISSUE TITLE
`abs` support for getting vector length/magnitude

### ISSUE THREAD

**Issue by Matiiss** [pygame-community/pygame-ce#2153]
Simple idea, just like in math `|v|` symbolizes a vector's magnitude, in pygame `abs(v)` could also return the magnitude of the vector. Essentially that would be equivalent to `v.length()` or `v.magnitude()` but shorter and more mathy (and might as well really).

I would implement it if this gets accepted.

**Comment by gresm** [comment]
People use ``|v|`` with different meaning, there's even a notation ``||v||`` for length of a vector. ``|v|`` could also mean a vector with every value absolute. (Based on [this](https://math.stackexchange.com/a/1346795/1145683).)

**Comment by Matiiss** [comment]
@JiffyRob  `abs(v.elementwise())` already exists and returns a vector with all components being absolute values of whatever they were previously

**Comment by Matiiss** [comment]
Won't get implemented now as it seems unnecessary and just adds another method on top of the two existing ones for getting the length of a vector, besides it's ambiguous.
