### ISSUE TITLE
Loading MP3 music from file like object fails on Linux

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2154]
Discovered this while I was working on #2152.

Apparently `test_load_object` in mixer_music_test.py will fail on Linux if it gets an mp3 file like object. (Originally `house_lo.mp3`)
```
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/pygame/tests/mixer_music_test.py", line 70, in test_load_object
    pygame.mixer.music.load(musf)
pygame.error: ModPlug_Load failed
```

People have seen this out in the world:
https://stackoverflow.com/questions/65614352/pygame-error-modplug-load-failed-when-trying-to-play-sound-from-bytes

I would like someone to investigate why this fails. It might be expected without a namehint, but then why does it only fail on Linux?

**Comment by cool-dev-guy** [comment]
This code works perfectly fine on linux.

**Comment by Starbuck5** [comment]
The setup in the stackoverflow question is different than the setup in the test case I referenced.

Try something like this:
```py
import os

import pygame

pygame.init()

from pygame.tests.test_utils import example_path

data_fname = example_path("data")
path = os.path.join(data_fname, "house_lo.mp3")
if os.sep == "\\":
    path = path.replace("\\", "\\\\")
bmusfn = path.encode()

with open(bmusfn, "rb") as musf:
    pygame.mixer.music.load(musf)

print("success")
```

**Comment by cool-dev-guy** [comment]
Result:

> ```
> >>> python issue.py
> pygame-ce 2.2.1 (SDL 2.26.4, Python 3.10.6)
> success
> ```

**Comment by Starbuck5** [comment]
So it works locally and fails on CI.

Well that's a good outcome!

It would still be nice to actually add tests for this into the CI so that it doesn't regress in the future.
