### ISSUE TITLE
pygame._sdl2.Renderer is broken on my system.

### ISSUE THREAD

**Issue by yolowex** [pygame-community/pygame-ce#2190]
**Environment:**

- **Operating system**:
* OS: Kali GNU/Linux Rolling x86_64
* Kernel: 6.1.0-kali7-amd64 

- **Python version** 3.11.2
- **SDL version** 2.26.4
- **PyGame version** 2.2.1
- **Relevant hardware** 
* CPU: 11th Gen Intel i7-11700 (16) @ 4.800GHz 
* GPU: Intel RocketLake-S GT1 [UHD Graphics 750]

**Current behavior:**
_sdl2.renderer is broken on my system.
it says that Renderer is already associated with window

**Expected behavior:**
I want to render things using _sdl2

**Steps to reproduce:**

I just copied the code that @Starbuck5  made in discord _sdl2 channel, and pasted it into my problem, running it.

**Test code**
```
import pygame
from pygame._sdl2 import Renderer, Texture, Window
import os
here = os.path.abspath(".")+"/"
pygame.init()

screen = pygame.display.set_mode((0,0), flags=pygame.FULLSCREEN)
window = Window.from_display_module()
renderer = Renderer(window)

texture = Texture.from_surface(renderer, pygame.image.load(here+"Capture.PNG"))

print(list(pygame._sdl2.get_drivers()))

clock = pygame.time.Clock()

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            running = False

    renderer.draw_color = (255, 255, 255, 255)
    renderer.clear()

    texture.draw(None, None)

    renderer.present()

    clock.tick()
    print(clock.get_fps(), end="\r")

pygame.quit()
```

* Traceback, Stacktrace, error log ( or whatever it's called )

```
Traceback (most recent call last):
  File "/home/yolo/Workstation/Python/pygame/android-unit-test/main.py", line 10, in <module>
    import sdl2_test
  File "/home/yolo/Workstation/Python/pygame/android-unit-test/sdl2_test.py", line 9, in <module>
    renderer = Renderer(window)
               ^^^^^^^^^^^^^^^^
  File "src_c\cython\pygame\_sdl2\video.pyx", line 1107, in pygame._sdl2.video.Renderer.__init__
pygame._sdl2.sdl2.error: Renderer already associated with window
```

**Comment by Starbuck5** [comment]
Does `pygame.examples.video` work?

`python -m pygame.examples.video`.

**Comment by mmdmoa** [comment]
Yes it does.
It opens two windows

**Comment by mmdmoa** [comment]
I'll run it from source and start investigating the problem asap.

**Comment by mmdmoa** [comment]
I ran it from source and it seems that in `pygame.examples.video` the window is defined through _sdl2.Window and not 
pygame.display.set_mode .
But still, if the code you I earlier posted (which was made by Starbuck) works for other people, the problem has to be related to my OS.
I'll run the snippet in an Emulator to confirm it works in the same conditions that it doesn't in my host os.

**Comment by mmdmoa** [comment]
I ran the snippet in an emulated Windows 11 and had no issues.
I can confirm that the pygame and sdl version of both Windows 11 os and Kali linux OS were the same, and the snippet 
I mentioned above was run in the exact same conditions in both os's.
the code is not operational in my host os.

@Starbuck5

**Comment by cool-dev-guy** [comment]
I did a bit research(i also had the same error) and ```renderer = pygame._sdl2.video.Renderer.from_window(window)
``` fixes the issue

**Comment by mmdmoa** [comment]
> I did a bit research(i also had the same error) and `renderer = pygame._sdl2.video.Renderer.from_window(window)` fixes the issue
> 
> UPDATE:I currently builded pygame-ce from source and now the code @mmdmoa provided perfectly works.So i think updating pygame-ce may solve the issue.

Nope, for me using dev3 didn't solve the problem.

but replacing the code you provided with the recent one fixed my issue.

@Starbuck5 
regarding to this event, do you think it's possible that the problem is not with SDL itself?

**Comment by Starbuck5** [comment]
It's not like pygame-ce was creating a renderer for no reason before, and isn't.

cool-guy says that updating to dev3 fixed the issue, I'm very confident building from source is what actually fixed the issue.

My theory is that newer SDL (newer than your system SDL), creates a renderer in the backend when you get a display surface from a SDL_Window, and that explains the problem. So I think the problem is with SDL itself.

**Comment by mmdmoa** [comment]
@cool-dev-guy 
can you tell me what version of SDL are you using?
for me it's this:
```
pygame-ce 2.3.0.dev3 (SDL 2.26.5, Python 3.11.2)
```

**Comment by Starbuck5** [comment]
@yolowex Test this.

```c
#include <stdio.h>

#define SDL_MAIN_HANDLED

#include "SDL.h"

// my compile command
// gcc test.c -ISDL2 -lsdl2 -L.

#define SDL_ERROR                            \
    printf("SDL error: %s", SDL_GetError()); \
    exit(1);

int main()
{
    SDL_Init(SDL_INIT_EVERYTHING);

    SDL_Window *win = SDL_CreateWindow("test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 500, 500, 0);
    if (!win)
    {
        SDL_ERROR
    }

    SDL_Surface *screen = SDL_GetWindowSurface(win);
    if (!screen)
    {
        SDL_ERROR
    }

    SDL_Renderer *renderer = SDL_GetRenderer(win);
    printf("renderer = %p\n", renderer);

    SDL_Quit();

    printf("Finished.\n");
}
```

Getting the renderer from your window should be NULL, since a renderer was never created. However I think on your system it will not be NULL.

**Comment by yolowex** [comment]
When  I run it, I get this:
```
└─$ ./main
renderer = 0x5648f705f330
Finished.
```
this is a bad thing right?

**Comment by yolowex** [comment]
a contributor of SDL added a pr that probably solves this problem, but I have no Idea how to compile SDL to test if the issue is resolved.
You can access it from [here](https://github.com/libsdl-org/SDL/pull/7795) @Starbuck5

**Comment by slouken** [comment]
As mentioned in the PR above, using a renderer and a window surface at the same time isn't supported. I don't see any reason for a window surface to be created in the example above. Is there something happening under the hood in pygame to create one?

**Comment by cool-dev-guy** [comment]
> @cool-dev-guy can you tell me what version of SDL are you using? for me it's this:
> 
> ```
> pygame-ce 2.3.0.dev3 (SDL 2.26.5, Python 3.11.2)
> ```

I tried with 2 sdl versions including `pygame-ce 2.3.0.dev3 (SDL 2.26.5, Python 3.11.2)`,And it worked.

**Comment by cool-dev-guy** [comment]
> As mentioned in the PR above, using a renderer and a window surface at the same time isn't supported. I don't see any reason for a window surface to be created in the example above. Is there something happening under the hood in pygame to create one?

hey @slouken,
pygame-ce has this line `screen = pygame.display.set_mode((0,0), flags=pygame.FULLSCREEN)` which returns a widow-surface(i think,but it actually creates a window and returns a surface).So it creates a window-surface.

**Comment by slouken** [comment]
I think your assumptions are correct here. Some video drivers use a renderer for the window surface and some don't, and because of this you shouldn't try to mix the two.

Thanks for digging in and finding out why it wasn't working for you!

**Comment by Starbuck5** [comment]
>  As mentioned in the PR above, using a renderer and a window surface at the same time isn't supported. I don't see any reason for a window surface to be created in the example above. Is there something happening under the hood in pygame to create one?

@slouken pygame.display.set_mode was initially a direct port of SDL_SetVideoMode in SDL1.2, so it's job is to give a display surface. When porting pygame to SDL2 the API was kept very largely backwards compatible (something easier to do in Python than C, with duck typing and no concept of ABI).

So right now in mainstream pygame-ce there is no standalone concept of a Window. A Window class more similar to SDL_Window has been in development for a while, we hope to polish that up and release that as a stable API soon.

But the point is, pygame.display.set_mode both creates the window and gets the display surface.

We thought it would be cool if people could mix using the display.set_mode API with the experimental api (porting SDL_render) we've been working up.

So I wrote sample code that does display.set_mode and then tries to create a renderer from the same SDL_Window object later, and it was quite confusing to me that it didn't work for yolowex here.

Besides 1sybl's patch upstream, another potential way forward could be to make getting a Renderer after a display surface from a window an illegal operation consistently. The problem that made this hard to debug was that the behavior was very different cross platform.

**Comment by Starbuck5** [comment]
I'm pretty sure this difference in runtime behavior cross platform is also the cause of a recent regression discovered in one of our dev releases: #2236 

Pygame.display.set_mode has a flag SCALED that creates a "display surface" that is automatically streamed into an SDL_Renderer, to achieve GPU scaling and vsync support.

https://github.com/pygame-community/pygame-ce/blob/main/src_c/mouse.c#L74-L78
^These lines in our source assume that if a renderer exists, we created it (aka using pygame.SCALED)

Now that we know the problem the regression can be fixed, but it did take some investigating to get here.

**Comment by cool-dev-guy** [comment]
> I think your assumptions are correct here. Some video drivers use a renderer for the window surface and some don't, and because of this you shouldn't try to mix the two.
> 
> Thanks for digging in and finding out why it wasn't working for you!

Thanks for the reply.

**Comment by slouken** [comment]
Okay, I added functions for the next SDL release that will let you check whether a window surface has been created, and destroy it if you want to switch between 2D renderer and using the window surface. I also made creating a renderer fail if the window has a surface associated with it, so the limitation is more clear. :)

**Comment by ankith26** [comment]
Okay, I think this has been resolved. The upstream fixes here help in this usage erroring consistently.
OP can rewrite their code to use only the pygame-ce `Window` API and not use `pygame.display` API, and that should work.
