### ISSUE TITLE
Make use of multiline text rendering in `pygame.examples`

### ISSUE THREAD

**Issue by Matiiss** [pygame-community/pygame-ce#2206]
A lot of examples use multiple calls to `pygame.Font.render` to render different lines of text and then blit each returned surface at a different position, however, with the advent of multiline text rendering since `pygame-ce` version `2.1.3` that's not necessary anymore. 

So, all of these examples that have these multiple lines of text rendered this way, could switch over to a single call to `pygame.Font.render` and utilize `wraplength` and `\n` characters. Also those examples that implement alignment, could use `pygame.Font.align`.

A list of examples where this needs to be "fixed":
- [x] `dropevent.py`, simply add `wraplength` argument to the two `render` calls in the event loop so large dropped text gets wrapped (https://github.com/pygame-community/pygame-ce/pull/2235)
- [x] `eventlist.py`, a couple places where there's some iteration over lines of text instead of using a single call to `render`, also maybe add `wraplength` to `showtext` (https://github.com/pygame-community/pygame-ce/pull/2219)
- [x] `font_viewer.py` (https://github.com/pygame-community/pygame-ce/pull/2235)
- [x] `joystick.py`, `TextPrint` should use strings or lists for stuff that it does (lists for easier modifications on different lines, but render it using `str.join`) (https://github.com/pygame-community/pygame-ce/pull/2235)
- [x] `music_drop_fade.py` (https://github.com/pygame-community/pygame-ce/pull/2235)
- [x] `textinput.py` (https://github.com/pygame-community/pygame-ce/pull/2588 ~~https://github.com/pygame-community/pygame-ce/pull/2209~~)
- [x] `playmus.py`, switch over to `pygame.font` and utilize multiline rendering (should it be touched at all?) (https://github.com/pygame-community/pygame-ce/pull/2581)

**Comment by JiffyRob** [comment]
On it

**Comment by bilhox** [comment]
Hey ! Everything should be done here, it should be fine to close it now.
