### ISSUE TITLE
Documentation: Insufficient Contrast of Code Operators in Light Mode

### ISSUE THREAD

**Issue by Conz3D** [pygame-community/pygame-ce#2224]
Description:
The current color scheme for displaying code in the **light mode** of the page presents a readability issue. Specifically, operators are displayed in light gray on a light yellow background, which makes them nearly illegible on my system. I would like to recommend using a more contrasting color (brightness) for displaying operators to enhance readability.

Example: The code block in the Documentation has a "==":
https://pyga.me/docs/tutorials/en/newbie-guide.html#software-architecture-design-patterns-and-games

System:
    Operating System: Windows
    Browser: Firefox

Please let me know if any further information is required.

**Comment by yunline** [comment]
Screen shot:
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/474ca05d-386f-4137-a3b0-a1dd24a5ac0b)

**Comment by Conz3D** [comment]
The file with the issue:
https://github.com/pygame-community/pygame-ce/blob/main/docs/reST/themes/classic/theme.conf
the parameter and color for the operators and dots seems to be this one:
codedot                     = #D4D4D4
Maybe it will help to fix it.

**Comment by NOTMEE12** [comment]
https://github.com/pygame-community/pygame-ce/pull/2225.

Changed color to #242424.
ss:
![Zrzut ekranu (46)](https://github.com/pygame-community/pygame-ce/assets/103068655/267f920c-1a0d-4e32-8167-9f053e2af256)

**Comment by Conz3D** [comment]
Just for my understanding. @NOTMEE12, why are you pointing to issue #2225?
Can't see anything related there. Was this a typo? The issue here is #2224.

**Comment by NOTMEE12** [comment]
I'm not pointing to issue, but pull request.
I just decided to fix few bugs while making sidebar.
