### ISSUE TITLE
Gaussian Blur inconsistency with PIL

### ISSUE THREAD

**Issue by Sjmarf** [pygame-community/pygame-ce#2239]
I've noticed that performing a gaussian blur with `pygame.transform.gaussian_blur` makes a less blurry image than PIL's gaussian blur when the same radius is used. If the radius of the pygame blur is doubled, then they match up correctly. 

I assume this isn't intended behaviour? Is it possible that the radius was not doubled by Pygame CE when it should have been, or something like that?

Blurring a pygame surface with PIL:

```py
img = Image.frombytes(
    "RGBA", surface.get_size(), pygame.image.tostring(surface "RGBA", False)
)
img = img.filter(ImageFilter.GaussianBlur(radius=10))
blurred_surface = pygame.image.frombuffer(
    img.tobytes(), img.size, "RGBA"
)
```

With Pygame CE:

```py
blurred_surface = pygame.transform.gaussian_blur(surface, 10)
```

Side-by-side comparison, with both radii set to 10:

<img width="514" src="https://github.com/pygame-community/pygame-ce/assets/78750526/323745fc-8b3f-4215-a94c-b28f4af07bc7">

Both radii set to 10:

<img width="400" src="https://github.com/pygame-community/pygame-ce/assets/78750526/7e6f1e64-81dc-475b-8d9d-5a150aa7fbd5">

PIL with a radius of 10, and Pygame with a radius of 20:

<img width="400" src="https://github.com/pygame-community/pygame-ce/assets/78750526/302b2967-9513-4fbc-bfd5-049f09188fe3">

**Comment by yunline** [comment]
radius = 20px
![blur](https://github.com/pygame-community/pygame-ce/assets/31395137/167f6ea1-0f1d-4719-905d-908b9719030c)

So yes, I think this is a bug of pygame.

**Comment by Isoheptane** [comment]
It's noticeable that gaussian blur (Gaussian distribution) doesn't have a radius, instead it has a standard deviation (sigma).

In the gaussian blur implementation of pygame-ce, sigma is half the radius instead of radium. This may be the problem.

[/src_c/transform.c](https://github.com/pygame-community/pygame-ce/blob/e07e681b7e81decc84382aa0b2391c76d09ac996/src_c/transform.c#L3063)
```c
float *lut = malloc((radius + 1) * sizeof(float));
float lut_sum = 0.0;

for (i = 0; i <= radius; i++) {  // init gaussian lut
    // Gaussian function, radius=2*sigma
    lut[i] = (float)radius / 2.0f *
             expf(-powf((float)i, 2.0f) /
                  (2.0f * powf((float)radius / 2.0f, 2.0f))) *
             0.3989422804014327f;
    lut_sum += lut[i] * 2;
}
```

**Comment by Isoheptane** [comment]
I have rewritten the algorithm using Rust. Compared the algorithm with Rust's implementation, it turns out that sigma should be equal to radius.
![image](https://github.com/pygame-community/pygame-ce/assets/38118922/49d8fd00-885d-43ca-88dd-0bada6d433dc)
