### ISSUE TITLE
Drop Python 3.7 support?

### ISSUE THREAD

**Issue by MightyJosip** [pygame-community/pygame-ce#2252]
According to the release calendar provided [here](https://peps.python.org/pep-0537/#release-schedule) this month marks the end of support for Python 3.7. 

Few questions:
- Should we stop releasing pygame-ce new versions for python 3.7
- Will we get any advantage from it

**Comment by itzpr3d4t0r** [comment]
We dropped support for Python 3.6 already. Here: #1850 and here: #1896.

**Comment by Starbuck5** [comment]
It would be convenient to drop support when we add support for a release version of 3.12.

**Comment by narilee2006** [comment]
Nooo

**Comment by Starbuck5** [comment]
> Nooo

Numpy has already dropped support for Python 3.7 and Python 3.8. It's gotta happen eventually.

**Comment by Starbuck5** [comment]
According to our download statistics fetched using pypinfo, Python 3.7 makes up about 6% of our installations.

```
| python_version | download_count |
| -------------- | -------------- |
| 3.10           |          3,447 |
| 3.11           |          3,015 |
| 3.9            |          1,499 |
| 3.8            |            611 |
| 3.7            |            545 |
| 3.12           |             13 |
| 3.6            |             13 |
| 3.5            |              1 |
| Total          |          9,144 |
```

**Comment by Starbuck5** [comment]
Dropping 3.7 means dropping support for Debian Buster. This also allows us to raise our minimum SDL version.

A minimum of Python 3.8 means Ubuntu Focal (20.04), which corresponds to a minimum SDL version of 2.0.10. Currently, our minimum supported SDL is stated to be 2.0.8, but it's probably 2.0.9 in practice. 2.010 is from July 2019.
