### ISSUE TITLE
Enhancement: change import name from pygame to pygame_ce

### ISSUE THREAD

**Issue by elliottower** [pygame-community/pygame-ce#2264]
**Description**

Describe your enhancement, as clearly as possible.

Love what you guys are doing but unfortunately I've ran into a good number of issues due to other packages requiring pygame as a dependency, and the python interpreter importing `pygame` rather than `pygame-ce`. 

Sure for your own local environment it's easy enough to do `pip uninstall pygame`, but for a pyproject.toml/setup.py for another repo, it's impossible to specify requirements to uninstall as far as I know (maybe doable with poetry but migrating the project to poetry would be a task in itself), so if a subdependency you have requires pygame, you can't do anything besides manual uninstall. Maybe somebody has a better solution for managing this? I think it's kind of unavoidable though since they have the same import statement.

Just figured I'd throw this out there, as this was the solution [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) used to enable it to work alongside [OpenAI Gym](https://github.com/openai/gym): instead of having the same name, they just do `import gymnasium as gym`. I would think a migration guide could say to do `import pygame_ce as pygame`. 

It would be a bit cumbersome for new users and may be less than ideal as you would have to change code going forward to work with pygame-ce, but IMO it's worth it to have the clear distinction between the packages. Debugging things is a huge mess when you accidentally have both installed, as you get errors like ```font.render(
TypeError: function takes at most 4 arguments (5 given)``` which aren't immediately obvious that they are due to using pygame instead of pygame-ce.

**Comment by novialriptide** [comment]
This would require anyone who would want to migrate from pygame to pygame-ce to change all the imports in their files which would probably discourage them from migrating, but meh that's not really hard to do.

I would also like to point out that MonoGame & Microsoft XNA imports have remained the same when Microsoft XNA was discontinued, so we're not the odd ones out here.

https://docs.monogame.net/articles/getting_started/3_understanding_the_code.html

```cs
// MonoGame
using Microsoft.Xna.Framework;
```

**Comment by elliottower** [comment]
Fair enough, just figured I’d throw the idea out there but totally fair if it’s not desirable. Maybe there’s other ways to have both installed and have regular pygame code work as backwards compatible, but then certain functions from pygame-ce will be specific to pygame-ce? Don’t know if pythons import system would be able to make that work, but if it did search for the module in pygame and then search in pygame-ce after not finding it, that would be a nice solution.

For my case I need pygame-ce to do text wrapping, but the font.render function is shared from pygame and pygame-ce, with differing numbers of arguments. I saw for example that calling pygame.Font is not possible with regular pygame so that was something that showed my environment was using the wrong package. 

Maybe the best solution would be making explicit prints similar to the “hello from the pygame community” that regular pygame has (didn’t notice in my testing but maybe this already exists).

**Comment by Starbuck5** [comment]
One important thing is that at the time pygame-ce was created pygame hadn't had a release for more than a year, and there was no indication that would change. That's why pygame-ce was created. We followed the model of Pillow, which was the continuation of project of `PIL`, and which still uses `import PIL`.

> Debugging things is a huge mess when you accidentally have both installed

You can't have both installed (in the same environment) because they both install into the pygame folder in site-packages.

> Maybe the best solution would be making explicit prints similar to the “hello from the pygame community” that regular pygame has (didn’t notice in my testing but maybe this already exists).

This already exists.
You can test pygame-ce programmatically with https://pyga.me/docs/ref/pygame.html#pygame.IS_CE

> I've ran into a good number of issues due to other packages requiring pygame as a dependency, and the python interpreter importing pygame rather than pygame-ce.

What happens is pip installing those packages will overwrite pygame-ce with pygame. So you have to install those packages first, then uninstall pygame and install pygame-ce.

What packages are you having problems with? It's possible we could resolve things upstream. I've put in a PR or two dropping `pygame` requirements from requirements, which makes sense for projects that obviously require pygame. At least one library has a special pygame-ce edition, https://pypi.org/project/pygame-menu-ce/. But some people are porting over to requiring pygame-ce only.

**Comment by elliottower** [comment]
Good to know, thanks. I don’t imagine there’s an easy solution but I wonder if it would be possible to have a requirement of either pygame or pygame-ce. I’m the maintainer of pettingzoo (https://github.com/Farama-Foundation/PettingZoo) and we require pygame for certain environments. Don’t want to be heavy handed and do a pygame-ce dependency because lots of other libraries have pygame requirements and it would make things messy, but it would be cool if the pyproject.toml could require either one or the other. Did some googling but doesn’t appear possible. 

And pip list | grep pygame showed both installed but I can see how they overwrite each other.

**Comment by robertpfeiffer** [comment]
Having the opportunity to install both side by side in the same venv and then import both into one program would be a source of SDL errors as well.

**Comment by elliottower** [comment]
> Having the opportunity to install both side by side in the same venv and then import both into one program would be a source of SDL errors as well.

Makes sense, I’ll close this then as it seems not to be the best idea

**Comment by Starbuck5** [comment]
For the purposes of the library you maintain, you could drop any and all “pygame” requirements. This means you wouldn’t conflict with anyone’s environment. On a pygame ImportError you could print something special. Idk.

Of course as a member of the pygame-ce dev team I hope that you would consider requiring pygame-ce, to get access to the newest cool features, such as floating point Rects and multi line text rendering.

But I also understand why you’d want to just silently support both :)

**Comment by elliottower** [comment]
Yep makes sense, the only issue was just sub-dependencies which we don't have control over having pygame as a requirement, which when you do pip install -e . on our library, you needed to also do pip uninstall pygame and pip install pygame-ce, in order to not have things cause issues. Slightly annoying but not the end of the world. What would be nice would be if something like poetry allowed you to have specific instructions to uninstall libraries, instead of just dependencies, but that's probably not possible.
