### ISSUE TITLE
Documentation: Add 'color name/str' to list of allowed color values for pygame.draw.* and pygame.Surface.fill()

### ISSUE THREAD

**Issue by DickerDackel** [pygame-community/pygame-ce#2273]
**Environment:**

- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.3.1

**Documentation:**

I just learned, that the (all?) draw functions now allow a color name.  Docs still only say, Color, int and tuple are allowed, but not str.  Same for `pygame.surface.Surface`

**Expected behavior:**

str should be in the list of acceptable color arguments.

**Comment by Starbuck5** [comment]
PR is welcome :)

You can see how color.rst references color_list to link to the list of named colors.

**Comment by rethanon** [comment]
I can tackle this - the issue says it's affecting version 2.3.1, is that a typo? We don't' have 2.3.1 yet do we?

**Comment by DickerDackel** [comment]
Sorry, yes, 2.3.1 is a typo:

```
In [1]: import pygame
pygame-ce 2.3.0 (SDL 2.26.4, Python 3.11.4)

In [2]:
```
