### ISSUE TITLE
Should we remove old versionadded docs tags?

### ISSUE THREAD

**Issue by itzpr3d4t0r** [pygame-community/pygame-ce#2281]
In my opinion, considering that the first version of pygame-ce is 2.1.3 and it already encompasses all the functionalities of older versions of pygame, it is both confusing and unnecessary for actual users to be aware of which version each feature was added in. This is particularly true because users who try to search for these versions won't find them anyway. Therefore, in my PRs for the documentation (#2262 #2263), I have removed the `.. versionaddedold::` tags. What are your thoughts on this? How should we handle these tags in our docs? should we keep them or remove them?

I would also like to clarify that I am not advocating for the removal of pygame-ce version-specific documentation, as that serves a purpose by highlighting pygame-ce features.

The process of removing these tags will not be swift since a substantial portion of our documentation requires rephrasing and improvement. Hence, I suggest that we gradually phase out these tags while rewriting the documentation.

An example:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/dade28f9-3a1b-4873-a89c-665089ba9ab0)

**Comment by bilhox** [comment]
``: versionaddedold`` is used if it's an older version of pygame 2.1.3 ?

**Comment by NOTMEE12** [comment]
in some community projects it's neccesary to know in which version was feature added so other people could use the compatible version. I think we should keep it.

**Comment by ankith26** [comment]
I'm in favour of keeping it. I don't think maintaining the distinction leads to confusion

**Comment by itzpr3d4t0r** [comment]
Okay, I suppose the general sentiment is to keep them (I still think they serve little to no purpose to a pygame-ce user but wathever) so I'll close this as not planned. I'll reimplement the versionadded tags to my other docs PRs.
