### ISSUE TITLE
WASM: RuntimeError: pygame.PixelArray is not available

### ISSUE THREAD

**Issue by coppermouse** [pygame-community/pygame-ce#2283]
**Versions:**

- **pygame-ce 2.1.4.dev1** (SDL 2.24.2, Python 3.11.2)

**Background:**
I am using https://github.com/pygame-web/pygbag to run a game in browser.

I got a `RuntimeError: pygame.PixelArray is not available` error when I try to call PixelArray().

I open a discussion on pygbag making a suggestion to make PixelArray available. I thought this was closer to pygbag than pygame-ce.

After some discussion I was told the issue was on pygame-ce / pygame wasm port

https://github.com/pygame-web/pygbag/discussions/103#discussioncomment-6328621

**Issue:**

pygame.PixelArray does not seem to be available when in wasm port.

To replicate error message try run these two commands in the "wasm-port." ( I run them through pygbag session )
```
import pygame
pygame.PixelArray(pygame.Surface((1,1)))
```

I was given this link to test: https://pygame-web.github.io/showroom/python.html?-i
(but I think it might use based on pygame (not pygame-ce))

I of course have tested this locally with pygbag and looking at the output it seems to be using
`pygame-ce 2.1.4.dev1 (SDL 2.24.2, Python 3.11.2)`

Even though the pygbag-version is most likely not relevant because it out of your scope I still inform you that I use `pygbag==0.7.1
`
`

**Comment by oddbookworm** [comment]
I responded in the linked pygbag issue. If you've only tried `import pygame.PixelArray`, it's going to give an error, even locally. That's not the correct import. Try `import pygame.pixelarray`

**Comment by coppermouse** [comment]
> I responded in the linked pygbag issue. If you've only tried `import pygame.PixelArray`, it's going to give an error, even locally. That's not the correct import. Try `import pygame.pixelarray`

On this version:
- **pygame-ce 2.1.4.dev1** (SDL 2.24.2, Python 3.11.2)
(not sure what WASM port version)

and with this code:
```
print("===========")
print("import pygame...")
import pygame
print("...done")
print("import pygame.pixelarray...")
import pygame.pixelarray
print("...done")
```

I get this output:
```
===========
import pygame...
...done
import pygame.pixelarray...
181: FIXME dependency table for manually built modules
1202: want='pygame.pixelarray' found : False
PKG NOT FOUND : want='pygame.pixelarray', resume=<function <module> at 0xf1b920>, ex=ModuleNotFoundError("No module named 'pygame.pixelarray'")
```

**Comment by oddbookworm** [comment]
Why are you using a dev version of pygame-ce? Try using the most recent version

**Comment by coppermouse** [comment]
> Why are you using a dev version of pygame-ce? Try using the most recent version (2.3.0)

I am using pygbag 0.7.1 :) 

I do not think I am in control what version of pygame-ce it is using

**Comment by oddbookworm** [comment]
@pmp-p I don't think this is a pygame-ce problem. Pygbag is using an out-of-date dev version compiled from source. printing `pygame.__dict__` in pygbag reveals that pixelarray was not compiled into the version being used

**Comment by coppermouse** [comment]
Maybe. I do not know :)

I was told it was a bug in wasm pygame port and it should be reported here.

**Comment by pmp-p** [comment]
> @pmp-p I don't think this is a pygame-ce problem. Pygbag is using an out-of-date dev version compiled from source. printing `pygame.__dict__` in pygbag reveals that pixelarray was not compiled into the version being used

Thanks for the hint, i'll try on a fresh build as soon as i have some time

**Comment by coppermouse** [comment]
By reading the comments I have to trust that the issue is not in pygame-ce and therefore I close this issue.

**Comment by pmp-p** [comment]
2.3.1.dev1 does not seem to have a working pygame.PixelArray, so I would not close until pinpointed

**Comment by pmp-p** [comment]
i think PixelArray should raise an error at import if numpy is NOT in sys.modules : implicit imports are very confusing on wasm or ofthen impossible. 

Please confirm that module is useless without numpy ?

**Comment by JiffyRob** [comment]
> found the problem.
> 
> Question : is this module usefull or not whitout numpy ?
Useful without.

**Comment by oddbookworm** [comment]
Yeah, I'm pretty sure that pixelarray doesn't need numpy, but surfarray does

**Comment by pmp-p** [comment]
upgraded pygame-ce wasm wheel, seems to work but i'm no expert on that module :D
