### ISSUE TITLE
``pygame.joystick`` issues with Nintendo Switch Joycons

### ISSUE THREAD

**Issue by bilhox** [pygame-community/pygame-ce#2289]
- **Operating system** : Windows 10
- **Python version** : 3.10.0  
- **Relevant hardware** : Nintendo Switch Joycons

After experimenting with ``pygame.joystick`` module for Nintendo Switch Joycons, I found a lot of bugs and outdated things because between SDL 2.0.22 and SDL 2.26.4, a lot of things changed (mainly in SDL 2.24 with mappings). My goal isn't to use ``pygame._sdl2.controller`` and yes it's finished, no, what I want is improving the module.

**I :**

- **SDL version** : 2.26.4 
- **PyGame version** : 2.3.0

``pygame.joystick.init`` doesn't initialise the module properly, for example we should get ``pygame.JOYDEVICEADDED`` events at the beginning at least so we can detect the joysticks that are connected.

**II :**

- **SDL version** : 2.0.22
- **PyGame version** : 2.1.3

In pygame 2.1.3, no ``pygame.JOYAXISMOTION`` is generated when a stick is moved, when there should be ones.

**III :**

- **SDL version** : 2.26.4
- **PyGame version** : 2.3.0

In pygame 2.3.0, it's another event that isn't generated, it's ``pygame.JOYHATMOTION``. Observation : this event is correctly generated in pygame 2.1.3, and ``pygame.JOYAXISMOTION`` is correctly generated in pygame 2.3.0. Furthermore, ``pygame.Joystick.get_numhat`` says there are no hats in pygame 2.3.0, when in pygame 2.1.3, it says there are.

**IV :**

- **SDL version** : after 2.24
- **PyGame version** : 2.3.0

In SDL 2.24.0, the Nintendo Switch Joycons mappings got changed and they also introduced a new feature, now if you have the two joycons Left and Right connected, they get combined in one device. The problem is, ZL and ZR buttons aren't detected, is it a problem from SDL or pygame ? (In SDL 2.24 if I'm not wrong, L and R buttons aren't detected as well).

**V :**

- **SDL version** : 2.26.4
- **PyGame version** : 2.3.0

Finally, It isn't important but I think it should be said, when we to get the power state of the joycons with ``pygame.joystick.get_power_state``, we don't have the value right away after the ``pygame.Joystick`` object is created (is it expected ?).  Observation* : this method doesn't work at all wwith pygame 2.1.3, returning ``unknown``.

**Test code** : 

If you have nintendo switch joycons, and can connect them to your computer, it would be a pleasure if you could test it !

```py
# code from pygame-ce docs
import pygame
import os

os.environ["SDL_JOYSTICK_HIDAPI_COMBINE_JOY_CONS"] = "1" # If you want to combine the two joycons in one device

pygame.init()

class TextPrint:
    def __init__(self):
        self.reset()
        self.font = pygame.Font(None, 25)

    def tprint(self, screen, text):
        text_bitmap = self.font.render(text, True, (0, 0, 0))
        screen.blit(text_bitmap, (self.x, self.y))
        self.y += self.line_height

    def reset(self):
        self.x = 10
        self.y = 10
        self.line_height = 15

    def indent(self):
        self.x += 10

    def unindent(self):
        self.x -= 10


def main():
    screen = pygame.display.set_mode((500, 700))
    pygame.display.set_caption("Joystick example")

    clock = pygame.Clock()

    text_print = TextPrint()

    joysticks = {}

    done = False
    while not done:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                done = True  # Flag that we are done so we exit this loop.

            elif event.type == pygame.JOYBUTTONDOWN:
                print("Joystick button pressed.")
                if event.button == 0:
                    joystick = joysticks[event.instance_id]
                    if joystick.rumble(0, 0.7, 500):
                        print(f"Rumble effect played on joystick {event.instance_id}")

            elif event.type == pygame.JOYBUTTONUP:
                print("Joystick button released.")

            elif event.type == pygame.JOYDEVICEADDED:
                joy = pygame.joystick.Joystick(event.device_index)
                joysticks[joy.get_instance_id()] = joy
                print(f"Joystick {joy.get_instance_id()} connencted")
                print(joy.get_power_level())

            elif event.type == pygame.JOYDEVICEREMOVED:
                if event.instance_id in joysticks:
                    del joysticks[event.instance_id]
                    print(f"Joystick {event.instance_id} disconnected")
                else:
                    print(f"Tried to disconnect Joystick of id : {event.instance_id}, but could not find it in the joystick list")

        screen.fill((255, 255, 255))
        text_print.reset()

        joystick_count = pygame.joystick.get_count()

        text_print.tprint(screen, f"Number of joysticks: {joystick_count}")
        text_print.indent()

        for joystick in joysticks.values():
            jid = joystick.get_instance_id()

            text_print.tprint(screen, f"Joystick {jid}")
            text_print.indent()

            name = joystick.get_name()
            text_print.tprint(screen, f"Joystick name: {name}")

            guid = joystick.get_guid()
            text_print.tprint(screen, f"GUID: {guid}")

            power_level = joystick.get_power_level()
            text_print.tprint(screen, f"Joystick's power level: {power_level}")

            axes = joystick.get_numaxes()
            text_print.tprint(screen, f"Number of axes: {axes}")
            text_print.indent()

            for i in range(axes):
                axis = joystick.get_axis(i)
                text_print.tprint(screen, f"Axis {i} value: {axis:>6.3f}")
            text_print.unindent()

            buttons = joystick.get_numbuttons()
            text_print.tprint(screen, f"Number of buttons: {buttons}")
            text_print.indent()

            for i in range(buttons):
                button = joystick.get_button(i)
                text_print.tprint(screen, f"Button {i:>2} value: {button}")
            text_print.unindent()

            hats = joystick.get_numhats()
            text_print.tprint(screen, f"Number of hats: {hats}")
            text_print.indent()

            for i in range(hats):
                hat = joystick.get_hat(i)
                text_print.tprint(screen, f"Hat {i} value: {str(hat)}")
            text_print.unindent()

            text_print.unindent()

        pygame.display.flip()

        clock.tick(30)


if __name__ == "__main__":
    main()
    pygame.quit()
```

**Comment by ankith26** [comment]
Hi, thanks for reporting the issue.

Yeah, this is most likely another one of the SDL issues (joystick things tend to keep getting broken and fixed a lot over the version, lets hope things stabilize in the SDL3 times). For now what we can do is make a C reproducer and make an upstream SDL bug report

**Comment by bilhox** [comment]
Hi,

After talking with zoldama in discord:
- The first issue is just due to the way I'm initialising the module, ``pygame.init`` does it correctly, we can fix it by calling ``pygame.joystick.init`` after initialising the display module.
- About the second and third issue, we think it's intended
- About the fourth one, somehow after testing with SDL3, the ZL and ZR buttons are detected.
- About the fifth one, we didn't talk about it yet.

**Comment by bilhox** [comment]
Closing this as I have more hopes on ``pygame._sdl2.Controller``. Maintaining joysticks is a complicated case, but as the issue is mainly exposing mapping problems, I think this can be fairly be fixed with ``pygame._sdl2.Controller`` now.
