### ISSUE TITLE
Segfault when passing an empty StringIO to font.Font()

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2295]
**Environment:**
Windows 10
python 3.10.6
pygame 2.3.1 dev1
SDL 2.26.4
SDL_ttf 2.20.2

**Test code**
```py
import pygame
import io

pygame.init()

f=io.StringIO()

font=pygame.font.Font(f)
print(font.name)
```

```
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x000011cc (most recent call first):
  File "x:\python\pygame_test\font_path.py", line 10 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.joystick, pygame.event, pygame.imageext, pygame.image, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame.system, pygame._freetype (total: 39)
```

**Comment by yunline** [comment]
I tested some other file operations in pygame, and here is the result
| code | result | 
|-|-|
|`font = pygame.font.Font(f)`<br>`print(font.name)`|  Segmentation fault |
|`from pygame import freetype as ft`<br>`ft.init()`<br>`ft.Font(f)`|  Segmentation fault |
|`pygame.image.load(f)`| Run forever (no return) |
|`pygame.mixer.Sound(f)`| Raise an exception<br>`pygame.error: Couldn't read first 4 bytes of audio data` |
|`pygame.mixer.music.load(f)`| Raise an exception<br>`pygame.error: Couldn't read first 12 bytes of audio data` |
|`pygame.cursors.load_xbm(f,f)`| Raise an exception<br>`IndexError: list index out of range` |

<details>

<summary>Test Code</summary>

```py
import pygame
import io

pygame.init()

f=io.StringIO()

#font=pygame.font.Font(f)
#print(font.name)

#pygame.image.load(f)

#pygame.mixer.init()
#pygame.mixer.Sound(f)

#pygame.mixer.music.load(f)

#from pygame import freetype as ft
#ft.init()
#ft.Font(f)

#pygame.cursors.load_xbm(f,f)

```

</details>

**Comment by ankith26** [comment]
I'd like to add that this isn't really `StringIO` specific, it happens for any empty file-like object. My guess would be that this needs fixing on SDL side (to cleanly SDLError, instead of segfaulting)

**Comment by MyreMylar** [comment]
I created a PR to fix the two segfaulting ones. However the `pygame.image.load()` one currently gives me this error:

```
pygame-ce 2.4.0.dev3 (SDL 2.26.5, Python 3.11.1)
Traceback (most recent call last):
  File "C:\Users\dan\Programming\scrap\segfaults_fiile_io.py", line 8, in <module>
    pygame.image.load(f)
pygame.error: Unsupported image format
```

using this test program:

```python
import pygame
import io

pygame.init()

f = io.StringIO()

pygame.image.load(f)
```

Could SDL have fixed this/broken it at some point? I'm on windows with SDL 2.26.5 and SDL_Image 2.0.

**Comment by ankith26** [comment]
I can confirm the image one cleanly errors and I'm on Ubuntu 23.10. And myre's PR fixes the issue for font/freetype. I'll go ahead and close this issue, but if one of the issues is still persisting, feel free to re-open
