### ISSUE TITLE
Passing None as name to SysFont raises UnboundLocalError

### ISSUE THREAD

**Issue by zoldalma999** [pygame-community/pygame-ce#2298]
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 11
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.10.4
- **SDL version** (e.g. SDL 2.0.12): 2.26.4
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.3.0dev4, 2.3.0
- **Relevant hardware**: -

**Current behavior:**
Passing `None` as the name to `pygame.font.SysFont` errors out with the traceback you can see below. Probably caused by https://github.com/pygame-community/pygame-ce/pull/2147

**Test code**
```python
import pygame

pygame.init()
pygame.font.SysFont(None, 25)
```

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
  File "\foo.py", line 3, in <module>
    pygame.font.SysFont(None, 25)
  File "C:\...\Python310\lib\site-packages\pygame\sysfont.py", line 498, in SysFont
    return constructor(fontname, size, set_bold, set_italic)
UnboundLocalError: local variable 'fontname' referenced before assignment
```

**Comment by Starbuck5** [comment]
This has already been fixed on main.

**Comment by zoldalma999** [comment]
You are right, it does work on main. Should have checked that... I'll close this
