### ISSUE TITLE
mypy complains about `FRect` being assigned to `Sprite.rect`

### ISSUE THREAD

**Issue by Makoren** [pygame-community/pygame-ce#2300]
**Environment:**

- **Python version**: 3.11.4
- **PyGame version**: 2.3.0
- **mypy version**: 1.4.1

**Expected behavior:**

mypy analysis should succeed when assigning an `FRect` to `Sprite.rect`.

**Steps to reproduce:**

1. Copy the code below and run `mypy` on it.
2. Observe errors.

**Test code**

```
import pygame


class SpriteSubclass(pygame.sprite.Sprite):
    def __init__(self, groups) -> None:
        self.rect = pygame.FRect(0, 0, 100, 100)

```

**Stack trace/error output/other error logs**

```
main.py:7: error: Incompatible types in assignment (expression has type "FRect", variable has type "Rect | None")  [assignment]
```

Looking through the [stubs](https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/stubs/pygame/sprite.pyi), there's a handful of things that have type hints for `Optional[Rect]`. I don't know the code base so I don't know if this can be found elsewhere.

**Comment by rethanon** [comment]
@devdanzin the issue you referenced #2312 is now closed, so no need to wait for that one to be done.
