### ISSUE TITLE
Change sprites to use `FRect` by default?

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2312]
Since `FRect` is a thing now, should we use that by default in sprites? It might break a few poorly-designed games that use the integer-only behavior, but I think overall this would be a good change. Maybe also enforce type conversion into the correct type for that property? As of right now, I can do:
```python
import pygame

class Foo(pygame.sprite.Sprite):
        ...

bar = Foo()
bar.rect = "foobar"
```
This idea came about while looking at expanding the solution to #2300 to more generally fixing any missing `FRect` hints

**Comment by JiffyRob** [comment]
If it is decided that this needs done, I would be willing to take a whack at it.

**Comment by oddbookworm** [comment]
If this gets traction, then I think #2300 can be absorbed into this

**Comment by Starbuck5** [comment]
What does this mean? The users instantiate the Rects themselves, not the sprite class, right?

**Comment by oddbookworm** [comment]
> What does this mean? The users instantiate the Rects themselves, not the sprite class, right?

I'll be honest, no idea what I was talking about here. Maybe I was suggesting creating a default `FRect` for the `.rect` property of sprites instead of `None`. But, I was super tired and don't remember what I was really thinking

**Comment by Starbuck5** [comment]
> I'll be honest, no idea what I was talking about here. Maybe I was suggesting creating a default FRect for the .rect property of sprites instead of None. But, I was super tired and don't remember what I was really thinking

Ok, I'm going to close this issue since the direction is unclear.
