### ISSUE TITLE
Remove all traces of `pygame.cdrom`?

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2323]
Should we? Is it even possible to get that version of pygame anymore? Certainly `pygame-ce` doesn't have a release for it. Also, pretty sure that you can't even compile `pygame-ce` with SDL1 even if you could get SDL1

**Comment by Starbuck5** [comment]
Sure, we could do this. For pygame there was an advantage keeping the docs up with a warning at the top for old links, but I doubt anyone has linked to the cdrom module on pyga.me.

Then there's the c-code, c-api documentation. Not sure this module had types or tests.

`__init__.py` also tries to import it on import every time, putting it as a missing module object. It could be fine to keep that with it as missingmodule object.
