### ISSUE TITLE
Migrate `pygame.sprite` to C (and/or remove the Cythonized sprite)?

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2342]
There was an attempt upstream to port `pygame.sprite` to Cython, but that seems to have died. I thought a conversation was had about moving it directly to C, but I can't find any record of it. Should the module be ported to C?

**Comment by Starbuck5** [comment]
Personally, I don't think it's worth the effort.

**Comment by oddbookworm** [comment]
What about removing the cythonized sprite then? It's incomplete. Finishing it would lend to an argument for doing a full conversion to C because aren't we trying to get away from cython? Leaving it as-is would lend itself to being removed because it's not actually used anywhere, and it's not advertised as being an option.

**Comment by Starbuck5** [comment]
Options:

- Remove Cython sprite
- Fix up Cython sprite and make it the canonical sprite module
- Work up a C sprite and make it the canonical sprite module
- Fix up Cython sprite and make it a "fastsprite" module
- Work up a C sprite and make a "fastsprite" module
- Leave it as is, undocumented and strange private sprite module

**Comment by Starbuck5** [comment]
Currently I think the best course of option is just to remove cython sprite. I'm skeptical a thin object layer gains that much by transitioning to cython, or C, especially in the future once Mark Shannon has his way optimizing the CPython interpreter.
