### ISSUE TITLE
pygame.typing/pygame.types?

### ISSUE THREAD

**Issue by gresm** [pygame-community/pygame-ce#2389]
**Description**

Related to : pygame/pygame#3411 
It would be great to have such module. Currently typing is scattered across different files (ie: ``_common.pyi``, ``math.pyi``...), but none of them are really accessible for users, as types there are defined as "_LocalVariables" (also type stub files, so no type objects available on runtime). The lack of API for that often forces users to define such annotations themselves. But such solution isn't versatile, as if there is an update changing the library API, those changes are not reflected in the users code.

**Comment by ankith26** [comment]
It is a good suggestion, and it's one of the things in my to-do list. However, we already have a `pygame-ce` issue tracking it - https://github.com/pygame-community/pygame-ce/issues/1682

I'll be closing this issue as a duplicate, but feel free to comment under that issue any other related ideas

**Comment by gresm** [comment]
I agree with your decision, although I was aware of the fact that this issue is a "duplicate", but the last activity in #1682 comes from a year ago from the "original" repository. My intention was to bring up again that issue, because it seemed abandoned/forgotten about.
