### ISSUE TITLE
Add `color` kwarg to Surface __init__

### ISSUE THREAD

**Issue by itzpr3d4t0r** [pygame-community/pygame-ce#2414]
Would allow to directly get a colored surface by running
```Py 
surf = pygame.Surface((100, 100), color="red")
```
Instead of having to use Surface.fill afterwards
```Py 
surf = pygame.Surface((100, 100))
surf.fill("red")
```
This would of course support all ways to pass in a color as Surface.fill does.

**Comment by itzpr3d4t0r** [comment]
I mean it's a convenience feature, no wonder it got a good reception on discord. I guess little things like this that save you one line of code each time add up to form a bigger benefit overall.

**Comment by Starbuck5** [comment]
Saving a line of code is great for code golf, I don't see how this is helpful to people writing games in a normal setting.

**Comment by zoldalma999** [comment]
I agree with the comments made by Kennedy and starbuck - this is extra code for us to maintain, for not a lot of benefit.
