### ISSUE TITLE
Some colors in dark theme make text invisible

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2417]
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/a8e70295-7d76-4434-b073-6029980c00fb)
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/ece46df0-d2fe-4e55-a112-966ee7edf842)
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/bae09d60-d1f8-4e97-be83-b43944ac60a5)

**Comment by Notenlish** [comment]
fix: https://github.com/pygame-community/pygame-ce/pull/2418
