### ISSUE TITLE
incorrect hexadecimal RGB colors for fonts

### ISSUE THREAD

**Issue by bilhox** [pygame-community/pygame-ce#2425]
**Environment:**

- **Operating system** : Windows 11
- **Python version**  : 3.11
- **SDL version** : 2.26.4
- **PyGame version** : 2.3.1 / 2.4.0 (from main branch)

**Current behavior:**

when rendering text with ``font.render``, if you use a hexadecimal RGB color value, the color is interpreted like that : 
```py
0x010203
# ^^^^^^
# G B A
```

**Expected behavior:**

```py
0x010203
# ^^^^^^
# R G B
```

**Test code**

```py
import pygame

pygame.init()
screen = pygame.display.set_mode([1024, 768])

font = pygame.Font(None, 100)
text = font.render("HELLO", True, 0xff0000)
screen.blit(text, [100,100])
# the color will be green instead of red

while True:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            exit(0)

    pygame.display.flip()
```

**Comment by ankith26** [comment]
This isn't a bug, it's a feature :wink:

When integers are passed to `font.render`, they are interpreted as "mapped colors", the kind of thing that [`Surface.get_at_mapped`](https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_at_mapped) 

To change your code such that it works like how you want it, you can do `text = font.render("HELLO", True, "0xff0000")` instead.
