### ISSUE TITLE
Use "/" in the docs and stubs to signal lack of kwarg support

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2445]
See https://peps.python.org/pep-0570/ and https://github.com/pygame-community/pygame-ce/pull/1885

We can put them back into the stubs because we no longer support Python 3.6.

Is it also worthwhile to put them into the docs?

**Comment by Matiiss** [comment]
We can't put them back into the stubs because we still support 3.7 and the syntax was introduced in 3.8, we can, however, put them in the docs, I'd say that'd be a nice touch and make sense.

**Comment by Matiiss** [comment]
Now that as I understand we are dropping 3.7 support for 2.4.0, this becomes doable in the stubs and the docs. Will get on it hopefully this week then.
