### ISSUE TITLE
Docs build with warnings

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2453]
When I do a full build of the docs with `python setup.py docs --f` I see several warnings come up. I'd like someone to investigate the warmings and figure out how to eliminate them.

Docs of the docs: https://github.com/pygame-community/pygame-ce/blob/main/docs/README.md

**Comment by AndreyVarvar** [comment]
I will look into it
(At least I will try)

**Comment by AndreyVarvar** [comment]
I din't get any warnings...
I though perhaps i used wrong version on pygame-ce or python, or maybe it doesnt appear on MacOS.
I was using latest pygame-ce fork (2.3.2 i think?), python 3.11, MacOS.

**Comment by bilhox** [comment]
Hello,
Just like AndreyVarvar, I didn't get any warnings.
My current setup : 
- pygame 2.4.0.dev1 (main branch)
- python 3.11.4
- Windows 11

Could you provide more details on how you got the warnings ?

**Comment by bilhox** [comment]
@AndreyVarvar Hello ! You have to use Sphinx 7.2, be sure to have this version installed.

**Comment by Starbuck5** [comment]
Alright my bad y'all, the warnings were coming from outdated versions of Sphinx's own helper libraries (which of course don't get updated when you do `pip install sphinx --upgrade`.

I now see no warnings.

Sorry for the confusion!
