### ISSUE TITLE
why i can't find sprites ?

### ISSUE THREAD

**Issue by Watynecc** [pygame-community/pygame-ce#2528]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): LMDE 6
- **Python version** (e.g. 3.11.1, 3.8.5) : 3.11.2
- **SDL version** (e.g. SDL 2.0.12): 
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

Describe how the bug manifests.
![image](https://github.com/pygame-community/pygame-ce/assets/64525273/feb294d9-0a0e-4d8e-875b-748c12b81426)
I

**Expected behavior:**

it should have the sprites method ?
**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.
![image](https://github.com/pygame-community/pygame-ce/assets/64525273/773f3bef-6f60-4688-b368-75759642f1e1)
installed in a virtualenv

There's my code for it
https://pastebin.com/J5ATg4Gy

**Comment by oddbookworm** [comment]
@Watynecc did you install pygame-ce **then** uninstall pygame?

**Comment by oddbookworm** [comment]
If so, just reinstall pygame-ce

**Comment by Watynecc** [comment]
> @Watynecc did you install pygame-ce **then** uninstall pygame?

I will try tomorrow Thanks u !
