### ISSUE TITLE
`Vetor2/3.scale()`

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2541]
```py
>>> v = Vector2(2, 2)
>>> v.scale(2)
Vector2(4.0, 4.0)
>>> v.scale(1, 6)
Vector2(2.0, 12.0)
>>> s = Vector2(1.5, -2)
>>> v.scale(s)
Vector2(3.0, -4.0)
```

**Comment by JiffyRob** [comment]
Should this be `scale_by` so it matches `pygame.transform.scale_by` and `pygame.Rect.scale_by`?

**Comment by ankith26** [comment]
Not really sure this is needed tbh. `v.scale(2)` can be more compactly and neatly written as `v * 2`.

**Comment by oddbookworm** [comment]
I can see a potential use, but only in very limited capacity, when wanting to scale x and y differently, but I can't imagine a use-case for that

**Comment by yunline** [comment]
In numpy, it's easy to scale x and y differently.
```py
>>> v = np.array((2,2))
>>> v * (3, 6)
array([ 6, 12])
```
But in pygame, if you multiply two `Vector2`s, you got the dot product.
```py
>>> v = pygame.math.Vector2(2,2)
>>> v * (3, 6)
18.0
```
So if you want to get a x-y scaled vector, the code become ugly.
```py
s = Vector2(v1[0]*v2[0], v1[1]*v2[1])
s = Vector3(v1[0]*v2[0], v1[1]*v2[1], v1[2]*v2[2])
```
So why not `s = v1.scale(v2)`?

**Comment by JiffyRob** [comment]
There is `s = v1.elementwise() * v2`

**Comment by yunline** [comment]
@JiffyRob Thank you for pointing this out.

Sorry I didn't read the docs.
In https://pyga.me/docs/ref/math.html#pygame.math.Vector2.elementwise:
> All these operations will be performed elementwise. In addition vec * vec will perform a scalar-product (a.k.a. dot-product). If you want to multiply every element from vector v with every element from vector w you can use the elementwise method: v.elementwise() * w

So there is no need to add a `scale()` function to get a x-y scale, just use `elementwise()`.
Closing this issue.
