### ISSUE TITLE
API proposal for scaled (svg) image loading

### ISSUE THREAD

**Issue by ankith26** [pygame-community/pygame-ce#2600]
**Description**

I propose the addition of a new kwarg `scale` (default: `None`) to `pygame.image.load` that takes a size, and makes sure the output surface is in that size (if it is not None).

The idea is that if the source file is something like an SVG, we use the new SDL_image 2.6.0+ functionality that rasterizes the SVG at the given size, so the output looks clean even at arbitrarily large resolutions. Additionally, if the source is not an SVG, I'd like something like `pygame.transform.smoothscale` applied behind the scenes in the image loading function, so this scale argument is generic and not constrained by the format of the source file passed.

I'm gonna work on this proposal if it is accepted, I'm also open to discussing alternatives in this issue

**Comment by Starbuck5** [comment]
Thanks for writing out your idea ahead of time, that's something we could be better at.

My initial thought on this was that we should have a separate function to do this special behavior. Since it comes from `IMG_LoadSizedSVG_RW`, it would be like `pygame.image.load_sized_svg`.

**Comment by ankith26** [comment]
A couple of points on why my proposal is the way it is
- For now SVG is the most common vector graphics format, but what if something becomes more popular in the future, we add a new `load_sized_xxx` function, or update the `load_sized_svg` one making its naming incorrect? I would prefer a more generic approach.
-  I think the requirement of scaling an image after loading it is not a quite rare even for non-svg images, so a single function call to do both looks cleaner.

**Comment by Starbuck5** [comment]
Benefits to my approach
- Is very straightforward about the offered functionality ("it rasterizes svg files at a certain size")
- Follows SDL naming conventions

I feel that a specific function that shows the functionality we offer is better than a generic function that tries to smooth out differences, in this case. For example, your proposal uses smoothscale-- many images that would be scaled after load would want to use scale instead (pixelart).

Let's say that we implement this generically and then a new vector graphics format bursts onto the scene ("avg = ankith vector graphic"). SDL_image will probably add standard loading support first, and we will follow when we update SDL image. So we'll have this new vector graphics format upscaling through smoothscale. Then maybe next release SDL_image adds a special sized load function like `IMG_LoadSizedAVG_RW`. Now if we switch over our load sized implementation to this, we are changing behavior for games that already expect the previous smoothscale behavior for this format. In this regard, I don't see a generic function as more resilient to change.

**Comment by ankith26** [comment]
Okay, that makes sense. How about a `load_sized`? But at this point I agree we can still add `load_sized_svg` and add `load_sized` in the future if it happens to be useful

**Comment by mcpalmer1980** [comment]
Perhaps image.rasterize? To me image.load()ing a vector into a surface doesn't even make sense because it requires a size attribute apart from the loaded file.

Ankith's desire for a generic load_and_resize does sound convenient, but probably every pygame user has their own function for that, and if its being used in a game loop the user needs more help than a load_and_resize helper alone can provide.

All my graphics were done in Inkscape and manually rasterized to the scale/window size I want. Rasterizing from svg to the size needed for a device's native resolution would be awesome and save a bit of space.

**Comment by ankith26** [comment]
I think we have settled on adding a `load_sized_svg` for now (I also have a PR that could be merged ATM), but I support being open to adding any more convenience/generic functions in the future as needed
