### ISSUE TITLE
Pressing some keys prevent others keys to be detected has pressed

### ISSUE THREAD

**Issue by PotatEnjoyerOfTomboys** [pygame-community/pygame-ce#2611]
**Environment:**
- **Operating system**: Windows 10
- **Python version**: 3.10.11
- **SDL version** : 2.26.5
- **PyGame version**: Pygame-ce 2.3.2
- **Relevant hardware**: N/A (as far as I know, feel free to ask if needed)

**Current behavior:**

Pyagme is not detecting some keys being pressed when others are pressed.

**Expected behavior:**

Any key pressed should be detected by pygame.

**Steps to reproduce:**

1. Press the keys S and D at the same time
2. Press the key 2
3. Key 2 will not light up on the pygame window
It doesn't just happens with those 3 keys, 

**Test code**
```
import pygame as pg
pg.init()
WIN, CLOCK = pg.display.set_mode((25 * 10 + 60, 100)), pg.time.Clock()
font = pg.font.SysFont("system", 30)

while True:
    for event in pg.event.get():
        if event.type == pg.QUIT:
            quit()
    keys = pg.key.get_pressed()
    keyboard_inputs = [
        [pg.K_1, pg.K_2, pg.K_3, pg.K_4, pg.K_5, pg.K_6, pg.K_7, pg.K_8, pg.K_9, pg.K_0, pg.K_MINUS, pg.K_EQUALS],
        [pg.K_q, pg.K_w, pg.K_e, pg.K_r, pg.K_t, pg.K_y, pg.K_u, pg.K_i, pg.K_o, pg.K_p, pg.K_LEFTBRACKET, pg.K_RIGHTBRACKET],
        [pg.K_a, pg.K_s, pg.K_d, pg.K_f, pg.K_g, pg.K_h, pg.K_j, pg.K_k, pg.K_l, pg.K_SEMICOLON, pg.K_QUOTE],
        [pg.K_z, pg.K_x, pg.K_c, pg.K_v, pg.K_b, pg.K_n, pg.K_m, pg.K_COMMA, pg.K_PERIOD, pg.K_SLASH]
    ]
    for y, row in enumerate(keyboard_inputs):
        for x, column in enumerate(row):
            pg.draw.rect(WIN, [(0, 0, 0), (255, 255, 255)][keys[column]],
                         (25 * x + y * 10, 25 * y, 25, 25))
            WIN.blit(font.render(pg.key.name(column).capitalize(), True, (125, 125, 125)),
                     (25 * x + y * 10 + 5, 25 * y + 5))
    pg.display.update()
    CLOCK.tick(60)


```

**Comment by ankith26** [comment]
This is not a pygame issue, it's likely a hardware limitation called keyboard ghosting. To verify this, try opening some other standard application like a text editor, and press the 3 keys you mentioned together. If it is indeed keyboard ghosting, even that application would be able to tell the 3rd keypress.

You may have to buy a new keyboard if your requirement involves detecting multiple key presses together, or try using a virtual keyboard

**Comment by PotatEnjoyerOfTomboys** [comment]
I made some tests and it seems to be it. Thanks for the info.

**Comment by PotatEnjoyerOfTomboys** [comment]
I tested with an old keyboard I have and it doesn't happen. So yeah, it's just my laptop's keyboard the issue.
