### ISSUE TITLE
pygame.draw.rects

### ISSUE THREAD

**Issue by ScriptLineStudios** [pygame-community/pygame-ce#2672]
Could be implemented in either of the following ways: 
```python
pygame.draw.rects(surf: Surface, color: Color, rects: List[Rect])
```

```python
pygame.draw.rects(surf: Surface, sequence: ((Rect, Color), ...))
```

If we go down this route we may as well implement this issue in full - https://github.com/pygame-community/pygame-ce/issues/1628

**Comment by Matiiss** [comment]
Also since this is new API, we could just return None instead of a list of rects here, so as to speed up the whole thing even more (this will probably even make these functions work faster with single values than current single draw function that have to build and return a rect)

**Comment by itzpr3d4t0r** [comment]
May I remind you of these?
- https://github.com/pygame-community/pygame-ce/pull/1839
- https://github.com/pygame-community/pygame-ce/pull/1841
- https://github.com/pygame-community/pygame-ce/pull/1834
- https://github.com/pygame-community/pygame-ce/pull/1835

**Comment by itzpr3d4t0r** [comment]
And this: https://github.com/pygame-community/pygame-ce/issues/2208

**Comment by ankith26** [comment]
This issue comes under the same umbrella as https://github.com/pygame-community/pygame-ce/issues/2208 so for issue gardening purposes I will close this one
