### ISSUE TITLE
SysFont does not get the real bold version of a font

### ISSUE THREAD

**Issue by RasmusTufvesson** [pygame-community/pygame-ce#2677]
**Environment:**

- **Operating system**: Windows 11
- **Python version**: Python 3.9.1
- **SDL version**: SDL 2.28.5
- **pygame-ce version**: pygame-ce 2.4.0

**Current behavior:**

When I run `pygame.font.SysFont("arial", 20, bold=True)` it does not return the actual bold version of the font but the faked version.

**Expected behavior:**

What I expect to happen is that it returns the actual bold version. This returns the actual bold version when not using the community edition of pygame and when I load the font manually with ´pygame.font.Font("C:/windows/fonts/arialbd.ttf", 20)´.

**Screenshots**

Using pygame-ce
![image](https://github.com/pygame-community/pygame-ce/assets/59421787/f8642a4b-7e86-412f-bf40-26ced66b1fd6)

Using pygame
![image](https://github.com/pygame-community/pygame-ce/assets/59421787/826b79bf-6376-478b-9efd-5690b498ece6)

**Test code**

```
import pygame

pygame.init()
screen = pygame.display.set_mode((500, 90))
clock = pygame.time.Clock()

supposed_to_be_real_bold = pygame.font.SysFont("arial", 20, True)
real_bold = pygame.font.Font("C:/windows/fonts/arialbd.ttf", 20)

screen.blit(supposed_to_be_real_bold.render("This is using SysFont for bold", True, (255,255,255)), (10,10))
screen.blit(real_bold.render("This is manually using the bold font", True, (255,255,255)), (10,50))

running = True
while running:
    for ev in pygame.event.get():
        if ev.type == pygame.QUIT:
            running = False
    
    pygame.display.flip()
    clock.tick(60)
```

**Comment by Starbuck5** [comment]
Thank you for the report!

I narrowed this down to pygame-ce 2.3.0.dev4, and then narrowed it down to this PR: https://github.com/pygame-community/pygame-ce/pull/2147

**Comment by Starbuck5** [comment]
@RasmusTufvesson try installing this wheel-- I've implemented a fix for the issue.

[pygame-wheels-windows-CPython 3.9 (64 bit).zip](https://github.com/pygame-community/pygame-ce/files/13987219/pygame-wheels-windows-CPython.3.9.64.bit.zip)

You'll need to download, unzip, then you can pip install it directly e.g. `pip install pygame_ce-2.5.0.dev1-cp39-cp39-win_amd64.whl`

**Comment by RasmusTufvesson** [comment]
That has fixed the issue! Thanks
