### ISSUE TITLE
transform.scale() and transform.scale_by() crash when scaling large surfaces

### ISSUE THREAD

**Issue by bigwhoopgames** [pygame-community/pygame-ce#2681]
**Environment:**

pygame-ce 2.4.0 (SDL 2.28.5, Python 3.12.0)

**Current behavior:**

Trying to scale a large surface down in size crashes python back to command line

![image](https://github.com/pygame-community/pygame-ce/assets/72057030/b6592087-4a8d-433c-b2a2-c01b0a16577e)

**Expected behavior:**

A correctly resized surface

**Steps to reproduce:**

Running the following in python terminal results in a crash.

`import pygame

s = pygame.Surface((34688, 15507))
t = pygame.transform.scale(s, (12141, 5427))`

**Comment by oddbookworm** [comment]
It's a segfault on SDL's end, [here](https://github.com/libsdl-org/SDL/issues/8878( is the issue I opened over there for it

**Comment by oddbookworm** [comment]
Thanks for the report!

**Comment by ankith26** [comment]
This should be fixed now that SDL has been bumped in https://github.com/pygame-community/pygame-ce/pull/2705
