### ISSUE TITLE
ImportError: dlopen failed: is for EM_X86_64 (62) instead of EM_AARCH64 (183)

### ISSUE THREAD

**Issue by Gabryel-lima** [pygame-community/pygame-ce#2714]
**Environment: Android Studio build**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** Windows, WSL( Ubunto-20.04 ):
- **Python version** Python-3.8.10 :
- **SDL version** SDL 2.28.5:
- **pygame-ce version** pygame-ce-2.4.0:
- **Relevant hardware** Moto G22 Android 12, api 31:

**Current behavior:**

When I leave pygame-ce as requirements in buildozer.spec, buildozer seems to force the compilation of the apk for the Linux x86_64 arch instead of the target one that I defined as arm64
/-v8a.

**Expected behavior:**

I expected my game to at least stay on the home screen. Since when I started porting it to Android it is still native on desktop.

**Screenshots**

![image](https://github.com/pygame-community/pygame-ce/assets/125817153/fdaa3bba-2a33-458b-a63e-e01600bf3762)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Use a WSL with Ubuntu of this version or the one specified in buildozer.
2. Follow all the steps and requirements necessary to build the apk.
3. Explain in the .spec requirements at least the following: python3, pygame-ce.

**Stack trace/error output/other error logs**

[log.txt](https://github.com/pygame-community/pygame-ce/files/14211529/log.txt)

**Comment by bilhox** [comment]
I have the same problem, and it's now pretty urgent in my case, if possible, if anyone can fix it/has a solution, please feel free to contribute !

**Comment by MyreMylar** [comment]
Could try using the meson build process instead to see if that helps?

this PR:
https://github.com/pygame-community/pygame-ce/pull/2557

**Comment by Gabryel-lima** [comment]
> Estou com o mesmo problema, e agora é bastante urgente no meu caso, se possível, se alguém puder consertar/tiver uma solução, fique à vontade para contribuir!

I understand. In the last few weeks I have looked for various alternatives, including in the community, people are very open to coming up with a solution. The problem is that this one is very specific lol. Take a look at the android channel on Discord, I haven't read it yet, but the latest messages I think refer to a recipe that a colleague managed to implement for pygame-ce. I think this would actually be the most ideal solution in our case. But I'll let you know here if I find another alternative. Thank you!

**Comment by Gabryel-lima** [comment]
> Poderia tentar usar o processo de construção do méson para ver se isso ajuda?
> 
> este PR: [# 2557](https://github.com/pygame-community/pygame-ce/pull/2557)

Thank you friend! I will take a look.

**Comment by Gabryel-lima** [comment]
> Poderia tentar usar o processo de construção do méson para ver se isso ajuda?
> 
> este PR: [# 2557](https://github.com/pygame-community/pygame-ce/pull/2557)

If I use the wheel available for a specific platform, can I overcome this problem?
