### ISSUE TITLE
Translation of README into Portuguese-PT and Portuguese-BR

### ISSUE THREAD

**Issue by Gabryel-lima** [pygame-community/pygame-ce#2719]
### Description

@Starbuck5 
@Myre Mylar

Hey guys! What do you think about me being able to contribute a translation of the readme into two languages ​​I know? And where can I go so I can make a pull request?

**Comment by Starbuck5** [comment]
You could submit a pull request if you'd like.

Are Brazilian and Portuguese Portuguese different enough that they would need different texts?

We have a guide on how to do so: https://github.com/pygame-community/pygame-ce/wiki/Opening-a-pull-request

**Comment by Gabryel-lima** [comment]
> You could submit a pull request if you'd like.
> 
> Are Brazilian and Portuguese Portuguese different enough that they would need different texts?
> 
> We have a guide on how to do so: https://github.com/pygame-community/pygame-ce/wiki/Opening-a-pull-request

I understood. Thank you very much! Look, there isn't that much of a difference, you're right

I won't be home today, but as soon as I -  get there I'll check it out. Thanks!
