### ISSUE TITLE
Pygame-ce Steering Council Nominations 2024 🧛 🧛 🧛 

### ISSUE THREAD

**Issue by MyreMylar** [pygame-community/pygame-ce#2722]
Hello All,

It is that time of year when we start the process of pygame-ce democracy and elect a new steering council.

Currently the Steering council is currently a 3 member body with responsibility for deciding any pygame-ce project related policies, appointing new members to the pygame-ce organisation, providing one of the reviews for every pull request submitted and for making releases of pygame-ce. It's current membership is myself, @ankith26 and @Starbuck5.

The steering council is elected by the members of the pygame-ce organisation which is drawn from people who review and submit pull requests to pygame-ce on a regular basis. If you think you should be a member of the organisation and are not already, please let us know!

The election takes place next month, but before that we have the process of nominations where any member of the organisation can stand to be elected onto the steering council. If you would like to put yourself forward for the steering council then just reply to this issue and let me know so I can add you to next months ballot.

This issue can also serve as a place to discuss anything related to the steering council, steering council elections or changes in policy if you like.

**Comment by MyreMylar** [comment]
And to confirm - I will once again be standing for election if you will have me. Hopefully we can get that open issue number down to 250 or less in the next year!

**Comment by oddbookworm** [comment]
@Starbuck5
@ankith26

Can I nominate other people lmao? I'm gonna do it anyway

**Comment by Starbuck5** [comment]
Yes, I think you can nominate other people.

And I'll second Andrew's nomination of myself, just to say that I would be happy to continue serving in this role. 🙂 

I think there's a lot of exciting stuff for the future of pygame-ce, if we can get new things stable and supported. SDL3, Python without a GIL, Python with a JIT, GPU support, web support -- I've seen people online with a perception that pygame is old and outdated, I think we can show pygame is only old. 😄

**Comment by Starbuck5** [comment]
Pinging the whole team so everyone has an opportunity to nominate and/or share ideas: @pygame-community/pygame-contributors

**Comment by ankith26** [comment]
Thanks for nominating me Andrew, I would be happy to continue to serve this role.

I would also like to re-iterate the point MyreMylar mentioned, please do not hesitate to reach out if you think you must be on the member team on github. Make sure you do this within the next 1-2 weeks, so that you too get voting rights.

**Comment by Gabryel-lima** [comment]
I forgot to comment here, but I'm excited too. Even if participating here in the community for a short time. Let's expand this horizon!

**Comment by ankith26** [comment]
The election results are in, see linked issue above. Thanks!
