### ISSUE TITLE
Implement Vector2 and Vector3 sortability

### ISSUE THREAD

**Issue by bigwhoopgames** [pygame-community/pygame-ce#2724]
Please implement the ability for Vector2 and Vector3 classes to be sorted by default.

For instance:

```py
from pygame import Vector3

a = Vector3(0, 1, 2)
b = Vector3(1, 2, 3)
c = Vector3(0, 3, 4)

d = [c, b, a]
d.sort()
```

The above code should result in the list d being sorted to output [a, c, b]

This would be the equivalent of adding the __lt__ method to the vectors but should be done in the C code rather than the Python like so:

```py
class CustomVector2(pygame.math.Vector2):
    def __lt__(self, other):

        if self.x != other.x:
            return self.x < other.x
        else:
            return self.y < other.y

class CustomVector3(pygame.math.Vector3):
    def __lt__(self, other):

        if self.x != other.x:
            return self.x < other.x
        elif self.y != other.y:
            return self.y < other.y
        else:
            return self.z < other.z
```

**Comment by Starbuck5** [comment]
This can currently be implemented by the user as `d.sort(key=lambda x: tuple(x))`

Insofar as a changing the behavior:

Arguments in favor of adding this--
- Makes bigwhoop's use case work more elegantly and performantly
- Makes vectors more similar to tuples

Arguments against adding this--
- It's not obvious to me how vectors should be sorted. Magnitude? direction?
- More api surface to maintain
- Sort of non-obvious
- More code

Currently I'm -1 on implementing `lt` for vectors.

**Comment by MyreMylar** [comment]
Magnitude would be the only sorting value that makes sense I think.
Direction sorted would be arbitrary in a 1 dimensional sort.

**Comment by bigwhoopgames** [comment]
I would expect the sort to be done on the component x then y then z, If I wanted sorted magnitudes I would be working with magnitudes in the first place then sort them.

**Comment by novialriptide** [comment]
I don't see an effective use case where `.sort()` would be beneficial as Starbuck5 has stated that it would not be obvious to the developer on what it's sorting. I personally think it's better if it was like `pygame.math.sort_by_magnitude()` or something similar.

**Comment by bigwhoopgames** [comment]
Sorting by components rather than magnitudes is more in line with how entities are drawn to the screen. For instance sorting from left to right and top to bottom to draw entities in order based on a two or three dimensional position vector.

It seems to me that vectors are already component based and therefore should be sorted as such. I think most people would think of them dimensionally how they might be shown on a grid, as in which one comes first (first being read left to right top to bottom), rather than which one is longer.

**Comment by bilhox** [comment]
I'm against this feature, because mathematically speaking, you can't sort vectors, they don't have an order. The current way using with ``key`` is already great I believe. In any case, people would have a different opinion on how to sort vectors.
