### ISSUE TITLE
`pygame.math.Quaternion` and `pygame.math.Matrix`?

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2728]
Matrices and 4D vectors have come up in conversation before, but I don't recall that a final decision was ever made. I'm generalizing that a bit and proposing a more complete API that would be less nebulous than "it's useful sometimes". Specifically, quaternions are a common way to represent 3D rotations instead of a rotation matrix. Especially if we want to potentially add more support for 3D games, this would be a good place to start IMO

**Comment by Starbuck5** [comment]
Yes, I've seen dozens of conversations between people on the contributing discord channel about how matrices would be helpful. In all of these discussions, I've never once seen an actual proposal with use cases. I've seen lots of people debating random details and saying the nebulous (as you mentioned) "it would be useful." Hence, I'm very skeptical.

Maybe you all see something with matrices I don't have a strong enough math background for? But if I don't have a strong enough math background for it, I'd reckon most users don't either.

Lastly, if there's a use case and it's actually helpful, why does it need to be in pygame? Would it be handled well already by something like pyglm?

**Comment by ankith26** [comment]
I think there are multiple scientific packages that already provide this functionality, like maybe numpy and sympy.

Even if we add this as a pygame functionality, it would be more useful to extend what's already existing as opposed to making something up from scratch, which is more maintenance-heavy

**Comment by MyreMylar** [comment]
I guess this is not planned - _at least for now_. 

I could see revisiting it if 3D skeletal animation in pygame was a more realistic prospect but I suspect we need to go through several more steps before we get there and right now the matrix & quaternion math is already available alongside the packages you would have to grab to realistically do that stuff with pygame involved anyway.

In short - the main use cases for matrix/quaternion math is stacking 3D rotations/translations and we are not there yet in terms of rendering support in pygame alone.
