### ISSUE TITLE
Improvement to General Annotations

### ISSUE THREAD

**Issue by Gabryel-lima** [pygame-community/pygame-ce#2729]
**Description**

One of the things I've been noticing with pygame codes is the lack of explicitness in certain functions, parameters and methods. In many cases, even though a docstring explains very well what something does, there are still times when the IDE nor the person knows exactly what type of data to work with. Besides, it doesn't cost significant performance. What do you think? I would really like to be contributing to this issue.

**Example:**

def sum(a: int, b: int) -> int:
    return a + b

**Comment by oddbookworm** [comment]
Can you point to something specific? We whose whole existence is based on this

**Comment by bilhox** [comment]
Is there a specific reason why we don't add code documentation, directly in front of each method in the stub files ?

**Comment by Gabryel-lima** [comment]
> Você pode apontar algo específico? Temos tocos cuja existência é baseada nisso

### Here you can be sure of its purpose and type:

![Captura de tela 2024-02-25 161922](https://github.com/pygame-community/pygame-ce/assets/125817153/d3020f9b-191f-414d-9a0f-68b433a52193)

### But what about here?

![image](https://github.com/pygame-community/pygame-ce/assets/125817153/a9651067-ab12-409d-bff3-7cf87a7116c1)

**Comment by bilhox** [comment]
I'm pretty sure this present in all pygame method in the stub files, could you provide specific method case, where it's not present ?

**Comment by Gabryel-lima** [comment]
> Tenho certeza de que isso está presente em todos os métodos pygame nos arquivos stub. Você poderia fornecer um caso de método específico, onde não está presente?

I think I was redundant, maybe it was my lack of experience. Is it better to close this issue?

**Comment by oddbookworm** [comment]
I think adding docstrings to stubs might be worth it, but I'm not 100% convinced. That's additional overhead to maintain whenever an update gets made. There's also no real standard for doing it, so @ankith26 mentioned waiting on the ecosystem to improve before we integrate it [in the discord server](https://discord.com/channels/772505616680878080/772940667231928360/1147434193295515698)

**Comment by oddbookworm** [comment]
As for typing, if you can find errors in the actual types of the stubs, that's something that should be fixed

**Comment by oddbookworm** [comment]
The two example functions you pointed to are not very good examples for these reasons:
The first one is a test function. If you're not developing, you rarely ever need to interact with the tests, so public-facing API documentation isn't a priority for that
The second one is intended to be internal-API. That's the significance of the leading underscore. That's a standard python notation for "user can technically use this, but they're not supposed to"

**Comment by Gabryel-lima** [comment]
I understand perfectly

**Comment by Starbuck5** [comment]
I don't see the point of this issue at this point?

Does someone have a clear idea what this issue has developed into, or can this be closed?

**Comment by Gabryel-lima** [comment]
> I don't see the purpose of this issue at this point?
> 
> Does someone have a clear idea what this issue has developed into, or can this be closed?

I think I traveled a little, I'm wanting to do something cool

**Comment by ankith26** [comment]
I think this issue can be closed, but feel free to open more issues if you have any specific improvement ideas
