### ISSUE TITLE
Segfault when setting a pixel with PixelArray

### ISSUE THREAD

**Issue by bilhox** [pygame-community/pygame-ce#2740]
Original report : https://github.com/pygame/pygame/issues/4163#issue-2152065057

Environment:

Operating system: Linux / Windows (Endeavour)
Python version : 3.11.7
SDL version: 2.28.0+
PyGame version: 2.4.1
Current behavior:

Segfault when changing a pixel in a PixelArray with the syntax ``pixel_array[y][x]``. 
Returns an error ``ValueError: sequence size missmatch`` with the syntax ``pixel_array[x, y]``.

Expected behavior:

Target pixel is set to the requested color in the PixelArray, as per documentation.

Test code

```py
import pygame
test = pygame.Surface([800,800])
testBuf = pygame.PixelArray(test)
testBuf[400][400] = [255,255,0]
```
Stack trace/error output/other error logs
```
$ python3.11
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame-ce 2.4.0 (SDL 2.28.5, Python 3.12.0)
>>> test = pygame.Surface([800,800])
>>> testBuf = pygame.PixelArray(test)
>>> testBuf[400][400] = [255,255,0]
Segmentation fault (core dumped)
```

**Comment by ankith26** [comment]
Thanks for the issue, linked PR fixes the segfault.

As for your usecase, replacing `[255, 255, 0]` with `(255, 255, 0)` makes pixelarray interpret the object as a color and behave as you expect
