### ISSUE TITLE
Pygame-ce Steering Council Election 2024! 🐍 🐍 🐍 - RESULTS IN

### ISSUE THREAD

**Issue by MyreMylar** [pygame-community/pygame-ce#2749]
Hello,

The [nominations](https://github.com/pygame-community/pygame-ce/issues/2722) are now over and there is now a week to place your votes (assuming you are a [member](https://github.com/orgs/pygame-community/teams/pygame-contributors) of the pygame-ce contributor team).

Voting opens at 8:00pm UTC on the 13th March at this link:

[https://vote.heliosvoting.org/helios/elections/82573254-dcbe-11ee-a561-f6cbe569ef47/view](https://vote.heliosvoting.org/helios/elections/82573254-dcbe-11ee-a561-f6cbe569ef47/view)

Just log in with your Github account and place your vote!

Please let me know if anything doesn't work, I only run this once a year and this is only the second time so I'm not yet a master of democracy.

Thank you for voting!

**Comment by Starbuck5** [comment]
I voted! (Rather boring election this year, maybe it'll spice up next year)

Once again pinging the whole team to make sure people are notified @pygame-community/pygame-contributors 

Voting will be open for ~4 more days, it closes a week after it started.

**Comment by MyreMylar** [comment]
The election is now over! 🎉 

Results are here:

https://vote.heliosvoting.org/helios/elections/82573254-dcbe-11ee-a561-f6cbe569ef47/view

But the long and short of it is that @Starbuck5, @ankith26 and myself are duly re-elected for another year of pygame-ce fun!

Thank you all for voting!

**Comment by ankith26** [comment]
Thanks everyone for voting! :partying_face:

**Comment by Starbuck5** [comment]
I edited the steering council page on the wiki to reflect the election. https://github.com/pygame-community/pygame-ce/wiki/The-Steering-Council
