### ISSUE TITLE
Incorrect window size when import pywinauto

### ISSUE THREAD

**Issue by LondonClass** [pygame-community/pygame-ce#2752]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):Windows 10
- **Python version** (e.g. 3.11.1, 3.8.5) :3.9.13 
- **SDL version** (e.g. SDL 2.0.12):
- **pygame-ce version** (e.g. 2.4.0.dev4, 2.1.3):2.4.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

Set the scaling and layout settings of Windows to 150%
pywinauto version:0.6.8

**Current behavior:**

After importing pywinauto, the scaling of the pygame window is no longer affected by Windows settings. The actual window size is approximately 533*400.

**Expected behavior:**

The scaling of the pygame window is affected by Windows settings.
Window size is 800*600.

**Test code**
```python
import pygame
import sys
import pywinauto #When not importing pywinauto, errors will not occur

pygame.init()
WIN = pygame.display.set_mode((800, 600))
pygame.display.set_caption("Pygame Example")

def main():
    run = True
    while run:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                run = False

        WIN.fill((255, 255, 255))
        pygame.draw.rect(WIN, (0, 0, 255), (50, 50, 50, 50))
        pygame.display.update()

    pygame.quit()
    sys.exit()
if __name__ == "__main__":
    main()

**Comment by Starbuck5** [comment]
How is this a bug in pygame-ce?

I checked the source code of pywinauto, they're setting the whole process as DPI aware in one of their modules. Therefore any graphics controlled by the process would have this exact thing happen.

**Comment by LondonClass** [comment]
> How is this a bug in pygame-ce?
> 
> I checked the source code of pywinauto, they're setting the whole process as DPI aware in one of their modules. Therefore any graphics controlled by the process would have this exact thing happen.


So it's like this.

**Comment by Starbuck5** [comment]
Yep, I'm pretty sure!

You would achieve the same affect if instead of importing pywinauto, you declared dpi awareness yourself like in this example code: https://github.com/pygame-community/pygame-ce/blob/9111d6cc65926b85ab10f95db4d3573dbcf6eb4d/examples/prevent_display_stretching.py#L51

**Comment by LondonClass** [comment]
> Yep, I'm pretty sure!
> 
> You would achieve the same affect if instead of importing pywinauto, you declared dpi awareness yourself like in this example code:
> 
> https://github.com/pygame-community/pygame-ce/blob/9111d6cc65926b85ab10f95db4d3573dbcf6eb4d/examples/prevent_display_stretching.py#L51

Thank you, I know how to solve it now.
