### ISSUE TITLE
Exclude mac specific assets from other builds

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2780]
This should probably happen after https://github.com/pygame-community/pygame-ce/pull/2557, let that get resolved first.

We have mac specific assets:
src_py/pygame_icon_mac.bmp
src_py/pygame_icon.icns

Combined, they are 500kb.

~~If we can remove that from the 40 non-mac builds we do, we can reduce the size of a release by 20mb.~~
Edit: forgot about whl compression. They are 286 kb combined compressed, so the 40 builds would save a total 11.4 mb. That's almost as much as getting rid of a full wheel.

On another note, what are pygame_icon.icns and pygame.ico even doing?

**Comment by ankith26** [comment]
I also don't see how `pygame.ico` and `pygame_icon.icns` are being used, so we can probably remove them and then test if pygame applications show the icon as they should?
