### ISSUE TITLE
font.point_size is not equal to parameter size

### ISSUE THREAD

**Issue by LondonClass** [pygame-community/pygame-ce#2781]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):Windows 10
- **Python version** (e.g. 3.11.1, 3.8.5) :3.9.13 
- **SDL version** (e.g. SDL 2.0.12):2.28.5
- **pygame-ce version** (e.g. 2.4.0.dev4, 2.1.3):2.4.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

font.point_size is not equal to parameter size

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame

pygame.init()

# Define font file path and a list of fonts with different sizes
font_path = None
font_sizes = [10, 16, 24, 32, 40]  # List of different font sizes

# Iterate through different font sizes and check if their width matches the passed size
for size in font_sizes:
    font = pygame.font.Font(font_path, size)
    point_size = font.point_size
    
    if size == point_size:
        print(f"Font size {size} matches the point size {point_size}.")
    else:
        print(f"Font size {size} does not match the point size {point_size}.")

```

**Comment by oddbookworm** [comment]
Does it behave the same way with any non-default font? There’s some weirdness going on with the default font that gives it half the size that is currently kept around for backwards compatibility

**Comment by novialriptide** [comment]
Hi, I wrote `.point_size`.

It's stated that it "will not be accurate upon initializing the font object when the font name is initialized as `None`" as said here: https://pyga.me/docs/ref/font.html#pygame.font.Font.point_size and as Andrew has stated, this is meant to happen because of backward-compatibility.

**Comment by LondonClass** [comment]
> 嗨，我写了.`.point_size`
> 
> 据说它“在初始化字体对象时，当字体名称初始化为”时，它将不准确，如下所述： https://pyga.me/docs/ref/font.html#pygame.font.Font.point_size 正如安德鲁所说，这是由于向后兼容性而发生的。`None`

thanks.
