### ISSUE TITLE
problem with higher fps

### ISSUE THREAD

**Issue by pinkteddybearfluff** [pygame-community/pygame-ce#2846]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux(Mint)
- **Python version** (e.g. 3.11.1, 3.8.5) : 3.10.12
- **SDL version** (e.g. SDL 2.0.12): 2.28.5
- **pygame-ce version** (e.g. 2.4.0.dev4, 2.1.3): 2.4.1

**Current behavior:**

These issues below only occur at higher FPS( for FPS higher than 334) and used with delta time:
1. The player rect could only move UP or LEFT irrespective of keys pressed ie; K_W or K_UP or anything else.
2. Also it couldnt't move outside the game window it just stucks at the LEFT edge or TOP edge of the window as shown in screenshots.
3.  Even if FPS is not as high as 334, at maybe 120 or 200 FPS the left and top movement is smooth and fine but the down and right movement feels slow and down-right movement feels even slow.
4. If i don't put the FPS value in pygame.time.Clock().tick() and leave it at default FPS ,ie; (around 1000 or 2000 FPS for my pc this will likey cause the above problem)

**Expected behavior:**
Smooth movement in all directions

**Screenshots**

![Screenshot_2024-05-10_21-04-03](https://github.com/pygame-community/pygame-ce/assets/167787153/71191cc2-bc57-4721-a982-64b4b0836ce6)
![Screenshot_2024-05-10_21-04-24](https://github.com/pygame-community/pygame-ce/assets/167787153/415121f8-a5ff-4454-967c-24308453605e)
 
**Steps to reproduce:**

1.the issue could be reproduced with the test code with any key pressed and at FPS higher than maybe 500 or 1000(334 for me)

**Test code**

```
import pygame

pygame.init()
running = True
clock = pygame.time.Clock()
player_surf = pygame.Surface((32,32))
player_surf.fill("red")
player_rect = player_surf.get_rect(center = (640,360))
screen = pygame.display.set_mode((1280,720))

FPS = 500

while running:
    dt = clock.tick(FPS)/1000
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    keys = pygame.key.get_pressed()
    if keys[pygame.K_UP]:
        player_rect.y -= 300*dt
    if keys[pygame.K_DOWN]:
        player_rect.y += 300*dt
    if keys[pygame.K_LEFT]:
        player_rect.x -= 300*dt
    if keys[pygame.K_RIGHT]:
        player_rect.x += 300*dt
    
    pygame.display.flip()
    screen.fill(pygame.Color(48,48,48))
    screen.blit(player_surf,player_rect)
    
pygame.quit()
```

**Comment by oddbookworm** [comment]
I suspect this is an issue with the fact that normal rects truncate to integers. At higher fps, dt is so small that 300*dt is probably less than 1, making it essentially adding 0 when you add it to an integer. Try using an frect instead or using a vector for your position, and update the rect from that

**Comment by pinkteddybearfluff** [comment]
As oddbookworm  and Damus666 said , it worked perfectly fine by using frect but it doesn't work with the combination of only get_rect and pygame.math.Vector2() but as get_frect is new I will be using that anyways, so the issue is solved.
Thank You

**Comment by oddbookworm** [comment]
> it doesn't work with the combination of only get_rect and pygame.math.Vector2()

No, it works perfectly fine if you use them correctly. Here's your code modified to use a vector for positioning
```python
import pygame

pygame.init()
running = True
clock = pygame.time.Clock()
player_surf = pygame.Surface((32,32))
player_surf.fill("red")
player_pos = pygame.Vector2(640, 360)
player_rect = player_surf.get_rect(center = player_pos)
screen = pygame.display.set_mode((1280,720))

FPS = 500

while running:
    dt = clock.tick(FPS)/1000

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    keys = pygame.key.get_pressed()
    if keys[pygame.K_UP]:
        player_pos.y -= 300*dt
    if keys[pygame.K_DOWN]:
        player_pos.y += 300*dt
    if keys[pygame.K_LEFT]:
        player_pos.x -= 300*dt
    if keys[pygame.K_RIGHT]:
        player_pos.x += 300*dt

    player_rect.center = player_pos

    pygame.display.flip()
    screen.fill(pygame.Color(48,48,48))
    screen.blit(player_surf, player_rect)

pygame.quit()
```
