### ISSUE TITLE
Working with audio generates error (WSL2 - Windows11)

### ISSUE THREAD

**Issue by toxfu** [pygame-community/pygame-ce#2857]
**only pygame-ce enviroment on WSL (Windows 11)**

- **Operating system** (Linux(Ubuntu) WSL2):
- **Python version** (3.11.9) :
- sdl2                      2.30.2 
- sdl2_image                2.8.2
- sdl2_mixer                2.6.3 
- sdl2_ttf                  2.22.0 
- **pygame-ce version** (2.4.0.1):

when I want to work with audio, regardless of the code, it always generates the following error:

```bash
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1342:(snd_func_refer) error evaluating nam
...
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
...
pygame.error: ALSA: Couldn't open audio device: No such file or directory
```

I have already tried the solution with PulseAudio, it works well with applications. But I can't get it to work with pygame.

postscript: I have used this tutorial https://www.linuxuprising.com/2021/03/how-to-get-sound-pulseaudio-to-work-on.html

**Comment by ankith26** [comment]
It seems like pygame-ce is trying to find PulseAudio and failing, then falling back to using ALSA.

Could you try updating to pygame-ce 2.5.0.dev2 and using the PipeWire driver? To use the pipewire driver just do something like `SDL_AUDIODRIVER=pipewire python3 your_app.py`

**Comment by toxfu** [comment]
As I had been working with my WSL environment for years, at the time the audio was a problem, so I did the pulseaudio tutorial.

Searching I found that WSL now comes with WSLg (which has audio control included). Installed a new WSL environment and everything works great with audio (includes pygame-ce=2.4.1).

Thanks for your time.

**Comment by FrackinFamous** [comment]
> As I had been working with my WSL environment for years, at the time the audio was a problem, so I did the pulseaudio tutorial.
> 
> Searching I found that WSL now comes with WSLg (which has audio control included). Installed a new WSL environment and everything works great with audio (includes pygame-ce=2.4.1).
> 
> Thanks for your time.

Having a horrible time trying to figure out something similar.. I have pygame-ce audio works but is very laggy and eventually stops working... did you have to just install a new distro or completely reinstall wsl2?

**Comment by toxfu** [comment]
> Having a horrible time trying to figure out something similar.. I have pygame-ce audio works but is very laggy and eventually stops working... did you have to just install a new distro or completely reinstall wsl2?

It depends on what you've done. If you've made a lot of changes to the audio like I did, you'd have to revert everything, which is very tedious. It's better to install a new distro. It's not necessary to completely reinstall WSL

ps: the audio still doesn't work quite right, but that's a WSL-only problem, but the code will run without problems.
