### ISSUE TITLE
Portmidi broke cython

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2864]
In [this commit](https://github.com/PortMidi/portmidi/commit/64314cc3d1a6fdddfc6ff5408a3f83af685b8cea), portmidi broke our cython build. I opened #2863 to fix it on our end, and @Starbuck5 is opening an issue for portmidi. Hopefully the break was unintentional and the shim can be removed in the future

**Comment by Starbuck5** [comment]
@oddbookworm and @Mzivic7 both experienced this, their package managers must have updated to a new portmidi version.

Windows is unaffected because we haven't updated our portmidi prebuilts in forever. (Maybe we should do that?)

Portmidi issue: https://github.com/PortMidi/portmidi/issues/72
