### ISSUE TITLE
Grammar: Missing comma in main Readme?

### ISSUE THREAD

**Issue by whangho** [pygame-community/pygame-ce#2870]
It looks like there's a comma missing between two of the names in your Credits section of the main Pygame Readme. See the screenshots below:

![Screen Shot 2024-05-18 at 9 57 09 PM](https://github.com/pygame-community/pygame-ce/assets/114325042/12a7a4fa-18fd-42d4-8138-3b95cd9a6368)
![Screen Shot 2024-05-18 at 9 58 04 PM](https://github.com/pygame-community/pygame-ce/assets/114325042/81922157-7e63-4d11-8d0f-3d2f69d18cca)

**Comment by ankith26** [comment]
Good catch, thanks!
I am adding a good first issue label to this issue, for anyone interested in contributing to get started.
