### ISSUE TITLE
DOC: Add CONTRIBUTION.md and Contribution section to README?

### ISSUE THREAD

**Issue by MrF1ow** [pygame-community/pygame-ce#2883]
Hello,

I realize while looking through the documentation of this project, that there is no information about how to contribute to the project. With this being said, I am suggesting that we add a CONTRIBUTION.md and a small section in README that will lead new and existing contributors to that page when they need information regarding contribution. 

If this is approved, if you could assign me to it, I would love to take this on. 

Thank You!

**Comment by oddbookworm** [comment]
We actually have it scattered across multiple pages in the [wiki](https://github.com/pygame-community/pygame-ce/wiki), but yeah, maybe this is a good idea. @Starbuck5 @ankith26 @MyreMylar thoughts?

**Comment by MrF1ow** [comment]
I am more than happy to write something up for you guys and you see how you like it.

**Comment by Starbuck5** [comment]
As oddbookworm mentions we have contributing documentation in our wiki.

I'm not sure what you'd be write that isn't already there and is helpful, since you're not a pygame-ce contributor or maintainer.

If you'd like to help, try following the documentation that exists and point out any areas you got stuck.

**Comment by MrF1ow** [comment]
Here is what I was going to do:

- Add a CONTRIBUTION.md so it is linked in the GitHub repo.
- Organize and format current documentation you have to make it easy to read and understand in the CONTRIBUTION.md
- If you are up to the idea:
-              Add section about how to create and/or address issues in the project
-              Add section about using prefixes for pull requests, commits, and issues. For example, using "DOC" for any changes to documentation, and "ADD" for the addition of a feature, and "FIX" for fixing an issue, and a few more. 
- Add a "How To Contribute" section in the README that will be linked to the CONTRIBUTION.md

Reasoning:

Having these standards and methods for contributing in a centralized place for new and existing contributors would allow for consistency and clarity, ensuring all contributions follow a uniform format and style. This will in turn reduce confusion and facilitate easier review by you (the maintainers). 

My intention is not to waste your time, however, I think that this would both enhance and summarize what you guys have already done. I would love to do this for you guys, and if after review you still do not see the benefit no hard feelings.

**Comment by Starbuck5** [comment]
> Add section about how to create and/or address issues in the project
Add section about using prefixes for pull requests, commits, and issues. For example, using "DOC" for any changes to documentation, and "ADD" for the addition of a feature, and "FIX" for fixing an issue, and a few more.

We have a bug report template, and a wiki with contribution guides. Also "DOC", "ADD", and "FIX" are not how we do things. Trying to enforce that level of standardization on a volunteer group would be counterproductive, it's difficult enough to contribute already with the C code and the type hinting and unit testing that need to be done for every new feature.


----
On a totally separate note, I notice you go to OSU. I graduated from there last year. Small world.

**Comment by MrF1ow** [comment]
I know that we are not 100% sure about whether this would be a good change or not, but my pull request outlines what I changed and why it would be a good idea. I would appreciate it if you could take a look when you have a chance and let me know. 

Note: I did it in mark down format, however, if you like the addition of this file, I am more than happy to convert it to `.rst` and create another pull-request.

**Comment by MrF1ow** [comment]
> > Add section about how to create and/or address issues in the project
> > Add section about using prefixes for pull requests, commits, and issues. For example, using "DOC" for any changes to documentation, and "ADD" for the addition of a feature, and "FIX" for fixing an issue, and a few more.
> 
> We have a bug report template, and a wiki with contribution guides. Also "DOC", "ADD", and "FIX" are not how we do things. Trying to enforce that level of standardization on a volunteer group would be counterproductive, it's difficult enough to contribute already with the C code and the type hinting and unit testing that need to be done for every new feature.
> 
> On a totally separate note, I notice you go to OSU. I graduated from there last year. Small world.

Wow, that is a small world. I am assuming you graduated in computer science. What you up to now, other than this project?

**Comment by Starbuck5** [comment]
> Wow, that is a small world. I am assuming you graduated in computer science. What you up to now, other than this project?

I work as a data engineer in Seattle.

**Comment by MrDixioner** [comment]
I fully support the idea of ​​a centralized section for contributions to the project. This is much better than information that is scattered in various places in the documentation and takes a long time to find. For example, I still haven’t figured out how to take part in the translation of ALL documentation: for some reason this is divided into different parts between the main documentation and lessons. It is also not clear how to add a translation language.
For example, in the documentation of the Godot game engine, the section for contributing to the project describes in great detail and step by step how to contribute not only to the documentation itself, but also to its translation. In addition, the translation of documentation into Godot takes place on the Weblate server, which allows beginners to immediately get started without having to understand all the intricacies of the Git system.

**Comment by Starbuck5** [comment]
> I fully support the idea of ​​a centralized section for contributions to the project.

That's the wiki: https://github.com/pygame-community/pygame-ce/wiki

>  For example, I still haven’t figured out how to take part in the translation of ALL documentation: for some reason this is divided into different parts between the main documentation and lessons. It is also not clear how to add a translation language.

If you figure it out, please tell us. We haven't figured it out either. There isn't documentation for a strategy that hasn't been devised and implemented.

**Comment by Starbuck5** [comment]
I'm counting this as closed in #2910. Thank you.
