### ISSUE TITLE
Installation Failure using pixi

### ISSUE THREAD

**Issue by jeremy886** [pygame-community/pygame-ce#2946]
**Environment:**

I am trying this new package management tool pixi: https://github.com/prefix-dev/pixi

I tried `pygame-ce` first and no luck. Then I tried `pygame` and it worked.

```
% pixi add pygame-ce
  × could not determine any available versions for pygame-ce on osx-arm64. Either the package could not be found or version
  │ constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: No candidates were found for pygame-ce *.
      

% pixi add pygame   
✔ Added pygame
```

Other environment details, not included in `print_debug_info()`, that might help:
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

MacBook Pro M3
14.3.1 

**Current behavior:**

pygame-ce is not available.

**Expected behavior:**

just like `pygame` that can be installed.

**Screenshots**

N/A

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. brew install pixi
2. pixi add pygame-ce

**Test code**

N/A

**Stack trace/error output/other error logs**

N/A

**Comment by ankith26** [comment]
Hello, as far as I can tell `pixi` is a conda based package manager, and `pygame-ce` isn't on `conda`. 

However, from the [pixi repo](https://github.com/prefix-dev/pixi):
> This project is currently in the alpha stage. It's actively under development, and we're planning to add many more features. The file formats are still subject to change, and you should expect breaking changes as we work towards a v1.0.
> Some notable features we have in the pipeline are:
> - Build and publish your project as a Conda package.
> - Support for PyPi packages.
> - Support for dependencies from source.
> - Improvements to documentation, examples, and user experience.

I believe your issue will be resolved when `pixi` adds support for PyPI packages, as `pygame-ce` is available as a PyPI package.

**Comment by ankith26** [comment]
I will close this issue, as I believe this is something that could be resolved on the `pixi` side.

If that's not the case, feel free to open a new issue, or re-open this one.
