### ISSUE TITLE
docs: README.md probably outdated

### ISSUE THREAD

**Issue by twistios** [pygame-community/pygame-ce#2958]
In the file `README.md` in the `docs`-folder, Chapter "Generating the Documentation", it says that one should run
````bash
python buildconfig/make_docs.py
````
The folder `buildconfig` does not exist. I guess the file is outdated.

**Comment by oddbookworm** [comment]
Just double checking, you're running that in the root of the repository after you clone it right?
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/428f9075-b14a-4892-b1ad-b12d1aeb3588)

**Comment by twistios** [comment]
Oh, my bad, I got this issue because I was using this (new?) Pycharm feature that allows running commands from the `README.md`-file.

**Comment by twistios** [comment]
Maybe it should be added that one has to be in the main directory in the file?

**Comment by oddbookworm** [comment]
> Maybe it should be added that one has to be in the main directory in the file?

Generally commands like that are assumed to be from the root of the repository unless specifically otherwise stated
