### ISSUE TITLE
Nix Flake Support

### ISSUE THREAD

**Issue by Lumesque** [pygame-community/pygame-ce#2967]
**Description**

I created an [overlay](https://github.com/Lumesque/pygame-ce-overlay) for pygame-ce for support on Nix for putting it into python projects either on __nixos__ or on the default systems nix supports in its package manager, wanted to see what you guys thought/wanted out of it that isn't set up, and if any documentation is missing that would make it less confusing (and make sure it's okay for me to keep it up anyway)

Currently allows for using in a flake, or calling directly in `nix shell 'github:Lumesque/pygame-ce-overlay'`

**Comment by oddbookworm** [comment]
I definitely appreciate the effort that went into this after my recent foray into compiling pygame-ce on nix myself recently. @Starbuck5 @robertpfeiffer @ankith26 thoughts?

**Comment by oddbookworm** [comment]
I'll try to take a good look at it in the next couple of days, I've got a long weekend coming up, so I should have the time

**Comment by ankith26** [comment]
Nice work! As such, I don't think any of the active pygame-ce developers are regular Nix users, so we probably won't be able to test it out to confirm if it works.
Though I would like to point out one thing, going over the code. We are gradually moving away from the old `setup.py` based config to a newer `meson-python` based buildconfig. The old buildconfig is still in the source tree, and I can see that you are making use of it, but if possible I would recommend using the new one.

**Comment by Lumesque** [comment]
Ty!

> We are gradually moving away from the old `setup.py` based config to a newer `meson-python` based buildconfig.
> 
> 
> 
> 

Is there anywhere that I can find an example of how its run?

**Comment by ankith26** [comment]
For building wheels, you can invoke the one of the standard wheel tools: [`pypa/wheel`](https://github.com/pypa/wheel) or [`pypa/build`](https://github.com/pypa/build)

**Comment by oddbookworm** [comment]
Just got around to exploring this with a brand new NixOS install. Here's the point I'm at
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/02aef2e7-e8b7-4d14-98ae-4374dbe85aa1)

**Comment by oddbookworm** [comment]
It's a VM, so I expected some weird fails (like the time module), but I got some fails that seem unrelated to that
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/2b5c54b7-d85f-44ee-9b5a-f02016bd56f5)
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/c0290321-c856-442b-99f4-084c994fb066)
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/260a42da-4637-4561-b2de-d32dc28ab98b)
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/5c1716ff-bf3d-408e-8e85-642399811137)
Maybe this one is still related to it being a VM, so running slow?
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/f512ddfc-572e-4c59-b1aa-1d33babffcc1)
I also had a bunch of fails due to tests being unable to write to the file system, which I suppose is a nix issue that I just don't know how to fix

**Comment by oddbookworm** [comment]
Here's the `nix.shell` that I used
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/871a9d4a-85dd-47a2-a1d9-8aeebb2d3f5c)

**Comment by oddbookworm** [comment]
I was able to play the aliens example though, and everything seemed to be working fine (pretty low fps for that example and I had some really intermittent audio, but I blame the VM)

**Comment by oddbookworm** [comment]
Now that I look further, did I even do it correctly? Your overlay restricts to python 3.12 right? @Lumesque

**Comment by Lumesque** [comment]
> Now that I look further, did I even do it correctly? Your overlay restricts to python 3.12 right? @Lumesque 

Yeah I currently only have it set to be able to run in Python 3.12, ideally if you run
'nix flake init -t "github.com/Lumesque/pygame-ce-overlay#init"' and then run 'nix develop' you'd enter the correct corresponding shell

**Comment by oddbookworm** [comment]
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/868b5c14-629a-4ecd-874d-fa1690511947)
Yep, that's looking better

**Comment by oddbookworm** [comment]
I'm gonna have to install this directly instead of a VM lol. The test suite keeps segfaulting the VM and I have no idea why

**Comment by Lumesque** [comment]
Lmao weird that it segfaults the whole ass vm, I can probably test it on my end my laptop has NixOs installed if you give me what you want me to run

**Comment by oddbookworm** [comment]
`python -m pygame.tests` lol

**Comment by Lumesque** [comment]
![errors](https://github.com/pygame-community/pygame-ce/assets/138247800/8b14a911-46ec-4866-9d55-dd7e50a0516b)
I get these errors when I run python -m pygame.tests on it, don't fully know what they mean/why they'd happen

**Comment by oddbookworm** [comment]
That means that a test or two didn't run/complete (probably segfault)
I suspect it was `pygame.transform`s tests

Mind running `python -m pygame.tests transform` and see what happens?

**Comment by Lumesque** [comment]
![errors_again](https://github.com/pygame-community/pygame-ce/assets/138247800/d2add15b-796f-42b2-b7cc-c41291e1d7e0)
Ran that one and that one seems to pass, the window one fails tho, wonder if it's just something with my laptop display 'cause its intel integrated graphics not a full on gpu maybe?

**Comment by oddbookworm** [comment]
Hmmmmm, that particular error is interesting because it's ensuring that the window borrowed from pygame.display doesn't have opengl support when it wasn't originally created with opengl support
Interesting that it fails

**Comment by Lumesque** [comment]
Prob. will mess with it in pdb later, sounds kinda wild

**Comment by oddbookworm** [comment]
I don't know that pdb is enough lol. That's all done in C. I guess I'll have to install on bare metal and run some debug builds

**Comment by Lumesque** [comment]
lmao unlucky, I wonder if we're at the point where it might also just be how my nixos configuration is set up, I don't definitively define opengl anywhere in there

**Comment by oddbookworm** [comment]
That's why I'm focusing on testing. I suspect it's a nix-specific problem, but I don't know enough to guarantee that right now. Maybe @robertpfeiffer would have more direct knowledge?

**Comment by ankith26** [comment]
BTW, we have a [discord server](https://discord.gg/pygame), so if you would prefer that mode of communication, you can join the server and continue this topic there :)

**Comment by Starbuck5** [comment]
@Lumesque I've stumbled back on this issue, do you have a path forward you want to pursue? Are you still interested in this issue? (No shame if not)

If you want to maintain this package for the nix ecosystem we could link your repo as an unofficial thing in the setup instructions? "If you're on Nix: go to Lumesque". It would be nice if people on versions besides 3.12 could use it, if so.

Or do you want to commit it into our repo or have us maintain it somehow? It's not something we've done before, not even for things like conda. And we don't have much Nix expertise.

**Comment by Lumesque** [comment]
I forgot about the issue until now, but I do have some ideas for different paths forward (and some pros and cons)

1. Add to the repository directly
    *  The pros here is that it would be directly compiling from that repository as is every time, so you'd always have the most up-to-date mainline compiled pygamece
    * Cons here are that, if someone was to want to do a previous tag, that'd be difficult (they'd have to basically manually do it, though I could also make it a function in the outputs of the flake to override the version, but a bit tricky), also if something fails in the git workflow for `nix flake check`, that doesn't mean pygamece failed, though having it as a check in general could be a positive from some perspectives
2. Create a flake repository (The current one I've done, while works, is not up to standards as I've learned a lot about writing nix since then and the current way I did it didn't account for different compilations of systems for instance, or having non-python312 versions as you mentioned)
    * Pros here are that it'd be easier to go to previous tags/releases
    * Cons are that because it's separate, knowing when things break might be late, and if you ever wanted to test it prior to a push or something similar, you wouldn't be able to do so unless you (similar to previously mentioned function for overriding source) overrode where the repository source was coming from, also adding overlay can sometimes be hard to read but I mean, nix can be in general too.
3. Add to Nix repository directly
    * This one doesn't rely on flakes which can be seen as a positive, and it would be in the official Nix repository for all future users. This is essentially, a middle of the pack option, it does a mix of both specific releases as pygamece will prob. have different versions with different versions of nix, and you can create workflows to auto push to it
    * Cons here is maintainability, nix has seen some more unstable releases recently, and you wouldn't be in control of when those PRs get accepted, as for the other two I think the repository could still be under pygamece, even if unofficial, if you guys would still want to have full control of when things get pushed/pulled in, and if something breaks in nix in general like for 24.11 (at least from my understanding), the newest version would be delayed from individuals for n amount of months.
    * Another con here too, is that if you want to do different versions of your build system (as you've switched to **meson** now I believe?), you'd be hard stuck with whatever version those maintainers put into nixpkgs, though usually this hasn't led to issues and I'm sure they have workarounds I just don't know enough to say for certain.
    
Down to help out in any way you guys need, I enjoy writing nix lmao. Let me know what you think @Starbuck5

**Comment by Starbuck5** [comment]
Ideally, we could add this to the nix repository and have them shoulder the maintenance burden?

**Comment by Lumesque** [comment]
That works for me, I'll get started on messing with the repository; is there a readme or some documentation in your repository about the updated build system (I can't check the repository itself rn so can't see if it's in readme or a website or something)

**Comment by Lumesque** [comment]
@Starbuck5 Looks like someone put it into the nixpkgs repo already a few months ago, I checked looks like it's all good!

**Comment by Starbuck5** [comment]
Nice! Thank you for looking into this @Lumesque
