### ISSUE TITLE
Entire LICENSE being displayed in `pip show pygame-ce`

### ISSUE THREAD

**Issue by blankRiot96** [pygame-community/pygame-ce#2970]
**Description**

Using `pip show pygame-ce` displays the entire License
![image](https://github.com/pygame-community/pygame-ce/assets/77634274/3ab6a19c-88fe-4c07-a536-f9874c62a7a0)

Never seen this for other packages, and while it may be "allowed", I'd find it much more convenient to just be `License: GNU LESSER GENERAL PUBLIC LICENSE` (the name of the license)

https://pip.pypa.io/en/stable/cli/pip_show/#examples

**Comment by oddbookworm** [comment]
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/8de834ce-4ab8-4a3a-b65d-2a120dde973e)

@blankRiot96 fixed now by @ankith26

**Comment by blankRiot96** [comment]
Thanks ggs
