### ISSUE TITLE
Port SDL_FlashWindow

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#3049]
This one of the few SDL Windows features we don't have ported in pygame.Window.

https://wiki.libsdl.org/SDL2/SDL_FlashWindow (seems to be unchanged in SDL3)

This seems a fun and relatively straightforward addition.

API design wise, I think this could be window.flash(operation), and operation could be a flag representing https://wiki.libsdl.org/SDL2/SDL_FlashOperation ?

**Comment by damusss** [comment]
Do you prefer "verbose" constants names such as "WINDOW_FLASH_CANCEL" or "FLASH_CANCEL"?
