### ISSUE TITLE
sprite.Group.draw() doesn't work : TypeError: Source objects must be a surface

### ISSUE THREAD

**Issue by stucowade** [pygame-community/pygame-ce#3062]
Hi I tried to make a small game to entertain myself, however encountered the below issue:
I create a class for background display:
BGI1 = pygame.image.load(os.path.join('image','bg1.jpg')).convert()
class BGImage(pygame.sprite.Sprite):
    def __int__(self):
        pygame.sprite.Sprite.__init__(self)
        self.image = BGI1
        self.rect = BGI1.get_rect()
        self.rect.x = 200
        self.rect.y = 200

and add it to a sprite ground:

BackG = BGImage()
BG_Group = pygame.sprite.Group()
BG_Group.add(BackG)

But when I tried to use Group.draw() method to draw this sprite to the screen "BG-Group.draw(screen)", I got this:

TypeError: Source objects must be a surface

the argument "screen" is what I created from pygame.display.set_mode((800,800))
this means it is a Surface, but Group.draw(screen) always comes "TypeError: Source objects must be a surface"

Please help, thank you!!!

**Comment by bilhox** [comment]
Hello @stucowade ,

You made a small mistake in your class constructor name, it is ``__init__`` and not ``__int__``. 
You might also want to get help on your code so I suggest you to join the pygame discord server [here](https://discord.com/invite/pygame).

**Comment by stucowade** [comment]
> Hello @stucowade ,
> 
> You made a small mistake in your class constructor name, it is `__init__` and not `__int__`. You might also want to get help on your code so I suggest you to join the pygame discord server [here](https://discord.com/invite/pygame).

AHHH, OOOOPPP...Thank you man @bilhox , a blind man like me!!!
As well, thank you for the invitation! I will be there
