### ISSUE TITLE
Incorrect error message for vectors

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#3066]
I was digging through the math.c source and found this:

```py
>>> import pygame
pygame-ce 2.5.2.dev1 (SDL 2.30.6, Python 3.9.5)
>>> a = pygame.Vector2(30,40)
>>> del a.y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot delete the x attribute
```

I didn't try to delete the x attribute, I tried to delete the y attribute!

Implementation code (unchanged for 8 years):
```c
static int
vector_set_component(pgVector *self, PyObject *value, int component)
{
    if (value == NULL) {
        PyErr_SetString(PyExc_TypeError, "Cannot delete the x attribute");
        return -1;
    }
    if (component >= self->dim) {
        PyErr_BadInternalCall();
        return -1;
    }

    self->coords[component] = PyFloat_AsDouble(value);
    if (PyErr_Occurred())
        return -1;
    return 0;
}
```

**Comment by damusss** [comment]
This is probably related to the CPython API (but finding an answer online is hard because google doesn't understand the difference between python and cpython), but why is the function for setting the component also handling deletion?

**Comment by aatle** [comment]
Hmm, so vector `x`, `y`, `z`, and `w` all call `vector_set_component` from their setter function, which only has one hard-coded error message.

Also I am no C or CPython expert, but why is there seemingly unused `w` coordinate stuff in the code?

___

@damusss I did a bit of research and found the relevant C-API stuff:

pygame `Vector2` properties:
https://github.com/pygame-community/pygame-ce/blob/3183d1604fccf3a31e80c833d8b0f4b9abc3b199/src_c/math.c#L2605-L2609

`PyGetSetDef` [docs](https://docs.python.org/3/c-api/structures.html#c.PyGetSetDef) state:
> [setter](https://docs.python.org/3/c-api/structures.html#c.setter) set
Optional C function to set or delete the attribute. If NULL, the attribute is read-only.

**Comment by oddbookworm** [comment]
> Also I am no C or CPython expert, but why is there seemingly unused `w` coordinate stuff in the code?

Because it looks like someone at some point started implementing a `Vector4` class, which doesn't fully exist

> why is the function for setting the component also handling deletion?

https://docs.python.org/3/c-api/object.html#c.PyObject_SetAttr
Because that's a special-case for it, but it's deprecated behavior. I suggest moving to `PyObject_DelAttr` or `PyObject_DelAttrString` (which are both stable ABI as of 3.13 and both exist in all of our supported python versions)

**Comment by oddbookworm** [comment]
In fact, looks like it might emit an error in the future as we have it https://github.com/python/cpython/issues/106572#issuecomment-1628865815

**Comment by Starbuck5** [comment]
It handles deletion because that’s how the Python C API works.

This is not about pyobject_setattr.

**Comment by oddbookworm** [comment]
> It handles deletion because that’s how the Python C API works.
> 
> This is not about pyobject_setattr.

It actually is. The docs and that cpython comment indicate that the behavior is deprecated and you shouldn't have PyObject_SetAttr do your deleting anymore

**Comment by oddbookworm** [comment]
Hold on, I'm dumb

**Comment by damusss** [comment]
Thanks @aatle and @Starbuck5 for the info :)
