### ISSUE TITLE
Typing problems in new `pygame.typing` module

### ISSUE THREAD

**Issue by aatle** [pygame-community/pygame-ce#3074]
I noticed a few fixable problems while reading the new `pygame.typing` module.

**Environment:**

Commit https://github.com/pygame-community/pygame-ce/commit/9208ee52d8fa12dc74d0dd747eeffbf52398809d (not released yet)

### `_HasRectAttribute` protocol is implemented wrong
https://github.com/pygame-community/pygame-ce/blob/141a75df3e9be40394684d1474db0c0d641b6169/src_py/typing.py#L50-L53
The `Union` here means that a given class's `rect` attribute must support holding *both* a `RectLike` object and a function returning a `RectLike` object. Most classes, including `pygame.Sprite`, would only support one of those, and so would be incompatible.
In addition to this, the attribute must also be writeable, which is impossible if implemented as a method.
<details><summary>Possible fix:</summary>

```python
class _HasRectAttribute(Protocol):
    @property
    def rect(self) -> "RectLike": ...

class _HasRectFunction(Protocol):
    def rect(self) -> "RectLike": ...

_HasRect = Union[_HasRectAttribute, _HasRectFunction]
```
Test case classes for mypy (all passed):
```python
class Attr:
    rect: RectLike

class Method:
    def rect(self) -> RectLike:
        return [1,1,1,1]

class ReadProperty:
    @property
    def rect(self) -> RectLike:
        return [1,1,1,1]

class ReadWriteProperty:
    @property
    def rect(self) -> RectLike:
        return [1,1,1,1]
    @rect.setter
    def rect(self, value):
        ...

class FunctionAttr:
    rect: Callable[[], RectLike]

class ClassAttr:
    rect: ClassVar[RectLike]
```

</details>

### `_CanBeRect` covers an invalid case
https://github.com/pygame-community/pygame-ce/blob/141a75df3e9be40394684d1474db0c0d641b6169/src_py/typing.py#L47
Slightly imprecise; `[(1, 2), 3, 4]` would be compatible, but is not actually supported.
Fixed:
```python
 _CanBeRect = Union[SequenceLike[float], SequenceLike[Coordinate]]
```

### Custom defined `_PathProtocol` uses a bound TypeVar instead of constrained TypeVar
https://github.com/pygame-community/pygame-ce/blob/141a75df3e9be40394684d1474db0c0d641b6169/src_py/typing.py#L9-L15
As is common when supporting both `str` and `bytes`, a constrained TypeVar should be used (which disallows mixing (`str | bytes`) for the type var). (There is an `AnyStr` type var included in the standard `typing` module, but we cannot use it since it is invariant and protocols [can't have invariant type vars](https://peps.python.org/pep-0544/#overriding-inferred-variance-of-protocol-classes).)
Modeling after [`PathLike` definition in the python typeshed](https://github.com/python/typeshed/blob/main/stdlib/os/__init__.pyi#L415-L418), type var fix:
```python
    _AnyStr_co = TypeVar("_AnyStr_co", str, bytes, covariant=True)

    class _PathProtocol(Protocol[ _AnyStr_co]):
        def __fspath__(self) -> _AnyStr_co: ...
```

### `SequenceLike` protocol may be a bit strict
Protocol methods:
https://github.com/pygame-community/pygame-ce/blob/141a75df3e9be40394684d1474db0c0d641b6169/src_py/typing.py#L31-L32
The `__getitem__` signature mandates that an adhering class's `__getitem__` index parameter must be typed with `SupportsIndex`. However, some classes do not use `SupportsIndex` for the index parameter (using `int` or `slice` instead), including `collections.abc.Sequence`.
This means that `collections.abc.Sequence` itself and a method signature like `(self, index: int)` are not valid `SequenceLike`s.
So, replacing `SupportsIndex` with `int` will support more sequence classes, but at the cost of supporting less objects as indices.

**Comment by ankith26** [comment]
1. I think the existing implementation is correct. A `Union` of two types does not make the typechecker check for both. The test case you provided passes with the current implementation as well. But maybe I'm not understanding your point correctly here.
2. Yes this is definitely an issue, your suggested fix is good.
3. Yes this is definitely an issue, your suggested fix is good.
4. I didn't realise that `int` is incompatible with `SupportsIndex` (this is surprising). I think the solution to this problem is to use `Union[SupportsIndex, int]` then. It is important to keep including `SupportsIndex` because we want our `SequenceLike` to be compatible with the actual python `Sequence` itself

**Comment by ankith26** [comment]
Feel free to open a PR for these issues, so that the fixes are correctly attributed to you :)

**Comment by aatle** [comment]
Sure, I will work on a PR.

After looking further into the problems (because my past testing did fail with the current implementation), I realize that you are mostly correct about 1, but maybe misunderstanding 4.

**1.** (Thanks for the correction.) The current implementation is nearly correct except for another thing: implicitly, the `rect` attribute is declared as *writeable*, when in practice it is used as read-only. Mutability makes the attribute invariant, similar to `list` being invariant. (Reason why my tests failed on mypy.)
Using `@property` to type an attribute as not writeable is the common solution in the standard [typeshed](https://github.com/python/typeshed/blob/main/stdlib/typing.pyi).
Alternative fix (note: is basically equivalent to original proposed fix):
```python
class _HasRect(Protocol):
    @property
    def rect(self) -> "RectLike" | Callable[[], "RectLike"]: ...
```

**4.** Sorry for the misunderstanding; `int` *is* compatible with `SupportsIndex`. Also, this proposed change is a decision rather than a correction.
To define a method compatible with the [current protocol](https://github.com/pygame-community/pygame-ce/blob/141a75df3e9be40394684d1474db0c0d641b6169/src_py/typing.py#L31), one must type the parameter with a *broader* type than the protocol's as function parameters are contravariant.
However, the protocol's parameter is already broad (`SupportsIndex`), so less method implementations are compatible, *including* `collections.abc.Sequence`, which types it as `int` (+override for `slice`).
Proposed change:
```python
def __getitem__(self, index: int, /) -> _T_co: ...
```
Applying this would make `collections.abc.Sequence` a valid subtype of `SequenceLike`, but also make it so that `SupportsIndex`  objects cannot be used as an index for `SequenceLike` even though it is probably supported. So I am not sure whether this should be changed.

**Extra problem:** Mypy needs to be explicitly told that certain methods are abstract; it would otherwise give an error.
Fix is to put `@abstractmethod` on every method and property.

**Comment by damusss** [comment]
@aatle I don't want to sound stupid but why can't the rect attribute be writable?

**Comment by aatle** [comment]
@damusss The `rect` attribute does not need to be written to when handling a `RectLike`, so it is declared as a property with no setter. (This is required for the `Union` type in the protocol to work, because of variance.)
Note that this does not disallow the `rect` attribute being *implemented* as writable; rather, we make `rect` mutability *not required* in implementations.

**Comment by damusss** [comment]
> @damusss The `rect` attribute does not need to be written to when handling a `RectLike`, so it is declared as a property with no setter. (This is required for the `Union` type in the protocol to work, because of variance.)
> Note that this does not disallow the `rect` attribute being *implemented* as writable; rather, we make `rect` mutability *not required* in implementations.

I thought making it a property would disallow it being implemented writable, that makes sense then. Python typehinting is deeper than I thought lol
