### ISSUE TITLE
`pygame.draw.aaline(⋯)` segfault for 24-bit surfaces

### ISSUE THREAD

**Issue by geometrian** [pygame-community/pygame-ce#3075]
The following example causes a segfault (Python 3.12.5, pygame-ce 2.5.1):
```py
import pygame

surf = pygame.Surface( (315,271), depth=24 )

#Crash on following line:
pygame.draw.aaline( surf, (255,0,255), (100,207),(20,229) )
```
Some coordinates can be passed safely, while others cannot. When it works, it seems to draw a line with the correct locations, but blended incorrectly. Meanwhile, 32-bit surfaces do not have this problem. This tells me that this function is not respecting the pixel stride.

**Comment by damusss** [comment]
I haven't looked at how or why, but I'm sure if you added the result of `pygame.print_debug_info()` to the PR description it would help contributors.
