### ISSUE TITLE
Where is pygame ce 2.6.0?

### ISSUE THREAD

**Issue by MunaAlaneme** [pygame-community/pygame-ce#3082]
I know there is a pygame 2.6.0, but where is pygame ce 2.6.0?

**Comment by damusss** [comment]
From the moment pygame ce was created the versioning became independent. pygame ce on a lower version is much more optimized and has way more features.

**Comment by ankith26** [comment]
At the time of writing of this comment, the latest pygame-ce release (2.5.1) happened 2 weeks ago but pygame 2.6.0 happened two months ago.

As damus said, versioning is independent and so is the implementations.
