### ISSUE TITLE
Ambiguity in the mixer documentation

### ISSUE THREAD

**Issue by mentat51** [pygame-community/pygame-ce#3184]
We can init the mixer with a channels argument.
"The channels argument is used to specify whether to use mono or stereo. 1 for mono and 2 for stereo."

But we have two methods not related to this channels value:
pygame.mixer.set_num_channels and pygame.mixer.get_num_channels
The channels here are for playback, and the default value is 8.

I think a precision must be added to point that this two channels value are not related.

**Comment by ankith26** [comment]
I believe the linked PR fixes this issue so I'm closing this now, but feel free to reopen if more changes or clarification is needed, thanks!
