### ISSUE TITLE
After dropping Python 3.8 we can go up to SDL 2.0.14

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#3210]
We base our SDL minimum versions on the oldest common Linux package repository.

```
Ubuntu Focal => Python 3.8 and SDL 2.0.10              (we are here)
Debian Bullseye => Python 3.9 and SDL 2.0.14           (next step)
Ubuntu Jammy => Python 3.10 and SDL 2.0.20
Debian Bookworm => Python 3.11 and SDL 2.26.5
Ubuntu Mantic => Python 3.11 and SDL 2.28.3
```

Python 3.8 removal: https://github.com/pygame-community/pygame-ce/pull/3143

**Comment by bilhox** [comment]
what about other SDL libraries ?

**Comment by Starbuck5** [comment]
Focal: SDL_image 2.0.5, SDL_mixer 2.0.4, SDL_ttf 2.0.15
Bullseye: SDL_image 2.0.5, SDL_mixer 2.0.4, SDL_ttf 2.0.15

I don't think so, unless I'm messing up my searches.
