### ISSUE TITLE
```get_backends()``` sys.platform check for linux 

### ISSUE THREAD

**Issue by sonotopes** [pygame-community/pygame-ce#3223]
src_py/camera.py

```
def get_backends():
    possible_backends = []

    if sys.platform == "win32" and int(platform.win32_ver()[0].split(".")[0]) >= 8:
        possible_backends.append("_camera (MSMF)")

    if "linux" in sys.platform:
        possible_backends.append("_camera (V4L2)")

    if "darwin" in sys.platform:
        possible_backends.append("OpenCV-Mac")

    possible_backends.append("OpenCV")
```

Sorry if this is a nitpick issue, but since CPython 3.8>= is used, couldn't this line: 

```
    if sys.platform == "linux":
        possible_backends.append("_camera (V4L2)")
```

be used instead? According to the docs, there isn't really a need to use the 'in' operator since no major version will show up when accessing sys.platform (the string will just be 'linux')? Just a thought!

"Changed in version 3.3: On Linux, [sys.platform](https://docs.python.org/3/library/sys.html#sys.platform) doesn’t contain the major version anymore. It is always 'linux', instead of 'linux2' or 'linux3'."

**Comment by oddbookworm** [comment]
You're correct. Although, I think it looks cleaner as-is. I'm not going to block someone from making a pull request though

**Comment by sonotopes** [comment]
Gotchu. Is it alright if I make a PR for this?

**Comment by oddbookworm** [comment]
Go ahead if you so desire
