### ISSUE TITLE
Connecting a Krom (xbox 360-style controller) controller mid-game crashes pygame. 

### ISSUE THREAD

**Issue by willhlm** [pygame-community/pygame-ce#3225]
Hi, I'm developing a game where I want to use a controller. Actually using the controller works fine, however, connecting the controller via USB while the game is running crashes the game with the error below. Disconnecting during gameplay doesn't cause any crash. Connecting with USB prior to running the game works fine, and the controller can be used as intended. Error:

KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\willi\Desktop\Code\Games\happy_ville\game.py", line 78, in <module>
    g.run()
  File "C:\Users\willi\Desktop\Code\Games\happy_ville\game.py", line 55, in run
    self.event_loop()
  File "C:\Users\willi\Desktop\Code\Games\happy_ville\game.py", line 34, in event_loop
    events = pygame.event.get()
             ^^^^^^^^^^^^^^^^^^
SystemError: <built-in function get> returned a result with an exception set

Using a "krom key pro gaming wired gamepad" (Model: NXKROMKEY). Same button and joystick layout as a xbox 360 controller. 

Current environment:
pygame-ce 2.2.1 (SDL 2.26.4, Python 3.11.9)
Platform:               Windows-10-10.0.22631-SP0
System:                 Windows
System Version:         10.0.22631
Processor:              AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
Architecture:           Bits: 64bit     Linkage: WindowsPE
Driver:                 Display Not Initialized

Python:                 CPython
pygame version:         2.2.1
python version:         3.11.9

SDL versions:           Linked: 2.26.4  Compiled: 2.26.4
SDL Mixer versions:     Linked: 2.6.3   Compiled: 2.6.3
SDL Font versions:      Linked: 2.20.2  Compiled: 2.20.2
SDL Image versions:     Linked: 2.0.5   Compiled: 2.0.5
Freetype versions:      Linked: 2.11.1  Compiled: 2.11.1

Any help would be much appreciated.

**Comment by oddbookworm** [comment]
Try updating your pygame-ce version to the latest release and let us know if it’s still a problem

**Comment by willhlm** [comment]
Yea that solved it! That's a bit embarrassing hehe. Thanks a lot :)
