### ISSUE TITLE
No aaarc method in gfxdraw (355)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#365]
# **Issue &numero;355 opened by *[kjyv](https://github.com/kjyv)* at 2017-09-11 15:49:52**

The drawing method arc has no aa counterpart like most of the other draw methods. (Maybe it can be fashioned from the aaellipse method, modified such that it draws only parts of the ellipse?)

**Related Docs:** https://www.pygame.org/docs/ref/gfxdraw.html<hr>

# Comments

**Comment by zoldalma999** [comment]
I'll close this as gfxdraw has not been updated in a while, so they probably won't add it, and we are going in the direction of merging it with draw (and deprecating gfxdraw). If someone *really* wants this functionality though, feel free to comment or reopen the issue.
