### ISSUE TITLE
FreeBSD build issue (473)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#435]
#  **Issue &numero;473 opened by *[ndowens](https://github.com/ndowens)* at 2018-07-20 04:18:43**

Using UNIX configuration...

Hunting dependencies...
SDL     : found 1.2.15
FONT    : found
IMAGE   : found
MIXER   : found
PNG     : found
JPEG    : found
SCRAP   : found
Traceback (most recent call last):
  File "config.py", line 173, in <module>
    if __name__ == '__main__': main()
  File "config.py", line 161, in main
    deps = CFG.main()
  File "/wrkdirs/usr/ports/devel/py-pygame/work-py36/pygame-1.9.4/config_unix.py", line 232, in main
    d.configure(incdirs, libdirs)
AttributeError: 'NoneType' object has no attribute 'configure'
*** Error code 1

Stop.
<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2018-07-20 08:05:36*

Thanks for the report!

Sorry, I didn't get a chance to try 1.9.4 with freebsd before the release. We don't have a freebsd maintainer anymore. Also we don't have any build robots checking things in Continuous integration for freebsd (Travis CI and Appveyor don't support it).

cheers,
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-20 13:07:15*

Any idea how to fix it?  What I could change to make a patch for it. I’m not a programmer so I’m not sure how to fix issue

Older setup.py worked but for the latest version of pygame it don’t 
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-21 13:07:28*

All I know is that someone value of None is being returned 
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-23 01:09:11*

I believe this to be a possible issue on other platforms than just FreeBSD. For some reason configure seems to be returning None or d is returning/receieving None
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-23 16:56:22*

I have fixed it. Will link to patches. Though in summary it’s about the code to check if portaudio is portmidi part
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-23 22:14:23*

@illume 

https://pastebin.com/UJzFGetL

<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-24 03:41:29*

I was thinking, maybe you could add if os=freebsd skip that section I had to delete?
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2018-07-24 10:33:41*

Thanks for that :) Ah, it seems that portmidi does not exist for freebsd (from my limited searching). I've made a patch. Can you please try that? (see # 476 , branch portmidi-freebsd)
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-24 18:27:14*

I’ll try later today when I’m back on pc 
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-25 00:48:45*

Oh another I had to fix was I think in config where it says if linux import extra file that contains camera because it has import <linux dir/file.h>
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2018-07-25 10:27:47*

Thanks for trying that out. I've merged that PR.

I made another change in here to disable it except on linux. https://github.com/pygame/pygame/pull/478 

Perhaps at some point freebsd supported that header. The comment seems to suggest so, but I'm not sure. So we will just disable it until someone comes along who knows.
<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-25 21:40:19*

**src/_camera.c:213:36: error: use of undeclared identifier 'V4L2_CID_HFLIP'
    if (v4l2_get_control(self->fd, V4L2_CID_HFLIP, &value))
                                   ^
src/_camera.c:216:36: error: use of undeclared identifier 'V4L2_CID_VFLIP'
    if (v4l2_get_control(self->fd, V4L2_CID_VFLIP, &value))
                                   ^
src/_camera.c:219:36: error: use of undeclared identifier 'V4L2_CID_BRIGHTNESS'
    if (v4l2_get_control(self->fd, V4L2_CID_BRIGHTNESS, &value))
                                   ^
src/_camera.c:244:36: error: use of undeclared identifier 'V4L2_CID_HFLIP'
    if (v4l2_set_control(self->fd, V4L2_CID_HFLIP, hflip))
                                   ^
src/_camera.c:247:36: error: use of undeclared identifier 'V4L2_CID_VFLIP'
    if (v4l2_set_control(self->fd, V4L2_CID_VFLIP, vflip))
                                   ^
src/_camera.c:250:36: error: use of undeclared identifier 'V4L2_CID_BRIGHTNESS'
    if (v4l2_set_control(self->fd, V4L2_CID_BRIGHTNESS, brightness))
                                   ^
6 errors `generated.**

The camera patch doesn't work
It's probably just a Linux identifier

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2018-07-27 07:50:37*

Oops. So, I will have to set up a FreeBSD box to test with.

Thanks for trying it out.

<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-27 13:34:33*

The other one works fine just not camera patch
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2018-07-27 19:48:15*

I set up a freebsd box... 

Then I had some issues with `DEBUG = ` needing an extra space, and the pypm trying to be compiled. 
```
sudo pkg install devel/sdl12 git python36 py36-numpy-1.14.3,1 v4l_compat-1.6.3_1 graphics/sdl_image audio/sdl_mixer graphics/sdl_ttf
```

I had to install this package for the camera module to compile.
`sudo pkg install v4l_compat-1.6.3_1`

So, the config should detect the linux video header, and also it should detect portmidi not being there and not compile the pypm file if it's not there.

<hr>

# # #  **[ndowens](https://github.com/ndowens)* commented at 2018-07-28 17:42:05*

Yup seems to work :) :+1: 
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2018-08-01 15:12:20*

I'm glad it's working :)

Reopening the issue, because I'm still planning on patching pygame so it works out of the box on FreeBSD.

**Comment by MyreMylar** [comment]
Apparently there is no manylinux equivalent for BSD OS - but it is also 0.01% of the worldwide market, so I assume if you are choosing to use BSD you prefer to build everything from source anyway.

I think I will close this as it does not seem worth the development effort to build and maintain pygame-ce wheels for the subset of the dozens of users of BSD desktops worldwide who may also want to use pygame-ce and also are not used to building from source.
