### ISSUE TITLE
Most functions should accept keyword arguments (808)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#573]
#  **Issue &numero;808 opened by *[dlon](https://github.com/dlon)* at 2019-02-09 04:23:47**

Some modules to start with:

- [ ] surface
- [ ] display
- [x] draw
- [ ] color
- [ ] font
- [ ] rect
- [ ] event
- [x] mask
- [x] transform 

How?
- [Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
- See how other functions are using keyword arguments. See the [src_c/draw.c](https://github.com/pygame/pygame/blob/master/src_c/draw.c) module.
- Add the 'params' to the docs. See [docs/reST/ref/draw.rst](https://github.com/pygame/pygame/blob/master/docs/reST/ref/draw.rst)

<hr>

#  Comments

# # #  **[Bottersnike](https://github.com/Bottersnike)* commented at 2019-02-17 15:23:00*

Looking at it, it should just require changes from `METH_VARGS` to `METH_KEYWORDS` then have https://docs.python.org/2/c-api/arg.html# c.PyArg_ParseTupleAndKeywords be used to parse the arguments.
<hr>

# # #  **[charlesej](https://github.com/charlesej)* commented at 2019-03-30 20:28:50*

Changes for the draw module to accept keyword arguments is being done via # 896.
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2019-11-17 21:09:46*

See `rect-keyword-args` branch if anyone wants to finish off the rect kwargs.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-04-21 11:41:35*

Having a look at this, now I have pygame _mostly_ building on windows.
Modelling on the work @charlesej already did, I thought I'd start by having a go at doing one simple looking function in the event module, you can see my first commit here:

https://github.com/pygame/pygame/compare/master...MyreMylar:event-keyword-args

So the eventual syntax here would be:

`name = pygame.event.event_name(type=pygame.MOUSEBUTTONDOWN)`

it seems to work, though it is a bit of a trivial case. Was a bit unsure about specifying the 'type' of the 'type' parameter as int. I mean it _is_ an int but most people interact with the events system through the defined constants - but that is consistent with what was added by @charlesej .

If what I've done seems OK I can go through the rest of the event module. Not sure how/if we can handle the functions with two overlapping signatures like:

`set_blocked(type)`
`set_blocked(typelist)`

But there are definitely a couple of others that could have keyword arguments added.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-06-05 16:35:55*

I didn't really get very far with this one, I kept getting distracted by other things and was unable to think of neat solutions to map some c functions to python signatures. In the end my main interest was getting better auto-complete and linting support, which seems to have been largely solved by the .pyi files.

So, I'll let it go and see if anyone else has more interest in closing it off in the future.
<hr>

# # #  **[cwaldro](https://github.com/cwaldro)* commented at 2022-12-13 05:30:44*

I have been working on this task a bit with surface.c and would love to jump in as well.

**Comment by zoldalma999** [comment]
Superseded by #1990
