### ISSUE TITLE
Touch gestures (814)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#575]
# **Issue &numero;814 opened by *[dlon](https://github.com/dlon)* at 2019-02-12 03:20:43**

Functions:

https://wiki.libsdl.org/SDL_RecordGesture

https://wiki.libsdl.org/SDL_SaveDollarTemplate

https://wiki.libsdl.org/SDL_SaveAllDollarTemplates

https://wiki.libsdl.org/SDL_LoadDollarTemplates

https://wiki.libsdl.org/SDL_DollarGestureEvent

**Related Docs:** https://www.pygame.org/docs/ref/touch.html<hr>

# Comments

**Comment by zoldalma999** [comment]
Note to anyone wanting to implement this: SDL3 has removed the header that contains these functions and moved it to a different repo [here](https://github.com/libsdl-org/SDL_gesture). If we do add this, we will need to vendor the linked header in.

**Comment by zoldalma999** [comment]
I'll close this in favor of #2420
