### ISSUE TITLE
Scrap module lacks a quit() method (918)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#612]
#  **Issue &numero;918 opened by *[charlesej](https://github.com/charlesej)* at 2019-03-20 00:44:35**

The scrap module lacks a `quit()` method. It has `init()` and `get_init()` (PR # 748) methods, but is missing a `quit()` method.

Some general changes will be required, as well as code specific to each supported environment.

General changes:
- [ ] `src_c/scrap.c` and `src_c/scrap.h` - add/integrate `quit` method
- [ ] `test/scrap_test.py` - add test(s)
- [ ] `docs/reST/ref/scrap.rst` - update documentation

Environment specific changes:
- [ ] `src_c/scrap_mac.c` and `src_c/sdlmain_osx.m` - mac specific
- [ ] `src_c/scrap_qnx.c` - qnx specific
- [ ] `src_c/scrap_win.c` - windows specific
- [ ] `src_c/scrap_x11.c` - x11 specific

**Related Docs:** https://www.pygame.org/docs/ref/scrap.html<hr>

#  Comments

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-11-17 04:59:19*

Could this issue be closed if # 3510 gets merged because all of the old scrap would then be deprecated anyway (including `init` and `get_init`)? Under the new API, scrap would be initialized as long as the display module is initialized

**Comment by zoldalma999** [comment]
I agree with Andrew here, init function is deprecated so we probably don't want to add a quit method.
