### ISSUE TITLE
RTL text support. (with libraqm?) (1011)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#642]
#  **Issue &numero;1011 opened by *[weirman](https://github.com/weirman)* at 2019-04-30 04:20:05**

Hello Pygame folks, I have some questions about libraqm support. I don't know if pygame currently supports libraqm, but I found some information on these pages.(eg:[page1](https://github.com/HOST-Oman/libraqm/issues/64),[page2](https://bitbucket.org/pygame/pygame/pull-requests/52)). Can you tell me if pygame supports libraqm?Or how to use libraqm in pygame? Thank you.<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2019-04-30 06:35:40*

Hi. Sorry, I haven't looked into it in a while.

We can see again how to support RTL languages best in pygame. Any help evaluating it (and other solutions for RTL in pygame), and pull requests also very welcome.
<hr>

# # #  **[weirman](https://github.com/weirman)* commented at 2019-04-30 06:52:14*

Thank you for your reply. To this question (# 191 ) , I saw a [similar problem](https://github.com/python-pillow/Pillow/issues/2572) on pillow library and solved it with libraqm, So I think libraqm can be introduced to solve the problem of complex text rendering (I experimented with python3.5 at ubuntu14.04 and Libraqm works.) . [Here ](https://github.com/python-pillow/pillow-depends)is PIL's dependency library, [Here ](https://github.com/python-pillow/Pillow/tree/master/depends)is the depends scripts. I hope it helps.

<hr>

# # #  **[notpygame](https://github.com/notpygame)* commented at 2019-04-30 09:40:11*

Thanks @weirman 

There's an old PR here using libraqm: https://bitbucket.org/pygame/pygame/pull-requests/52/add-complex-text-layout-to-pygamefreetype/diff
<hr>

# # #  **[notpygame](https://github.com/notpygame)* commented at 2019-04-30 10:10:58*

From Pillow: "Windows support: Raqm support is currently unsupported on Windows."
https://github.com/python-pillow/Pillow/blob/master/docs/installation.rst

We could perhaps make this an optional dependency until it is packaged on more platforms like Pillow does.

Debian: yes, https://packages.debian.org/sid/libraqm-dev
Fedora: yes
Mac homebrew: no
Conan package: no
Windows build instructions: no (yes... see appveyor.yml)

<hr>

# # #  **[weirman](https://github.com/weirman)* commented at 2019-05-01 05:58:41*

@notpygame thank you so much.  I used the [PR]( https://bitbucket.org/pygame/pygame/pull-requests/52/add-complex-text-layout-to-pygamefreetype/diff) and solved my problem successfully.
<hr>

# # #  **[weirman](https://github.com/weirman)* commented at 2019-05-07 09:01:00*

@notpygame This [branch ]( https://bitbucket.org/pygame/pygame/pull-requests/52/add-complex-text-layout-to-pygamefreetype/diff)was installed successfully in Python2 and is available.But I had a problem with Python3 when it was installed. 
```bash
$ sudo python3 setup.py install
Skipping module _numericsurfarray for Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] build.
running install
running build
running build_py
copying lib/font.py -> build/lib.linux-x86_64-3.5/pygame
copying lib/version.py -> build/lib.linux-x86_64-3.5/pygame
running build_ext
building 'pygame.color' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_REENTRANT -DENABLE_NEWBUF=1 -I/usr/X11R6/include -I/usr/include/SDL -I/usr/include/python3.5m -c src/color.c -o build/temp.linux-x86_64-3.5/src/color.o
src/color.c:272:49: error: ‘Py_TPFLAGS_CHECKTYPES’ undeclared here (not in a function)
     (Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES)
                                                 ^
src/color.c:276:23: note: in expansion of macro ‘COLOR_TPFLAGS_COMMON’
 # define COLOR_TPFLAGS COLOR_TPFLAGS_COMMON
                       ^
src/color.c:316:5: note: in expansion of macro ‘COLOR_TPFLAGS’
     COLOR_TPFLAGS,
     ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Can you give me some advice?
`Environment:Python3.5 Ubuntu 16.04` 

I solved the problem by the following methods.
Add the code in the/src/pgcompath.h
```c
# ifndef Py_TPFLAGS_CHECKTYPES
# define Py_TPFLAGS_CHECKTYPES 0
# endif
```
<hr>

# # #  **[weirman](https://github.com/weirman)* commented at 2019-05-07 10:03:44*

@illume Thanks concern. I solved the problem by the following methods.
Add the code in the/src/pgcompath.h
```cpp
# ifndef Py_TPFLAGS_CHECKTYPES
# define Py_TPFLAGS_CHECKTYPES 0
# endif
```
So I closed this problem, if there is a new problem in use, I will re-open it  for submission.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-16 09:36:55*

I think we basically need to merge a really old branch supporting libraqm into the current master branch here?

<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-09-16 04:56:16*

Some updates on this issue, in the recent years freetype2 has been using harfbuzz, and SDL_ttf using freetype. I don't need we need libraqm to support RTL languages anymore, harfbuzz has some built-in support for it, which means that freetype2 and SDL_ttf do too.

We only need to export some new API like `set_script` and `set_direction` on our font class(es) and the underlying harfbuzz should handle all kinds of languages correctly

**Comment by zoldalma999** [comment]
This is supported in the font module now, with [`pygame.font.set_direction`](https://pyga.me/docs/ref/font.html#pygame.font.Font.set_direction). Closing as completed.
