### ISSUE TITLE
streaming long sound files (1156)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#695]
#  **Issue &numero;1156 opened by *[illume](https://github.com/illume)* at 2019-07-13 15:50:29**

How can you play multiple 2 hour long sound files with pygame?

**To Do to Close**

- [ ] Find a two hour long sound file for testing purposes.
- [ ] Confirm it doesn't work with current methods (python file stream object?)
- [ ] Investigate for another solution.

**Related Docs:** https://www.pygame.org/docs/ref/mixer.html# pygame.mixer.Sound<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-16 08:59:00*

Moved 'to do' list to first post
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-11-21 04:09:22*

Isn't this the kind of thing that `pygame.mixer.music` is meant for? `pygame.mixer.Sound` loads the entire data at once and that's expected behaviour, and `mixer.music` streams data from the file

IMHO this issue can probably be closed

**Comment by zoldalma999** [comment]
I agree with Ankith here, this is the reason `mixer.music` exists. We already have a way to do this, no need to add another way for no reason.
