### ISSUE TITLE
SDL2: scrap module (1178)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#703]
#  **Issue &numero;1178 opened by *[illume](https://github.com/illume)* at 2019-07-19 10:39:42**

seems the scrap module isn't being compiled with SDL2.

Related: https://github.com/pygame/pygame/pull/1175

**Related Docs:** https://www.pygame.org/docs/ref/scrap.html<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2019-10-03 12:55:23*

It's been compiled now thanks to these PRs:
- https://github.com/pygame/pygame/pull/1290
- https://github.com/pygame/pygame/pull/1284
- https://github.com/pygame/pygame/pull/1175

But there is still work to do.
<hr>

# # #  **[mcpalmer1980](https://github.com/mcpalmer1980)* commented at 2019-10-20 20:17:15*

Would redefining pygame.SCRAP_TEXT and decoding the byte string be enough?
<hr>

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2019-10-31 11:49:12*

I wrote the current SDL2-based scrap only as a stopgap.

In the long term, we should probably expose the SDL2 clipboard handling via _sdl2 and get the old win32/mac/x11 scrap stuff for binary image data working again.

In that case, I would propose deleting most of the existing scrap code base and re-implementing it in pure-ish python and ctypes.
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2020-09-27 18:06:56*

Removing the critical label, because I don't think it should block a pygame 2 release.

I personally have a couple of apps that use this, so I'd like to get to it eventually... but if anyone else wants to work on it, that'd be fine by me. Because I might not ever get to it with everything else left to do.
<hr>

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-05-24 21:14:21*

I did some further investigating of `scrap_mac.m`:
- It only supports text
- It was never updated for python3

I.e. it can be completely deleted in favor of using SDL's text clipboard support.

I think the whole `scrap` module should focus on getting support for text up to snuff, because that the most important target.

**Comment by MyreMylar** [comment]
The scrap module is now compiled and has seen various improvements and changes. I think we can close this generic issue.
