### ISSUE TITLE
Mixed colors come out pale on Mac. They only display correctly under window and cursor shadows. (1214)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#726]
#  **Issue &numero;1214 opened by *[atylmo](https://github.com/atylmo)* at 2019-07-31 00:50:52**

I can't capture it with screenshots, but when you do a `surface.fill()` and pass in a color mixture such as for yellow `(255, 255, 0)` or cyan `(0, 255, 255)` it looks washed out. Screenshots don't exhibit the problem, nor does accessing the Mac over VNC. It's only visible in person.

Window shadows and mouse cursor shadows that pass over the Pygame window display the color correctly underneath them. If you drag the window down toward the Dock you can see the correct color only within the shadow of it. But primary colors, i.e. red `(255, 0, 0)`, look fine.

I can temporarily change the monitor's color profile to fix it, but when I start the program again I have the same problem, regardless of which color profile I picked before.

Here's a reduced test case that exhibits the issue:

```
import pygame
import sys

CYAN = (0, 255, 255)

pygame.init()
screen = pygame.display.set_mode((640, 480))
running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        
    screen.fill(CYAN)
    pygame.display.flip()

```

Specs: Python 3.7.6 via Homebrew, pygame 2.0.0dev3, macOS Catalina Beta 4 (but it also happens on Mojave). I think it also happens with Pygame 1.9.6. It doesn't happen on Ubuntu 19.04.<hr>

#  Comments

# # #  **[markph0204](https://github.com/markph0204)* commented at 2019-09-09 14:29:05*

pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.3) | Mac 10.14.6

I'm unsure i'm seeing the issue you are describing.  I was only given five crayons as a kid -- so maybe its just my failure to represent colors properly. :)

For the above code -- I was able to use a color picker and get the value: 00ffff

Can you try a color picker and see what result you get? Also try one at least one other Mac?

<hr>

# # #  **[atylmo](https://github.com/atylmo)* commented at 2019-09-13 00:41:46*

Hiya. Unfortunately, I don't have access to another Mac :( But I tried a color picker. I get the correct values but they show up wrong on the screen. I've attached a (literal) screenshot to illustrate it.

I was also wrong about 1.9.6. It doesn't happen there. It only happens with Pygame 2.

![F378D84D-DAD1-4B7F-89EA-1288E010E513](https://user-images.githubusercontent.com/48929878/64830275-b3860f80-d59d-11e9-8032-ab550f36814f.jpeg)

<hr>

# # #  **[illume](https://github.com/illume)* commented at 2019-09-13 06:57:48*

Hi,

I guess you get the correct colors in other programs like a web browser?
<hr>

# # #  **[atylmo](https://github.com/atylmo)* commented at 2019-09-13 07:22:45*

Yeah, everything else seems fine. I haven't checked it with a color picker yet, though.
<hr>

# # #  **[atylmo](https://github.com/atylmo)* commented at 2019-10-11 18:39:20*

This still occurs on the newest Catalina and Pygame 2.0.0-dev4.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-12 08:01:52*

@atylmo does this still happen for you with 2.0.0.dev8? We haven't had any other reports of this so I'm not sure what to make of it. I wonder if the behaviour is different it you switch to calling display.update() like so:

    import pygame
    import sys
    
    CYAN = (0, 255, 255)
    
    pygame.init()
    screen = pygame.display.set_mode((640, 480))
    running = True
    
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
    
        screen.fill(CYAN)
        pygame.display.update()

<hr>

# # #  **[eebop](https://github.com/eebop)* commented at 2020-12-07 23:58:00*

Can you you take a screenshot with your computer? If we can use a color picker on that, we can figure out if it's real or just your monitor.
<hr>

# # #  **[Bobbybrojo](https://github.com/Bobbybrojo)* commented at 2020-12-08 09:59:43*

I had this same issue. Here is a screen shot with the left being the color I want and the right shows the pygame window with slightly muted color. I am only referring to the greenish background color in this image. On mac: 
![image](https://user-images.githubusercontent.com/43765519/101469017-06fa2100-38f9-11eb-886d-17d673ade31f.png)

**Comment by MyreMylar** [comment]
I'm going to close this issue as I'm pretty sure it is not happening generally with pygame-ce on mac.
