### ISSUE TITLE
system event only used on windows (1415)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#803]
#  **Issue &numero;1415 opened by *[illume](https://github.com/illume)* at 2019-10-14 10:56:29**

See src_c/event.c SDL_syswm.h and SDL_SYSWMEVENT.
Is there anything useful to include for other platforms?

**Related Docs:** https://www.pygame.org/docs/ref/event.html<hr>

#  Comments

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-12-28 05:14:03*

As I understand, the low level info given by `SDL_SYSWMEVENT` cannot be meaningfully used from a high level language like python. Even SDL docs say
> You are encouraged to avoid this if you can find a less platform-specific way to accomplish your goals.

ATM, we seem to be exposing windows and X11 data to the pygame Event, but we miss `dfb.event`

I don't think this event should be exposed to pygame users. Perhaps pygame can make use of this only internally, and when need comes for it, we can start emitting cross platform pygame events, that could extract use data extracted from this event

**Comment by MyreMylar** [comment]
Don't think we need this.
