### ISSUE TITLE
Docs - param (1448)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#816]
#  **Issue &numero;1448 opened by *[illume](https://github.com/illume)* at 2019-10-22 14:32:17**

We need to decide on how these `:param type name: description` parts are added into the docs.

These types can be used for autocomplete documentation and for type checking with tools like jedi/pycharm/mypy(if they are exported to type stubs). Also I think it's nice to have them in a standard layout in the html docs.

- Do they go below the function description?
- how do the other function signatures relate to this?
- currently the docs are stripped when making the .h file. Not sure what the reasoning behind this decision was, or if it's just a bug.
- do we start making type stubs now, or wait until more things are done?
- We could look at how other projects (like numpy) are doing it.
- what we decide should be documented in the developer guide ([Hacking](https://www.pygame.org/wiki/Hacking))

related: 
- "Types, hints, issues and approach" https://github.com/pygame/pygame/issues/839
- Using types in sphinx docs. Can we use https://github.com/agronholm/sphinx-autodoc-typehints?
- "Most functions should accept keyword arguments" https://github.com/pygame/pygame/issues/808
<hr>

#  Comments

# # #  **[s0lst1ce](https://github.com/s0lst1ce)* commented at 2019-10-22 14:34:48*

I think automatic stubs could already be made. It doesn't matter that most is missing. Using it already may give ideas to structure them better so that it works best. If something important is found it would prevent from having to write portions of the code again. Also mypi generates pretty reasonable ones which should, for now at least, suffice.

**Comment by MyreMylar** [comment]
I think we've committed down several paths for this now.
