### ISSUE TITLE
Fedora Compilation instructions need updating (1487)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#832]
# **Issue &numero;1487 opened by *[illume](https://github.com/illume)* at 2019-11-05 11:15:58**

Fedora/Redhat/CentOS instructions are quite a bit out of date. https://www.pygame.org/wiki/CompileRedHat

- SDL 2 libraries

- git (not subversion)

<hr>

# Comments

**Comment by MyreMylar** [comment]
Any updated Redhat compilation instructions should be added here:
https://github.com/pygame-community/pygame-ce/wiki/Compiling-on-Linux

**Comment by MyreMylar** [comment]
I think this is fairly irrelevant now we have the new build system.
