### ISSUE TITLE
music.play stops working after about 10 hours (1521)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#850]
#  **Issue &numero;1521 opened by *[taylorgrayson](https://github.com/taylorgrayson)* at 2019-11-26 18:44:30**

I was using pygame to play a message on my Raspberry Pi whenever a motion sensor activated and it worked fine for 10-12 hours, then the sound stopped coming out of the speakers. The program continued to run and the logs indicated the file played, but no sound. After trying a number of different options, I finally switched to another package "simpleaudio", which solved the problem. This suggests to me that there is something in pygame that doesn't work well for 24/7 applications.

**Related Docs**: https://www.pygame.org/docs/ref/music.html# pygame.mixer.music.play<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2020-01-18 12:01:04*

Can you tell us what versions of Python, pygame, SDL, and raspbian you were using?
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-12 07:37:41*

@taylorgrayson if you are still interested in this any details would be very useful in tracking things like this down.

You should be able to see version info for pygame just by running any pygame program and looking in the console. e.g.:

    pygame 2.0.0.dev8 (SDL 2.0.12, python 3.8.2)
    Hello from the pygame community. https://www.pygame.org/contribute.html

And Raspbian version info can be found by typing:

    cat /etc/os-release 

into the console.

**Comment by MyreMylar** [comment]
After thinking about I don't think this is feasible for us to resolve as we will not be able to reproduce the conditions in a reasonable fashion.
