### ISSUE TITLE
pygame.midi only offers non-blocking reads and no event mechanism (1581)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#890]
#  **Issue &numero;1581 opened by *[ghost](https://github.com/ghost)* at 2020-02-17 22:27:56**

That is unfortunate because now we only can do polling.
Am I right that the portmedia library underneath has no support for blocking reads either?

**Related Docs:** https://www.pygame.org/docs/ref/midi.html<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-15 19:37:34*

@flok99 Did you discover anything else about this? Right now we're not sure what you want pygame to do, or exactly what you are trying to accomplish.

Here is the pygame documentation for the midi library:

https://www.pygame.org/docs/ref/midi.html

And here is the documentation for the portmidi library that pygame wraps:

http://portmedia.sourceforge.net/portmidi/doxygen/
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-29 16:53:11*

While poking around midi libraries I noticed that RtMidi is the up and coming thing and I wonder if pygame should switch to wrapping that instead in pygame 2.

https://www.music.mcgill.ca/~gary/rtmidi/

Here's an example of another python library that wraps rtmidi: https://spotlightkid.github.io/python-rtmidi/

**Comment by Starbuck5** [comment]
As far as I'm concerned, pygame.midi is maintenance only right now. And since no one has picked this up in the last 3-4 years I think this should be closed out as not planned.
