### ISSUE TITLE
Slow blitting with combined pixel and surface alpha (1618)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#911]
#  **Issue &numero;1618 opened by *[mcpalmer1980](https://github.com/mcpalmer1980)* at 2020-04-04 19:26:26**

I recently discovered that surfaces can use both pixel and surface alpha in pygame2dev6. Curious about performance, I wrote a quick test. My results were somewhat surprising. When combined, the two alphas blit four times slower than either one alone.

Blubberquark suggested I submit an issue, presumably to remind him to take a look at some point. Feel free to close this at any time. This combination wasn't supported in previous releases, and future users hoping for fancy effects with pygame2 will likely use the renderer instead of software surfaces.

```
Test 0: 1000 blits of image size 1333, 1600
tested Blit no alpha: 68.406ms
tested Blit surface alpha: 464.457ms
tested Blit pixel alpha: 381.999ms
tested Blit pixel and surface alpha: 1925.622ms

Test 1: 1000 blits of image size 1333, 1600
tested Blit no alpha: 63.964ms
tested Blit surface alpha: 451.907ms
tested Blit pixel alpha: 380.308ms
tested Blit pixel and surface alpha: 1929.704ms

Test 2: 1000 blits of image size 1333, 1600
tested Blit no alpha: 64.182ms
tested Blit surface alpha: 457.898ms
tested Blit pixel alpha: 375.786ms
tested Blit pixel and surface alpha: 1927.906ms
```

Here's the code I used

```
import time
import pygame

filename = 'flyboy.png'

pygame.display.init()
screen = pygame.display.set_mode((720, 480))
ino_alpha = pygame.image.load(filename).convert()
isurf_alpha = pygame.image.load(filename).convert()
isurf_alpha.set_alpha(100)
ipixel_alpha = pygame.image.load(filename).convert_alpha()
idual_alpha = pygame.image.load(filename).convert_alpha()
idual_alpha.set_alpha(100)

def test(methods, tries = 1000):
	for method in methods:
		start = time.time()
		name = method(tries)
		results = (time.time() - start) * 1000
		print('tested {}: {}ms'.format(name, round(results, 3)))

def no_alpha(tries):
	for t in range(tries):
		screen.blit(ino_alpha, (10,10))
	return 'Blit no alpha'

def surf_alpha(tries):
	for t in range(tries):
		screen.blit(isurf_alpha, (10,10))
	return  'Blit surface alpha'

def pixel_alpha(tries):
	for t in range(tries):
		screen.blit(ipixel_alpha, (10,10))
	return  'Blit pixel alpha'

def dual_alpha(tries):
	for t in range(tries):
		screen.blit(idual_alpha, (10,10))
	return 'Blit pixel and surface alpha'

for i in range(3):
	tries = 1000
	w, h = ino_alpha.get_size()
	print(f'\nTest {i}: {tries} blits of image size {w}, {h}')

	test((no_alpha, surf_alpha, pixel_alpha, dual_alpha), tries)
```

**Related Docs:** https://www.pygame.org/docs/ref/surface.html# pygame.Surface.blit<hr>

#  Comments

# # #  **[nthykier](https://github.com/nthykier)* commented at 2020-05-09 20:45:09*

@mcpalmer1980 Can you share the image `flyboy.png` as well? It will help us debug the issue more reliably.
<hr>

# # #  **[mcpalmer1980](https://github.com/mcpalmer1980)* commented at 2020-05-10 14:06:28*

Sure here's the file
![flyboy](https://user-images.githubusercontent.com/47106920/81501341-dcce7b00-92a5-11ea-9a55-8de7b84c23af.png)

<hr>

# # #  **[nthykier](https://github.com/nthykier)* commented at 2020-05-10 15:36:15*

AFAICT, the slowness happens primarily in `SDL_BlitSurface`.  I am not sure how much we can do about that.

**Comment by MyreMylar** [comment]
Closing this as these are the current results I see in pygame-ce:

```
Test 0: 1000 blits of image size 750, 1050
tested Blit no alpha: 48.01ms
tested Blit surface alpha: 261.058ms
tested Blit pixel alpha: 74.017ms
tested Blit pixel and surface alpha: 177.04ms

Test 1: 1000 blits of image size 750, 1050
tested Blit no alpha: 44.01ms
tested Blit surface alpha: 275.062ms
tested Blit pixel alpha: 74.017ms
tested Blit pixel and surface alpha: 179.04ms

Test 2: 1000 blits of image size 750, 1050
tested Blit no alpha: 45.01ms
tested Blit surface alpha: 254.056ms
tested Blit pixel alpha: 72.016ms
tested Blit pixel and surface alpha: 177.039ms
```

Combining the alpha streams is now actually slightly faster than just doing surface alpha on it's own, about 10 times faster than it was and everything alpha is generally faster all-round (comparing against no alpha speed which hasn't changed as much code-wise).
