### ISSUE TITLE
Investigate cibuildwheel (1661)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#925]
#  **Issue &numero;1661 opened by *[illume](https://github.com/illume)* at 2020-04-22 19:53:32**

- [x] linux and manylinux investigation 
- [x] windows investigation
- [x] mac (it's being used now for our releases)

---
This looks good for removing much our CI code... https://github.com/joerick/cibuildwheel It handles building with lots of different python versions on lots of different build services. Thinking about trying it out just for the MacOS support. They support back to MacOS 10.9 which is better than our last builds which apparently work on MacOS 10.10. Maybe 3000 less lines of build config total. Seems well written, and there are quite a few contributors and projects using it.<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2020-05-11 11:57:15*

It's being used for our MacOS releases. 

I tried this out on linux and had to build a lot of things from source, and it took too long for my 2008 vintage laptop to complete. A few mods were required too.
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-06-11 10:11:22*

Been a while, but quick update on this issue.

We are now using cibuildwheel on manylinux CI too.

That leaves only windows and PiOS on this issue.
As for windows, using cibuildwheel on appveyor is not very smooth because appveyor has custom python installs that cibuildwheel does not recognise (I might open an issue on cibuildwheel to track this) and cibuildwheel instead proceeds to install its own python (which is not that much of a big deal)

About wheels on PiOS (was called raspbian before), [piwheels](https://www.piwheels.org/) already handles that for pygame and many more projects. Popular CIs don't even have armv6/armv7 runners readily available.
<hr>

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2022-07-16 21:41:46*

removed raspberry pi task as I think the world has just settled on using piwheels.

**Comment by MyreMylar** [comment]
We are now using cibuildwheel for everything.
