### ISSUE TITLE
Arcs with width values greater than 1 being drawn with tiny holes/gaps (1663)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#926]
#  **Issue &numero;1663 opened by *[MightyJosip](https://github.com/MightyJosip)* at 2020-04-24 13:40:33**

Arcs drawn with width values greater than 1 may contain tiny holes/gaps. This is shown by the following code as the resulting arc contains tiny gaps where it should be a solid color.

    import pygame
    import time

    pygame.display.init()
    screen = pygame.display.set_mode((100, 100))
    rect = pygame.Rect((0, 0), (80, 70))
    rect.center = screen.get_rect().center

    pygame.draw.arc(screen, pygame.Color('yellow'), rect, 1, 2, 35)
    pygame.display.flip()

    time.sleep(10)
    pygame.display.quit()

Resulting arc with tiny gaps.

![image](https://user-images.githubusercontent.com/29337110/80218691-cab3d200-8641-11ea-9f4f-0ede7984b472.png)

System details:

    os: windows 10 (64bit)
    python: 3.7.4 (64bit)
    pygame: 2.0.0.dev7 (SDL: 2.0.12)

**Related docs:** https://www.pygame.org/docs/ref/draw.html# pygame.draw.arc
<hr>

#  Comments

# # #  **[Mushguys](https://github.com/Mushguys)* commented at 2020-06-28 17:45:09*

This looks to me like the resolution of the arc is too low. I can't be sure without seeing the code.
Where is the internal code for drawing arcs?
<hr>

# # #  **[MightyJosip](https://github.com/MightyJosip)* commented at 2020-06-28 21:23:43*

Another example

```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((200, 200))
rect = pygame.Rect((0, 0), (180, 170))
rect.center = screen.get_rect().center
pygame.draw.arc(screen, pygame.Color('yellow'), rect, 1, 2, 70)
pygame.display.flip()
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            quit()
```

Source code for drawing arc:
front-end: https://github.com/pygame/pygame/blob/master/src_c/draw.c# L498-L574
algorithm: https://github.com/pygame/pygame/blob/master/src_c/draw.c# L1326-L1371
<hr>

# # #  **[Mushguys](https://github.com/Mushguys)* commented at 2020-07-03 17:23:58*

The problem seems to be here:
[https://github.com/pygame/pygame/blob/master/src_c/draw.c# L556-L560](https://github.com/pygame/pygame/blob/master/src_c/draw.c# L556-L560)
This code draws multiple arcs to make up a single, wider arc. The radii of the arcs are drawn at one-pixel intervals, which is large enough for holes in between the arcs. A smaller interval should fix it, but I'm not sure just how small.

**Comment by Starbuck5** [comment]
This has been resolved in #2344
