### ISSUE TITLE
SDL2: Fullscreen not backwards compatible (1713)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#939]
#  **Issue &numero;1713 opened by *[mcpalmer1980](https://github.com/mcpalmer1980)* at 2020-05-08 21:01:32**

Games developed for pygame versions < 2.0 expect FULLSCREEN to change the resolution to equal the width and height requested by a call to pygame.setmode(). There were some issues with screen flicker and graphical artifacts when changing to fullscreen, which I hid by filling the screen black and delaying 200ms.

From what I understand, newer versions of pygame don't change the resolution but use a 'windowed fullscreen mode' instead. The pygame display surface does not scale to the display resolution in FULLSCREEN, however.

There is a SCALED flag that may be combined with FULLSCREEN when calling pygame.setmode(). This fills the screen as expected but the image is scaled using a nearest pixel algorithm that creates screen artifacts, especially in animations. Setting the SDL_RENDER_SCALE_QUALITY environment variable to 1 or 2 enables bi-linear or anisotropic filtering, respectively.

These issues are easily remedied and I'm happy with the options I've provided in my games. But there are many older pygame games that don't work properly and have nobody to update them. I would recommend defaulting to SCALED with bilinear filtering enabled by default, falling back to nearest pixel scaling only where bilinear hardware support is lacking.

**Related Docs**: https://www.pygame.org/docs/ref/display.html# pygame.display.set_mode<hr>

#  Comments

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2020-05-13 06:22:31*

I don't think we should default to bilinear filtering, for technical reasons and because of the intended use cases of SCALED, but we can make the API more accessible and document it. The current state of SCALED is a bit unfortunate, as my work was merged with a bunch of TODO stuff in the code (but the tests ran through) right before I finalised the API. We should revisit this after # 1704.

**Comment by Starbuck5** [comment]
Given how long this behavior has now been in the world, I don't think there are any plans to change it right now, so let's close this out.
